### ISSUE TITLE
Scrollbar in animation

### ISSUE THREAD

**Issue by JustinDrake** [voisine/breadwallet#104]
This is a minor UI detail. In the pane with the list of historical transactions, tapping a transaction starts an animation to a 'transactions details' pane. This animation includes the scrollbar if it is visible at tap-time.

**Comment by voisine** [comment]
this is difficult to fix and not really much of an issue. I'd prefer to keep the code clean rather than try to change the default navcontroller behavior with respect to scroll bars.
