### ISSUE TITLE
Allow keeping address but rejecting amount.

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#123]
Today I saw a performer who printed a QR for bitcoin, was about to tip... then BAM... "Would you like to spend 1 BTC to 1xxxxx...?"

My only option was pay 1 BTC or not at all.

Maybe add an extra button "Copy Address to clipboard" or something?

It was not a BIP70 request, it was just a URI with the `&amount=1`

None of my other wallets had coins in them, so I walked away without giving anything :-(

Maybe it's a fringe case, but would have been nice to have a way to copy the address or otherwise change the amount.

**Comment by teran-mckinney** [comment]
Thank you! This is awesome.
