### ISSUE TITLE
Technically not RFC6979 compliant

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#128]
Comparing:
https://github.com/voisine/breadwallet/blob/master/BreadWallet/BRKey.m#L58
With:
https://tools.ietf.org/html/rfc6979#section-3.2

It seems you stop at Step: H-2 with `T = T || V` (or T = V in our case, as sha256 will always be the bitlength of qlen)

In order to be 100% compliant with RFC6979, one must evaluate that T (or its integer form `k`) to make sure it is between {1, N-1} (inclusive) where N is the order of secp256k1 curve, AND also make sure that the value does not result in a (r == 0 or s == 0) scenario.

This can be seen here:

> If that value of k is **within the [1,q-1]** range, and **is
> suitable for DSA or ECDSA (i.e., it results in an r value
> that is not 0**; see Section 3.4), then the generation of k is
> finished.  The obtained value of k is used in DSA or ECDSA.
> **Otherwise, compute**:

If either of these failure cases are true, then the following must occur.

```objective-c
[V appendBytes:"\0" length:1];
CCHmac(kCCHmacAlgSHA256, K.bytes, K.length, V.bytes, V.length, K.mutableBytes); // K = HMAC_K(V || 0x00)
V.length = CC_SHA256_DIGEST_LENGTH;
CCHmac(kCCHmacAlgSHA256, K.bytes, K.length, V.bytes, V.length, V.mutableBytes); // V = HMAC_K(V)
CCHmac(kCCHmacAlgSHA256, K.bytes, K.length, V.bytes, V.length, T.mutableBytes); // T = HMAC_K(V)
```

One way that bitcore manages it is using an int during the sign function called `badrs`
See: https://github.com/bitpay/bitcore/blob/b1557a25abb00f19d07db632913bd8e37b66d7ea/lib/crypto/ecdsa.js#L207

They perform a do while loop with conditions of r == 0 or s == 0 (out of bounds check is within the k generation function), and increment badrs after k generation so that if the do loops, the 2nd time around it will force 1 loop with badrs == 1. This makes it 100% RFC6979 compliant (for secp256k1 x sha256 anyways) This means that they only have to calculate r and s once if it's ok as is. Adding a separate r,s check function would mean each signature would require calculating the same r and s twice, even if it was ok the first time.

1. How would you like to tackle this issue? (or are you fine with staying only 99.99999...% RFC6979 compliant (considering these fringe cases are so rare) )

2. Leaving it alone should be fine, but I would like to ask, what would theoretically happen if a generated k was outside bounds or r or s resulted in 0? (I'm sorry, I am not good at reading objective-c, so I couldn't follow up to that point)

**Comment by voisine** [comment]
It's nice to know others are paying attention to the code. :)

Not doing the bounds checking was a deliberate choice, but I'm happy to discuss if it was the right one. The argument against it is that it complicates the code and creates more opportunities for error. The chances of generating an invalid k are approximately 1 in 2^128, which is the same as the chances of randomly generating someone else's wallet seed.

If by some astronomical fluke it were to happen, then the sign method would return nil, and the user would see "couldn't make payment, error signing bitcoin transaction". The funds would still be retrievable using a non-RFC6979 signature, either with another wallet or modified breadwallet.

**Comment by dabura667** [comment]
> The argument against it is that it complicates the code and creates more opportunities for error.
A very valid point.

> the user would see "couldn't make payment, error signing bitcoin transaction". The funds would still be retrievable using a non-RFC6979 signature, either with another wallet or by modifying breadwallet.
perhaps using the rng used for seed generation if k returns nil would be a simple, hard to mess up, solution.

However, what about the 2 in 2^256 (ish) chance of r == 0 or s == 0? Does it return nil? Generating a sig with r or s as 0 is basically publishing the private key...

One of the reasons I didn't bother trying to do a PR is that objective-c seems like an easy-to-screw-up language... so I understand your concerns...

Considering the amazingly small likelihood of this being a problem, it's probably a low priority... but if you were to add the loop, would you call a function to generate r and s from within the RFC6979 generation? (that seems like a less screw-up-able way to do it, and 1 extra r and s generation is not that expensive)

**Comment by voisine** [comment]
Looking at the openssl signature code, it does check that s is not zero internally, but not r if r is provided.

Being a deterministic wallet, transactions typically involve transferring all the balance from any keys used to a new change address, so even revealing one of your private keys wouldn't be a total disaster (unless your public seed was also compromised), but still would be bad. Again though it's essentially impossible for it to happen. You're probably a lot more likely to get a cosmic ray induced bit flip that results in an r or s being zero. (there are actually practical security attacks that take advantage of the phenomena: http://arcussolutions.com/blog/how-cosmic-rays-can-make-your-site-less-secure )

If I was going to put in the bounds checking I would prefer to do it in a way that only does additional calculations if the values are out-of-bounds.

**Comment by dabura667** [comment]
> If I was going to put in the bounds checking I would prefer to do it in a way that only does additional calculations if the values are out-of-bounds.

Considering out of bounds being 1 in 2^122 and r or s being 0 is 2 in 2^256, I guess checking for the more likely one (though honestly still not likely at all) seems like a good compromise.

**Comment by voisine** [comment]
The secp256k1 curve order is FFFFFFFF FFFFFFFF FFFFFFFF FFFFFFFE BAAEDCE6 AF48A03B BFD25E8C D0364141

By my count that's between 1 in 2^127 and 2^128 (slightly closer to 2^128)

**Comment by voisine** [comment]
we're now using the rfc6979 implementation from libsecp256k1
