### ISSUE TITLE
What! Yes it's a valid address, it's a (best practice) multi-sig address.

### ISSUE THREAD

**Issue by webdeli** [voisine/breadwallet#129]
Hi Aaron,

I love your wallet app. As it carries my daily spend - but Melbourne Bitcoin Technology Center (MBTC) has a multi-sig address as it's donation address.. I can't donate to my own foundation with Breadwallet.

Could you please remedy this in the next release? (photo attached)
![img_1948](https://cloud.githubusercontent.com/assets/218085/5610577/b11d30e6-950d-11e4-9d4f-071ec8f1560d.jpg)

**Comment by dabura667** [comment]
Could you tell me what exactly is encoded in that QR?

I want to know if it has the "bitcoin:" prefix or not.

**Comment by webdeli** [comment]
Sure - encoded is: 32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD1F

This is the public key for donations to the Melbourne Bitcoin Technology Center.

**Comment by dabura667** [comment]
The problem is the QR code:

QR code says "32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD"

Their actual address is "32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD1F"

Missing a 1F from the QR code.

I hope you haven't sent anything to that!

(or rather, I hope no app LETS you send anything to that... the checksum is broken.)

**Comment by webdeli** [comment]
Oh.. yeah.. so.. It should be:  "bitcoin:32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD1F" and "32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD1F" gets rejected. Hmm. Facepalm.

**Comment by chrismarquardt** [comment]
Simple answer: whoever made that sign messed up the QR code. You should be
glad Breadwallet didn't let you send BTC to this mangled address.

**Comment by dabura667** [comment]
@webdeli breadwallet supports both of those.

Unfortunately, the QR code you took a picture of is missing letters. (It is an incorrect address)

**Comment by dabura667** [comment]
QR code contains:

> 32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD

The correct address is:

> 32fRLsMg4gE1QQKH1kdrwAF6DHQjWQUD**1F**

Because the QR code is missing the last two letters of the address, this address is no longer valid.

**Comment by dabura667** [comment]
![qrcode 26834421](https://cloud.githubusercontent.com/assets/6586275/5612223/c1fcffde-9514-11e4-97b3-3bbc7b966294.png)

Here's the **CORRECT** QR code.

**Comment by webdeli** [comment]
(I made the sign, prototype 1 off.. so great early catch). 

I *COMPLETELY* agree it's fantastic Bread wallet didn't accept the QR.

Even though in testing I would only pushing a small transaction at the address, I wasn't going for a proof-of-burn kind of thing where the bitcoins went to an invalid address.

OK. User error. Issue closed.

Thank you all. Julian Smith.
