### ISSUE TITLE
Unable to send to clipboard address since rescanning blockchain

### ISSUE THREAD

**Issue by NanoAkron** [voisine/breadwallet#132]
Hi @voisine I've been using breadwallet to give away some bitcoins over xmas but this is a problem I've not seen before:
1. Brother downloaded breadwallet. Sent me his address via SMS
2. Tried to send some bits to the address in the clipboard from a less-than-perfect wifi network. Given 'couldn't make payment, transaction canceled, network timeout' message
3. Turned off wifi. Retried over 3G and 4G connections (depending on where I was standing in the building) with the same message
4. Tried on different wifi network. Still the same message
5. Tried rescanning the blockchain. I think here I tried swiping up and turning wifi back off because it was a very slow connection. Logged back in to breadwallet and here I think rescanning went back to 0%
6. Only had 10% battery left so waited until I got back home, plugged in and waited for the blockchain resync. This took about 4 hours on my home wifi.
7. Tried resending to his address. Still failing with same error message.

Any thoughts? Should I wipe it and reload the wallet from the backup phrase?

**Comment by voisine** [comment]
Sorry for the frustrating experience. A rescan shouldn't take 4 hours, it should only take a few minutes. If it pauses without making progress for more than a minute or two, then it's stalled. You can kill the app and restart it, or possibly try toggling airplane mode.

If you're having trouble sending, then it's probably because the transaction went through but the wallet thinks it didn't, so a rescan is what you need. This will all be handled much better in the next update.

**Comment by NanoAkron** [comment]
Hi @voisine - thanks for replying so quickly.

Unfortunately even after the extensive rescan (and another quicker rescan since then) it still refuses to send (or maybe acknowledge the send).

I've tried killing and restarting the app but with no success, and also paying an address via a QR code. I think I'm going to have to delete and reinstall it with my wallet seed.

By the way, you should have a tip address available somewhere!

**Comment by NanoAkron** [comment]
Further update: I deleted the app and reinstalled it. It had preserved my pin code and I didn't have to recreate the wallet, it just rescanned for a couple of minutes.

Then it let me send successfully first time to the address in the clipboard (also preserved).

Strange...any ideas?

**Comment by jreighley** [comment]
I am seeing simular behaviors.  Cannot send..  Doesn't seem to care what network I am on.  Haven't tried deleting and re-installing yet..

**Comment by voisine** [comment]
@NanoAkron and @jreighley, is the problem that the app doesn't complete syncing? I wonder if this is the same issue as #135 ?

**Comment by NanoAkron** [comment]
Hi @voisine - it's been over 2 weeks now so I can't quite remember all of the details. As I recall, it resynced VERY slowly over about 4 hours, but still wouldn't let me send bitcoins. So I forced a resync which was much quicker. Both times the syncing reached 100% and completed, but wouldn't let me send. 

So I had no other option but to try to wipe the app and restore my wallet from the passphrase, but fortunately just wiping and reinstalling fixed the problem.

Hope this helps somehow.

**Comment by jreighley** [comment]
@voisine,  I do suspect that it was the 135 issue.   I re-installed breadwallet, and it began working again properly.

**Comment by voisine** [comment]
gonna close this one, there are several improvements to both syncing and missing transactions in master.
