### ISSUE TITLE
Receive address doesn't update as transaction comes in

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#133]
I had breadwallet sitting on the receive screen while a transaction came in. In the current version this didn't update the address or the QR code to a new one. I tapped to the history, then back to the receive screen and the address was still the same. Only when I swiped to the send screen and then back did the address get replaced with a new one.

**Comment by dabura667** [comment]
+1 I noticed this a while back and subconsciously swipe back and forth when I need a new address.

**Comment by voisine** [comment]
Yes, at the time I thought it would be better to hide the address change to avoid confusion, but the current version in master gives you a little alert message and changes the receive address right away. So already done in the code.
