### ISSUE TITLE
Stuck at syncing 

### ISSUE THREAD

**Issue by Fogh** [voisine/breadwallet#135]
A few days back my wallet started being unable to synchronize. If a try to rescan blockchain it just get stuck again at random place in the syncing process. Force closing the app and trying to sync again don't work either.

**Comment by voisine** [comment]
Sorry this is happening. I'm working on more syncing improvements as we speak and there are several already in the code.

I see you are an iOS developer, so it would be great if you can install the latest from master and let me know if it corrects the problem or if there's another issue that hasn't been resolved yet. Are you comfortable doing that?

**Comment by nshopik** [comment]
I'm also recently start seeing this issue. From what I see just few minutes ago its geting worse, just made payment and it not appears in history.

**Comment by Fogh** [comment]
Okay cool. Maybe I should have looked at the commit history before posting this issue then. 

I just installed the master and it worked (after I disabled testnet) and syncing did complete, but it took a long time.

**Comment by voisine** [comment]
@nshopik does a rescan get the transaction back?

**Comment by nshopik** [comment]
@voisine rescan always stuck around 13%, so transcation now appears just always unverifed, since it unable to finish rescan for hour now (I restart app few times)

**Comment by dabura667** [comment]
@voisine Can you set up a testflight or a hockeyapp or something to push out dev beta versions between Appstore updates?

**Comment by ejhong** [comment]
I've seen this before as well. Only fix for me was to reinstall the
original app. So the fact that install of new code fixed things doesn't
necessarily mean anything. A reinstall of old code may solve it as well and
should be tried first maybe.

**Comment by voisine** [comment]
@dabura667 I'm planning on doing a testflight release as soon as the syncing issues are resolved. I believe I can only invite people via email, so you can email me and I'll add you. (that goes for anyone else following the project also)

@nshopik someone I know is having the same issue. I'll be able to debug on their phone tomorrow and see what's going on.

**Comment by dabura667** [comment]
@voisine Sounds great, #69 has my UUID and I can send my email.

**Comment by voisine** [comment]
soooo... debugging my friends phone that's stuck, not syncing, and his phone is trying to connect only to nodes in this class-c: 46.105.210.x

It looks like a tarpit attack where a malicious node tells you only about nodes it controls when you're doing node discovery. 

@dabura667 you can break out of it by deleting and re-installing the app obviously, but if you can also force it to fall back to DNS node discovery if you can get the "not connected" status bar to appear (try turning on airplane mode) and tap it.

**Comment by nshopik** [comment]
@voisine tried to go into airplane mode, and then tap on "not connected" bar then disable airplane mode, that doesn't seems fallback to DNS discovery.

If I delete app I assume I lose all my history of transactions right and will be need to recover from backup phrase?

**Comment by nshopik** [comment]
Anyway, I've able to resync it by just disable routing to 46.105.210.x net on router

**Comment by voisine** [comment]
@nshopik no, if you delete and reinstall the app, it will remember your backup phrase, but will need to re-sync.

That's great confirmation that you were stuck in the same tarpit. I'm working on detecting and dealing with it now.

**Comment by ryanvarley** [comment]
Same issue - also fixed by blocking the 46.105.210.x range

**Comment by voisine** [comment]
Thanks @ryanvarley, I need to do better detection and handling of nodes that don't respond in the expected way to protocol messages.

**Comment by Fogh** [comment]
Nice work! :+1:

**Comment by nshopik** [comment]
@voisine Its been while since previous release and lots fixes already on master, what your plans to publish new version?

**Comment by voisine** [comment]
The syncing issues people have with the current version is something I want to address quickly. I've got a few more changes I think will be important and then hopefully I can get an expedited review and get it in the app store early next week.

Then I want to do internationalization/translation and release another update with that soon after.

**Comment by Fogh** [comment]
I'm up for helping with danish localization.

**Comment by antris** [comment]
I still have this same problem. Sync gets stuck in a random place and never finishes.

**Comment by NicosKaralis** [comment]
Same problem here, 5 days ago the app stopped syncing and I can't see progress because now it is an orange bar with no percentage not block number
