### ISSUE TITLE
Bread wallet does not notice network/online/wifi state change

### ISSUE THREAD

**Issue by mcelrath** [voisine/breadwallet#137]
If started when the network/wifi is unavailable, Bread Wallet will complain that the bitcoin network is not reachable, even if the network does become available later.  It seems to stay in this this "disconnected" state.

Bread wallet should re-check for network availability before complaining that it can't connect to the network.

**Comment by voisine** [comment]
I'm not able to reproduce this. If I turn on airplane mode, it shows "not connected", then when I turn off airplane mode it reconnects automatically. Can you get it to happen consistently?

**Comment by truongvinht** [comment]
I think it is because of the Reachability framework. I also used it on other apps and sometimes it can't detect the network ability correctly. Its really strange...
