### ISSUE TITLE
Stuck sync; Network timeout

### ISSUE THREAD

**Issue by jamilbk** [voisine/breadwallet#138]
I'm encountering a show-stopping bug with Bread Wallet. My wallet never seems to stay in sync. If I rescan the blockchain, I usually get to 91.9% within a few seconds, then it takes hours to finish from there. This is on a 10 Mb DSL connection (LTE doesn't seem to be any faster). Occasionally, the app crashes during these periods of long sync.

If I try to send a transaction, the blue progress bar take about 30 seconds to complete, and then I get a Network timeout error.

"Quitting" Bread Wallet and re-opening doesn't make a difference. Nor does rebooting my phone.

I *did* save the backup passphrase, but I'm afraid to attempt a restore from backup due to the this bug: #95 .

I have a non-trivial amount of BTC I stored in Bread Wallet for a trip I was planning to take, but since there's no way to export my private key, my bitcoin is stuck in limbo.

Any help?

iPhone 5S
iOS 8.1.3

**Comment by voisine** [comment]
We tracked the final commenters issue on #95 down to a core data corruption problem. If you delete and reinstall the app, you don't need to restore, your backup phrase remains on the keychain.

Alternately if you prefer, you can email me  and I can work with you to track down the specific issue. 

You can also derive all your private keys from your backup phrase using other tools, but they are less secure than an app running on a malware hardened device like iPhone.

**Comment by jamilbk** [comment]
Thanks!

Deleted and reinstalled, and I'm all set now.
