### ISSUE TITLE
Transactions not completing. 

### ISSUE THREAD

**Issue by pdadon47** [voisine/breadwallet#139]
Hello I've recently start using bread wallet and my first transaction went through. But now every time I try to send money a pop message come up and say transaction cancelled network timeout. Is there away to fix this problem?

**Comment by NanoAkron** [comment]
I had this. Try deleting the app, restarting your phone and reinstalling it. Make sure you write down your passphrase first though.

I believe @voisine is releasing an update soon to address this.

**Comment by pdadon47** [comment]
Thank you. I'll try it btw did it work for you

**Comment by NanoAkron** [comment]
Yes it did. And the phone had remembered my wallet/keychain details even after deleting and reinstalling so I didn't actually need the passphrase in the end.

Please report back if this works for you as well.

**Comment by pdadon47** [comment]
Thank you very much. I appreciate it actually worked for me.

**Comment by voisine** [comment]
@pdadon47 glad this worked for you, thanks @NanoAkron 

There's a bunch of bitcoin network peers popping up recently that misbehave with respect to syncing, probably in an effort to cut down on bandwidth usage while attempting to gather information about other peers. I have checks in the code to detect the problem and disconnect now, and seems to be working in my testing.
