### ISSUE TITLE
Crytpo Error

### ISSUE THREAD

**Issue by ReggieST** [voisine/breadwallet#140]
I'm attempting to run Bread Wallet xcode project. I receive this error ->/Users/Reggie/Library/Developer/Xcode/DerivedData/BreadWallet-adpqwshoblmhprbqzxitzjeahpmw/Build/Intermediates/BreadWallet.build/Debug-iphonesimulator/crypto.build/Script-752B78CF1A1F098600A78D9E.sh: line 3: ./Configure: No such file or directory.

How do I resolve this issue?  
Thanks in advance

**Comment by voisine** [comment]
Sounds like the openssl git submodule isn't initialized. Do you get any errors if you go to the top breadwallet directory and run 'git submodule init' ?

**Comment by ReggieST** [comment]
I'll try that shortly.. Thanks

**Comment by voisine** [comment]
Going to close this one. If you're still having trouble, feel free to reopen.

**Comment by jpoorni** [comment]
hi,

i am also getting the same error. i am new to xcode, so can you clearly explain me the steps to resolve this problem.
