### ISSUE TITLE
SLOW, 4hr synching..not sending!!! iPhone 4, with iOS 8.1.3 (japanese)

### ISSUE THREAD

**Issue by happygeorge** [voisine/breadwallet#143]
My friend's first experience with Bitcoin went rather badly! :(

on his  iPhone 4, with iOS 8.1.3 (japanese) the wallet did not show the BTC I sent him, so we asked the program to RESCAN... nothing happened, the screen just flashed, and nothing.

Then a friend said we need to kill the app, restart and do it again.  So we did. 

The rescan showed "synching" at the top of the app this time, and the % done... it got to about 87% in a few minutes, and then it got "stuck"... we ended up waiting for about 4 hours!!!

The funds did show... but my friend got so spooked, he just wanted to send the BTC back, when we tried that.. it kept saying "timeout failure..." or something like that

We thought it was maybe the slow internet from my hotspot, so he went home, and tried it on his own WIFI... it still doesn't send... what can we do?

**Comment by dabura667** [comment]
バックアップ用のフレーズ控えておいて、 https://web.hivewallet.com/ にアクセスしてもらってください。

「既存ウォレットを開く」押してからバックアップフレーズ入力⇒同じアドレスが表示されるので送金可能になります。

breadwalletは直接ビットコインのネットワークとやり取りするため、
ポート8333が必要です。、無料Wifiはよくポート80以外をブロックします。
家のWiFiルータの機種によってはポート8333をブロックするかもしれません。
できればbreadwalletをご利用の際、4Gなどで接続するといいです。

**Comment by voisine** [comment]
Really sorry that happened. It should never take that long to sync. If it stalls for more than a minute or two with the current version the best option is to kill the app and restart, or if it persists you delete the app and reinstall.

If you'd like, you can email me and I can help you try out the latest update that should do a better job detecting and handling the issue. My email is in the LICENSE file.

**Comment by happygeorge** [comment]
Thanks for the advice

We'll try reinstall, and let you know how it went

**Comment by happygeorge** [comment]
The removal/reinstall worked!  Fast syching, and the transaction also sent immediately!

Thank you!
