### ISSUE TITLE
app won't sync

### ISSUE THREAD

**Issue by hughht5** [voisine/breadwallet#145]
My wallet won't sync. It's been like this for a couple of weeks at least and i've abandoned you for blockchain. I far prefer your wallet though :(

Any idea why it won't sync?

**Comment by voisine** [comment]
Try deleting and reinstalling the app. There's a set of nodes that are "tarpitting" clients. There's an uodate waiting for review that detects and handles it

**Comment by hughht5** [comment]
thanks - I'll give it a go.

**Comment by dabura667** [comment]
tarpitting? care to explain?

I'm slightly interested.

**Comment by nshopik** [comment]
@dabura667 my understanding its when it connect to nodes which controlled by same owner, thus you may stuck in syncing as nodes configured same and may limit requests by not giving your data in time manner.

**Comment by voisine** [comment]
There are some nodes that only report other nodes controlled by the same operator when asked for a list of peers, and they also only sync a few blocks and stop, so it causes stalled syncing. I assume it's an attempt to save bandwidth while collecting information about the network.
