### ISSUE TITLE
Evaluate replacing OpenSSL with libsecp256k1

### ISSUE THREAD

**Issue by prusnak** [voisine/breadwallet#148]
Bitcoin Core guys are working on a library called libsecp256k1. You might consider replacing OpenSSL dependency with a dependency to libsecp256k1. Source: https://github.com/bitcoin/secp256k1

That said, I am perfectly fine with OpenSSL usage in your code and it seems that libsecp256k1 is missing RIPEMD160 hash you are using. Feel free to close if it does not seem worth the effort, just wanted to provide some food for thought. :-)

**Comment by voisine** [comment]
I'd love to get rid of the openssl dependency. The most challenging part will be the bignum library. libsecp256k1 I think only handles bignums up to 256bits and there's a few places where we need more, like base58check encoding a private key. (288bits with checksum)

I'd love to do it though. Openssl is the only big external library dependency. I'd much rather replace it with something lightweight. I think I already have a standalone ripemd implementation in the github history somewhere that I removed when I noticed it was included in openssl.

**Comment by voisine** [comment]
@prusnak I discovered Luke Dashjr's libbase58 that you're using in trezor-crypto, which implements base58 without using bignums, and adapted it for breadwallet.
https://github.com/voisine/breadwallet/commit/fe1b1f2bc009605267942537d6d85820816418c7

That was the only place in the code that was using larger than 256bit bugnums. Between that and the non-openssl ripemd implementation. I should now be able to switch to libsecp256k1 and get rid of openssl entirely.
https://github.com/voisine/breadwallet/commit/4c169e4496e868a98230002978f16b8ad8d5b0ce

**Comment by Andr3wHur5t** [comment]
I've been working on a easy to use Bitcoin library for iOS based off of your work in Breadwallet, the first thing I did was replace openSSL with libsecp256k1. 

While doing my HD wallet implementation I ran into a problem of missing EC point operations needed for parent pub key -> child pub key deviation because there I couldn't find visible interfaces in libsecp256k1.

Its still WIP but here is a link if your interested https://github.com/Andr3wHur5t/Breadcrumb

**Comment by voisine** [comment]
very cool @Andr3wHur5t, I will keep an eye on this. Feel free to submit back any fixes or improvements.
