### ISSUE TITLE
Payment info not transferred to app whenit has to sync on opening

### ISSUE THREAD

**Issue by bamos01** [voisine/breadwallet#149]
I have noticed that normally when I click on a bitcoin address, Breadwallet opens like it should and the request details (e.g payee address, quantity, payee name) are accurately transferred to the app, allowing payment with one- click [great!].  However, when the app opens in this context and it has to sync for a little bit (i.e. it hasn't been used in a while), then the payment request details are not transferred.  If you then repeat the process right away for a second time (i.e. after the update sync has occurred), it works as expected.

**Comment by voisine** [comment]
ooh... this is a good catch. I open it frequently enough that I've never seen this happen. Looking at the current code I don't immediately see any reason for it not to handle a url request while the syncing is still happening, but I'll see if I can replicate it in the current app store version.

**Comment by throughnothing** [comment]
I've actually seen this exact behavior as well, but hadn't yet made the connection with the syncing.  I've definitely had to try twice when clicking on a link b/c it doesn't load the payment details on the first try.

**Comment by voisine** [comment]
@bamos01 @throughnothing please let me know if you see the problem again with the new update.
