### ISSUE TITLE
Export all used addresses

### ISSUE THREAD

**Issue by kgreenek** [voisine/breadwallet#150]
I'd really like to be able to export all the addresses that have ever been used to send/receive bitcoin. This is very important when doing your taxes.

Libratax has a feature where you just import all the addresses from all of your wallets, and it'll scan the blockchain to determine what the transactions were, and automatically calculate my taxes (including figuring out which ones were transfers to myself).

Right now this is a huge pain in breadwallet. I have to manually inspect the transactions in the UI to figure out what the addresses were and copy-paste them into my own spreadsheet from mobile. Icky.

**Comment by voisine** [comment]
This is similar to #45, export tx list. Similar discussion on that one.
