### ISSUE TITLE
Recovering backup phrase from encrypted iTunes Backup

### ISSUE THREAD

**Issue by bslayton** [voisine/breadwallet#151]
I got a new iPhone a few weeks ago as my previous one was acting up. Went to Apple and traded it in for a new one. I know for a fact I have an encrypted iTunes backup with breadwallet. Does anyone know how I can track down my backup phrase from my iTunes backup?

**Comment by voisine** [comment]
iTunes backups of your wallet are encrypted to the specific device. You need the device the backup was made from to decrypt it. To recover your wallet on another device you need the backup phrase. Storing your wallet in iTunes encrypted only with a password would expose you to desktop malware theft.

**Comment by bslayton** [comment]
Ahhh. That's a bummer. I had restored from backup before and noticed my wallet was restored. It was an easy assumption to make that an ios restore on another device would restore my wallets as well. Shoot. Thanks for your help!

**Comment by throughnothing** [comment]
This is actually good to know.  @bslayton I made the same assumption.  I wonder if this isn't something that could be documented/explained to the user better.  "iTunes backups are not sufficient if you get a new device" or some better wording than that.

**Comment by voisine** [comment]
Yes, I need to make this more clear somehow. The current version says "if you ever lose your phone, you will need this phrase to recover your wallet. please write it down."

But people don't believe it's actually true.

**Comment by bslayton** [comment]
Right. It's definitely a bit naive on my part. Fortunately I didn't have but like $5-10 bucks on there so it's no biggy. My assumption was you will need this phrase if you lose your phone and don't have a backup. So for a cost of ~$10 bucks, I learned I ABSOLUTELY have to keep a paper copy of the phrase.

**Comment by throughnothing** [comment]
@voisine maybe just adding "An iTumes backup will not be enough" to the end of that would work for now.

**Comment by throughnothing** [comment]
@voisine Based on your comment, I'm also curious if you don't recommend backing up a phone with breadwallet on it to iTunes.  I hadn't thought about it before, but it does lessen your security, b/c you could have malware recording your backup passphrase, etc.  Though if it's locked to the hardware in your phone, maybe that doesn't matter?

**Comment by voisine** [comment]
@throughnothing that's right, backups to iTunes or iCloud are fine because the recovery phrase is strongly encrypted to a key fabbed into the device and can only be restored to the same device. If an attacker gets a copy of your backup they can't do anything with it without the phone.

**Comment by throughnothing** [comment]
@voisine great to know.  Thanks!

**Comment by throughnothing** [comment]
Sorry to ping this thread again, but I'm curious what hardware this is true for?  All iPhones?  Curious as I still have an original 5 that I use breadwallet on.

**Comment by dabura667** [comment]
All hardware.

**Comment by voisine** [comment]
Yes, at least all hardware that can run breadwallet, not sure about pre-iPhone4.
