### ISSUE TITLE
Support restoring BIP39 with optional password (salt)

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#156]
This can be relegated to a small little "Advanced" button on the recovery phrase input screen.

I like Mycelium's UI for phrase managing. They don't give the advanced options on wallet creation, and they make advanced users who already know what they're doing jump through a little hoop by only allowing password usage for recovery and not generation.
(One of the reasons they do this is to prevent the misconception that the password is somehow "locking the recovery phrase")

When the advanced button is tapped, a short explanation of the password should be there in case a non-advanced user explores and misunderstands what it is for.

"The optional password generates a new wallet from the same recovery phrase. If you are using a wallet generated by breadwallet then you should leave this blank. Using a password to restore your wallet will require you to remember both your password AND your recovery phrase. Please be careful."

**Comment by voisine** [comment]
I like this. We definitely need to consider this for #131
