### ISSUE TITLE
Invisible text area

### ISSUE THREAD

**Issue by nshopik** [voisine/breadwallet#158]
Take look into screenshot, I don't think I should allowed to enter any text there (text only show as long I keep keyboard open)

![img_0650](https://cloud.githubusercontent.com/assets/4439311/6320443/97b27bdc-baee-11e4-883b-f385f2b1678d.PNG)

**Comment by voisine** [comment]
When the keyboard is open, you can see the entire contents of the clipboard and edit it. When the keyboard is closed, it only shows a valid bitcoin address that will be used if you tap the "pay address from clipboard" button.

**Comment by nshopik** [comment]
Well I can come up with any idea why I need to edit address, just get new from clipboard. if this intended you may close issue, but I feel this is unnecessary feature here, but I could be wrong.

**Comment by voisine** [comment]
I felt like there needed to be a way to manually type in an address if you really wanted to, but I didn't want to clutter the UI with input boxes, because typing stuff in is a pain and I don't expect people to do it hardly at all.
