### ISSUE TITLE
Locale Issue

### ISSUE THREAD

**Issue by victorengel** [voisine/breadwallet#161]
Today, I tried sending a friend of mine some bitcoin. Several attempts failed. I finally was able to get it to work after changing some localization settings. My settings that I'm assuming caused the failure included the following:

iPhone Language: English
Region: Germany
Calendar: Gregorian
Date/Time: 24-Hour Format
Time Zone: Set Automatically (Chicago)
My location: Austin, Texas
Local currency in Breadwallet: USD

After I changed my region from Germany to United States, the next attempt was successful. So I suspect that item was the offending item. The transaction was to send bitcoin by selecting an amount denominated in US dollars.

**Comment by voisine** [comment]
Thanks for the report. I will see if I can reproduce this. If you would, can you try to set it back to germany and see if the problem reoccurs, maybe with a small $0.01 transaction?

**Comment by voisine** [comment]
Also, do you remember the was the error message when it failed? I want to rule out the possibility that it was a network connection issue that happened to resolve itself while you were changing settings.

**Comment by victorengel** [comment]
I don't remember the error. It was something generic like the transaction
failed. It did behave rather like network congestion, but everything else
requiring network activity worked just fine, including other internet
connectivity and other bitcoin queries. I also upgraded the app during the
interim. I'll let you know the next time I try a transaction.

**Comment by victorengel** [comment]
Another attempt was successful, using my previous settings, so this very
well could have been a connectivity issue.

**Comment by victorengel** [comment]
Cannot reproduce, so am closing issue.

**Comment by voisine** [comment]
Thanks @victorengel, there were also a fair number of improvements around handling connection issues in the most recent update as well, so I suspect it may be fixed anyway. Please reopen if you observe it again.

**Comment by victorengel** [comment]
Well, I encountered the problem both before and after upgrading to the new version of the app, for what it's worth. It did seem to take longer than normal to scan the block chain. That would seem to confirm a connection issue. After upgrade, I don't have enough experience to note how fast it was compared to normal. The progress indicator moved forward and backward a few times before it really kicked in. Not sure what, if anything, that indicates.

**Comment by voisine** [comment]
I've seen that once or twice too. I believe it happens if the wallet connects to a node that isn't fully synced itself, then when it connects to a second node, it switches to that one, and the progress bar moves backward because it's further behind than it first thought.
