### ISSUE TITLE
no iPad specifiy layout

### ISSUE THREAD

**Issue by Thumpxr** [voisine/breadwallet#162]
Hello :)
I tried this app on my iPad and noticed i get those "1X" and "2X" buttons in the bottom right of my display, which shows that the app has no iPad layout.

Can you do it when you have some spare time?

**Comment by voisine** [comment]
Thanks @Thumpxr, this one was also discussed in #115. Right now iPad downloads are quite small compared to iPhone, but I would like to do a version more focused for merchants and point-of-sale
