### ISSUE TITLE
Blank QR code on standard receive page

### ISSUE THREAD

**Issue by JonnyPower** [voisine/breadwallet#164]
On the standard receive page I have a blank QR code for my address.

![](http://i.imgur.com/vZnicqc.png)

The QR code displays fine for the payment protocol request amount window, but not on the main receive panel.

Issue is worked around by force closing and opening the app.

**Comment by voisine** [comment]
Thanks for the report. This is different than a similar looking issue with an older version since you do get a receive address. I'll see if I can add some extra error checking around the qr.

**Comment by voisine** [comment]
quick question, do you remember if the address was correct or if it was something like 1WWWWWW.... ?

**Comment by JonnyPower** [comment]
I'm certain the address was correct, it is hard to replicate the issue though - I haven't seen it since
