### ISSUE TITLE
increase fee to trigger child-pays-for-parent when spending unconfirmed inputs

### ISSUE THREAD

**Issue by voisine** [voisine/breadwallet#165]
We had a new user test out breadwallet by sending 10,000bits to blockchain.info, then send it back with no fee (hey it's just a quid, who cares, right?)

Then they spent their full wallet balance of 17btc, including the 10,000bits. So now they have a few thousand pounds sterling stuck in limbo.

some pools like eligius have instituted child-pays-for-parent, so when spending unconfirmed inputs the wallet should include a fee to cover all unconfirmed input transactions in addition to the current transaction, according to eligius pool selection rules since that's the only pool we know of that implements child-pays-for-parent. According to http://eligius.st/~gateway/faq/following-applies-transactions-being-processed-our-blocks they require 40.96bits per 512bytes of tx size.

**Comment by voisine** [comment]
This still won't catch a long chain of unconfirmed tx since the inputs of the inputs won't be matched by the bloom filter, but it will be a significant improvement for they typical case.

**Comment by voisine** [comment]
@luke-jr is the eligius faq that mentions 40.96bits per 512bytes up to date? http://eligius.st/~gateway/faq/transaction-processing mentions a pending policy change which I assume includes changes to expected fees.

**Comment by luke-jr** [comment]
Yes, that should be up to date. The pending policy change only affects fee rate for non-standard transactions - standard transactions will remain at 0.1 TBC/512 B

**Comment by voisine** [comment]
@luke-jr also pointed out that we need to make sure the unconfirmed inputs make it into the miner's mempool. breadwallet can publish any unconfirmed inputs along with the spend to check if other peers relay or reject them. If not, it will get removed from the wallet so the user can't try to spend it.
