### ISSUE TITLE
Full balance only visible after unlock

### ISSUE THREAD

**Issue by Onefox** [voisine/breadwallet#169]
At the moment i need to unlock my wallet to see how much is in it.
I would like to not need to enter my pin for that information.

Overall i can go in to the transaction list and sum all transactions to get the balance without the pin but its far from user friendly.

If the name should be on top i would suggest a row on top of the transaction list where i can view the balance in Bitcoin and my Currency.

**Comment by voisine** [comment]
This was a conscious design choice to protect your privacy and allow you to receive funds without exposing your balance.

The history only shows your most recent 5 transactions without unlocking, so you can quickly check the status of recents, however that's been changed to only show tx with fewer than 6 confirmations for the next update.

**Comment by Onefox** [comment]
Ah okey i never had more than 5 transactions.
Do i have somewhere all transactions ?

**Comment by voisine** [comment]
Yes, if you unlock.
