### ISSUE TITLE
verify created scripts with libbitcoinconsensus

### ISSUE THREAD

**Issue by jonasschnelli** [voisine/breadwallet#171]
Maybe it would be good to use libbitcoinconsensus for consensus-critical code.
Currently it's only possible to verify a script.
`EXPORT_SYMBOL int bitcoinconsensus_verify_script(...`

**Comment by voisine** [comment]
Actually SPV wallets aren't consensus critical in the way mining nodes are. We don't independently verify transactions the way they do, only block headers and proof-of-work. SPV accepts the network consensus and verifies that the miners have spent the most resources on the chain that includes your trnasactions.

**Comment by jonasschnelli** [comment]
@voisine my idea was more to start using the libbitcoinconsensus to ensure that breadwallet created signatures are valid. Maybe for now this looks after a overdose of code.

**Comment by voisine** [comment]
@jonasschnelli creating standard signatures for standard transactions is actually not too difficult. The hard part, and what libbitcoinconsensus is for, is making sure that different full node implementations handle all possible non-standard edge cases in exactly the same way. That part is hard, but thankfully breadwallet doesn't have to do that.
