### ISSUE TITLE
Problem about transfer to breadwallet. (Urgent for me)

### ISSUE THREAD

**Issue by Jogwonjae** [voisine/breadwallet#174]
Hi, Aaron Voisine

My name is Gwonjae Jo (jogwonjae@naver.com)

I sent the email (vosine@gmail.com) including same contents and addtional breadwallet address information and transaction number which have corresponding problem to your email. In case that you can't read my email sent, I ask about same thing here.

I'm usual user of breadwallet. Recently, I have tried to transfer bitcoin to breadwallet installed in my iPhone. In other bitcoin site, I transfered much bitcoin included that bitcoin site into the breadwallet.
But the approvement of transfer into this breadwallet address had taked about 2 days by the administrator of this site. Meanwhile, my address of breadwallet has changed! how? The transfer has done after the address has changed. Of course the transfer to breadwallet is successful. I don't certify transaction about it. I think the reason that breawallet dosen't certify this transaction is that the transfer is completed to the previous address.
I've thought maybe transaction confirmation should take so long. But when I do a test that I tried to transfer some bitcoin into new address (seen in breadwallet at that time), receive confirmation of breadwallet arrised immediately! Thus, I insist that the transaction that bitcoin is transfered into the old address should be confirmed.

What can I do for that?
Is the previous address effective?
When do I certify the transaction about it?

Sincerely I ask you to solve this problem. 
I'm look forward to receiving your quickly response during I'm feeling a anxiety.
To see additional information about address and transaction number, pleas check the email I sent to you. 

Thanks for your time.

**Comment by voisine** [comment]
Hello @Jogwonjae, I received your email. The transaction id you sent is confirmed. Is the problem that the wallet is not showing that it is confirmed? If so, you can try to "rescan blockchain".

Your address will change each time you receive funds, but old addresses always work. This is because bitcoin addresses should not be reused. https://en.bitcoin.it/wiki/Address_reuse

**Comment by Jogwonjae** [comment]
I don't certify balance about this transaction (141749019139c22936313c8c60a894506f4876906d627f7ae496e92ea77a62ef) although transfer is successful. I haven't reuse address. Just, I only use this address (1HKNaFEL3y6Tt5HSR8bFN2vkWaajGKsmCr)  one time at this transaction. Why did address changed automatically before some transaction arrises? I certainly transfered my unused address of breadwallet. 

I still have not confirmed the ballence of this transaction although I try to click rescan blockchain several times. It's serious problem



2015. 3. 19. 01:34 Aaron Voisine <notifications@github.com> 작성:

**Comment by voisine** [comment]
Responding in email

**Comment by voisine** [comment]
We were able to recover the funds.

**Comment by weablow1** [comment]
I received money to my breadwallet now it's gone? I tried to recover and funds are not there. I have sent emails but no reply please help

**Comment by willy00** [comment]
https://prnt.sc/hy1d8e
