### ISSUE TITLE
[security] better fork detecting, PoW based.

### ISSUE THREAD

**Issue by jonasschnelli** [voisine/breadwallet#175]
It's probably not the most important issue but IMO the fork handling should be improved.

Currently if a preforged block with higher hight comes in, breadwallet will automatically take this block as a valid fork to reorg to. This could open a attack vector agains breadwallet.
https://github.com/voisine/breadwallet/blob/master/BreadWallet/BRPeerManager.m#L1131

IMO there should be a check if the block on the fork has a higher PoW/ChainWork.
https://github.com/bitcoin/bitcoin/blob/master/src/pow.h

**Comment by voisine** [comment]
We do check proof-of-work for each block, as well as verifying that difficulty targets are correct. This is required for SPV. 

The presumption is that a longer chain following the pow rules necessarily involves more work. I believe this is how the Satoshi client also determines highest pow unless I'm misunderstanding your point. To perforge a block with a higher height than the rest of the chain requires more work than went into the rest of the chain.

**Comment by jonasschnelli** [comment]
Meh. I wasn't aware of the `[BRMerkleBlock isValid]`. My fault.
Just trying to review your software while experimenting with a SPV-mode for bitcoind. :-)
I was stumbling over bitcoinj's reorg handling and (`https://github.com/bitcoinj/bitcoinj/blob/e0870efd61e19b971664aaaea384e9e1cebcc7ae/core/src/main/java/org/bitcoinj/core/AbstractBlockChain.java#L485`) and missed the moreWork check on BW. But as said, its there with the block.valid call.

**Comment by voisine** [comment]
@jonasschnelli thanks for reviewing the code, it's important to have more people looking for issues and its work that doesn't get enough recognition.
