### ISSUE TITLE
PIN_FAIL_COUNT_KEY incremented only after failure (instead of before)

### ISSUE THREAD

**Issue by sile16** [voisine/breadwallet#179]
the failure state should be preserved in the keychain and committed to flash before doing the compare / any other action.  Apple fixed a similar bug in their PIN code recently where a PIN could be tried and the power removed prior to storing the failure.  http://9to5mac.com/2015/03/18/iphone-passcode-hack/

**Comment by voisine** [comment]
Just wanted to comment that I'm not ignoring this one. I'm just going to fix it after this pending update so it has more time for testing before going live.
