### ISSUE TITLE
Passcode doesn't appear

### ISSUE THREAD

**Issue by egit2901** [voisine/breadwallet#180]
Trying to put a transaction through bitpay via a QR code.

I scan the QR code and the "passcode for bread" dialogue box flashes up but there is no way to input my passcode.

I've tried swiping every which way, clicking, double clicking, everything. No keyboard appears for me in input my passcode. All I can do is hit cancel.

I'm using a fully functioning Iphone 5 IOS 7.1.1 (11D201).

I have the most recent version of BreadWallet installed.

Is this a bug?

**Comment by voisine** [comment]
Yes this appears to be a bug only on iOS 7 when using payment protocol. I don't actually have any 4" devices still running iOS 7, so thanks for reporting.
