### ISSUE TITLE
QR code recognition

### ISSUE THREAD

**Issue by sarahsterchele** [voisine/breadwallet#181]
Just a question! When compiling the open source version of the wallet on my device that I cloned from github, a lot of QR codes are not recognized that the breadwallet app that I downloaded from the app store can get.  Any reason for this? Anything I can change in the source code to adjust for this discrepancy?

Thanks!
Sarah

**Comment by voisine** [comment]
Can you post an example of a qr that works in one but not the other? Is your version compiled for testnet or mainnet?

**Comment by sarahsterchele** [comment]
I can send you an example, but is it because it's testnet?  Because I think it is! That may be it?

**Comment by voisine** [comment]
Yes, mainnet addresses are not valid on testnet.
