### ISSUE TITLE
Bitcoin recovery

### ISSUE THREAD

**Issue by wbtc** [voisine/breadwallet#187]
Bitcoin was sent to my bread wallet"s send address.
How do I get it into received? Pleas help
![image](https://cloud.githubusercontent.com/assets/11959691/7164279/0d4e52e8-e354-11e4-86b2-195058762bef.jpg)
![image](https://cloud.githubusercontent.com/assets/11959691/7164280/0d6d7880-e354-11e4-9267-973f6d551b52.jpg)

**Comment by voisine** [comment]
The transaction is confirmed. Did the app "sync" all the way? (blue line at the top will disappear when syncing is complete) Does the receive address still show as 1FkcVDAuUuATmPDb3EpaxaroLdwXW3v3MH ?

**Comment by wbtc** [comment]
The address it was sent to is the address I use to send Bitcoin not receive it. My receiving address is different.   
1GmFhBdktAVuFvWkDzMCbWYvLNm4UFaf31

Is there anything I can do to retrieve the coins? I hope it's quite a bit of money

**Comment by voisine** [comment]
Did you take a screenshot of your recovery phrase before receiving the transaction? If so, do not delete the screenshot, you can use it to recover funds

**Comment by wbtc** [comment]
I do have a picture of the recovery phrase. So now how do I racover the Bitcoin?

**Comment by voisine** [comment]
Settings->start/recover another wallet

Enter the new phrase to wipe the existing wallet, then "recover wallet", and enter the old phrase from the screenshot

**Comment by wbtc** [comment]
Are you sure I'm scared to loose the wallet with my Bitcoin In it.   Can you guarantee this will work

**Comment by voisine** [comment]
Your current wallet is empty, correct? The funds were sent to the wallet associated with the recovery phrase you took a screenshot of.

**Comment by wbtc** [comment]
The wallet has a small amount in it. I can send that to my block chain before I try recover

So what your saying is the bitcoin that was sent to the sending address is sitting in the wallet still and I need to get it out by going through the recovery process?   What if that don't work? Then I won't have the wallet anymore so can you guarantee me that this will work. I'm sorry to be difficult but it's a lot of money were talking about

**Comment by voisine** [comment]
If you have the recovery phrase, you have the wallet. You don't need anything else to recover it.

**Comment by dabura667** [comment]
@wbtc 

Show us a screen shot of where you found the 1Fkc... address.

Did you find the address on the screen with the big QR code on it?
