### ISSUE TITLE
Recovery Phrase disappears on screen lock

### ISSUE THREAD

**Issue by michaelcummings** [voisine/breadwallet#188]
I've run into a bit of an issue.

I just installed BreadWallet and I went to write my recovery phrase down when my screen went dark in the process. I unlocked my screen to finish writing it down and it automatically moved on to the QR code screen and I can no longer delete this wallet and start a new one without knowing this phrase. 

As stated in Issue #113 you should probably remove the whole wallet if I delete an app and select that I want to remove all data. I can no longer safely add money to this wallet because I cannot recover BTC if lost or regenerate a passphrase, so what good does it do to keep the passphrase and pin in the keychain? 

I understand the thought behind wanting to keep that safely on the device to prevent people from losing their BTC because they don't remember their phrase, but without even the option of having this as a setting to delete is means that I cannot even use the app at all with confidence.

**Comment by dabura667** [comment]
You can view your recovery phrase in the settings menu.

1. tap the menu button in the upper left.
2. Scroll down to "settings" and tap it.
3. tap "recovery phrase"
4. input PIN
5. it will show your phrase.

**Comment by voisine** [comment]
@michaelcummings fair point about the screen locking while you're writing it down. It should stay awake until you're done.

you can see your phrase again under settings->recovery phrase

**Comment by michaelcummings** [comment]
:+1: Thank you!

That just freaked me out. I immediately uninstalled it and tried to reinstall and was just asked for the pin...

**Comment by voisine** [comment]
The recovery phrase now doesn't get dismissed when the screen locks during new wallet creation. (still gets dismissed if the screen locks while viewing after wallet creation)
