### ISSUE TITLE
Payment did not received

### ISSUE THREAD

**Issue by cjo008** [voisine/breadwallet#189]
Hi Aaron, 

I sent bitcoins to my breadwallet but have not received it for a day. I tried to delete/reinstall the app but did not really solve the problem. The receving address for bread wallet has changed after the transacdtion so I believe there was a transaction. Do I have to wait longer?

Also, it has been a long journey to find this website to be able to actually say something to you. It was very difficult to contact breadwallet. I think this should be solved as well

Thank you

Thank you

**Comment by voisine** [comment]
Sorry it was difficult to get here. There's a link in the app store for support, next to ratings, but I agree that's not easy to find. We're setting up support ticket system this week.

Can you email support@breadwallet.com and we'll look into your issue?

**Comment by voisine** [comment]
Never got your email. I'm going to close this for now. Feel free to contact us or re-open the issue if you're still having a problem.

**Comment by cjo008** [comment]
I have actually sent an e mail to the address you gave me but I did not get response for 3 days.. Please check.
![untitled](https://cloud.githubusercontent.com/assets/12043710/7329619/1bfc5540-eb1c-11e4-97db-9447a1c2d199.jpg)

**Comment by voisine** [comment]
I am incredibly sorry. We just set it up and I guess notifications weren't working. You should see a response now.
