### ISSUE TITLE
Can't sweep funds from BIP38 wallet

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#194]
Steps to recreate:

1. Go to bitaddress and make paper wallet password protected with "a" using BIP38 checkbox on the paper wallet tab
2. Send 200 bits to the address
3. Wait for at least 1 confirmation
4. Try to sweep the funds using "a" as the password. The dialog asking if you want to send the x amount of bitcoins to your wallet comes up so tap send.
5. Consistently get network time out every time.

Using iPhone 6 on Wifi, version running in Japanese. (v0.5.1 (8) )

**Comment by voisine** [comment]
@dabura667 this is just for wallet sweep transactions? other transactions are working?

**Comment by dabura667** [comment]
Yes, I can send via qr code scan as well as copy from clipboard

**Comment by voisine** [comment]
Wow, turns out chain.com uses big endian tx hashes while blockchain.info uses little endian. Thanks for catching this.
