### ISSUE TITLE
Date/Time information in payment history wrong duing rescan

### ISSUE THREAD

**Issue by tisek** [voisine/breadwallet#195]
When I opened the payment history, while "rescan blockchain" was running, the date/time information for each of the transctions was wrong (shifted a few month). When I closed the payment history and opened it again, the timestamp was less than last time. Looks like the timestamp is relative to end of the blockchain the wallet knows about and when the blockchain in rescanned the reference timestamp moves.

To reproduce this:
- Click rescan blockchain
- Close menu, open menu again, close menu again, open menu again, and so an.
- Each time our view your transaction it shows a date slowly counting down until you reach the current day

**Comment by voisine** [comment]
@tisek I believe this one was fixed as a side effect of commit 3451ef7 which is now in the app store
