### ISSUE TITLE
No keyboard when confirming transactions

### ISSUE THREAD

**Issue by thegus4** [voisine/breadwallet#198]
When I pay, wether I accept or reject fee, I am asked for passcode, without a keyboard, and the only option I have is to cancel. Therefore, I cannot send any payments.

Iphone 4S ios 7.1.2

Thanks!

**Comment by voisine** [comment]
This bug is specific to iOS 7, I think you can get around it by turning off the remove fee option in settings for now. It's fixed for the next update.

**Comment by thegus4** [comment]
Thanks!

**Comment by voisine** [comment]
closing as dupe of #180
