### ISSUE TITLE
Transaction fee too low, transactions not getting confirmed

### ISSUE THREAD

**Issue by DrEntropy** [voisine/breadwallet#199]
I think you need to allow the user to set the transaction fee, I am seeing "Medium Priority" and transaction fee too low warnings on blockchain.info when I spend from breadwallet.  It took 3 blocks before I got a (single) confirmation on a recent transaction.

**Comment by dabura667** [comment]
> transaction fee too low warnings on blockchain.info

This is because blockchain.info hasn't updated their systems since before Core release 0.9.0

> It took 3 blocks before I got a (single) confirmation on a recent transaction.

This would have happened even with 100 BTC fee. I have had 3-4 block waits on my ooooold blockchain.info app that automatically sends 0.0005 BTC fees without asking.

It's really luck of the draw.

**Comment by DrEntropy** [comment]
Ah thanks very much. I will mark it as closed then because on further consideration, allowing the user to set the fee will lead to more problems then they will solve....

**Comment by voisine** [comment]
In version 0.5.1, live on the app store as of a few hours ago, we've also bumped fees up slightly to the minimum used by eligius pool (who's settings are also used by other miners), so that should further improve average confirmation times.
