### ISSUE TITLE
Rescan blockchain shows transaction history

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#200]
1. Make a transaction
2. While the transaction is waiting for confirmation, kill breadwallet and restart it
3. In the transaction history, breadwallet shows you your currently ongoing transaction
4. Tap rescan -> without requiring passcode or touchid, breadwallet now shows you the last 5 transactions

**Comment by voisine** [comment]
Aaah yes, there are edge cases where the confirmation count can be confused during a rescan now that I think about it. I'll have to fix that. Thanks for testing. Email me your iTunes account email address and I'll invite you to the testflight betas as I make them before we release.

**Comment by erikwanberg** [comment]
Erikwanberg@hotmail.com

Yours,
=rik .\\ichael '//anberg

Mailto://ErikWanberg@Hotmail.com
Direct # & VoiceMail 609) 385-4744 

¥ • {_}   @ r €   §••  € X Č € [_ [_€ ]\[ +

***PLEASE HELP US SUPPORT OUR PARTNERS BY CLICKING IN THE LINKS BELOW!!!***

VirWoX (Virtual World Exchange), :  global online currency exchange lets you securely exchange a wide range of currencies at little or no cost. Convert between  BTC, USD, EUR, GBP, CHF, SSL and send to PayPal, BTC wallet, or financial institution if your choice!

https://www.virwox.com?r=dba27

Thanks!

**Comment by chrismarquardt** [comment]
> Email me your iTunes account email address

Your email address is remarkably hard to find (as in: I haven't found it yet :))

**Comment by chrismarquardt** [comment]
chris@chrismarquardt.com should do

**Comment by voisine** [comment]
Hah, it's in all the source code files and the license file... :)

**Comment by rgenito** [comment]
I mean, that's how I found Aaron's email :D
