### ISSUE TITLE
support

### ISSUE THREAD

**Issue by johnlcarter** [voisine/breadwallet#201]
where do users obtain support for the breadwallet app?

**Comment by voisine** [comment]
you can email support@breadwallet.com or visit http://support.breadwallet.com

**Comment by johnlcarter** [comment]
Ive been locked out of my app.. its says my pin is incorrect and type my passphrase and it does nothing. I have funds tied up in this app. please advise.

**Comment by voisine** [comment]
We can help. Please send an email to support@breadwallet.com or open a ticket at http://support.breadwallet.com
