### ISSUE TITLE
Private Key import doesn't require PIN

### ISSUE THREAD

**Issue by jasadams** [voisine/breadwallet#202]
I just imported a private key and noticed that it didn't ask me for the PIN. Not really a security issue but may lead to the situation where a user imports their key before realising they have forgotten their PIN. Just reporting the scenario in case you missed it, you may decide that this way is correct.

**Comment by voisine** [comment]
An excellent point. In theory you can do the same anytime you let someone scan your receive address, but I agree it somehow seems wrong to not require the passcode or touch id to send a transaction using the wallet.
