### ISSUE TITLE
PIN on open

### ISSUE THREAD

**Issue by NearlyMad** [voisine/breadwallet#203]
I would feel a lot more secure if there was a PIN option at startup.

**Comment by NearlyMad** [comment]
I usually deal with my bitcoins in BTC. Could we have the option to display what's in our wallet in BTC too?

**Comment by voisine** [comment]
we wanted to have the user authorize for each payment instead, and this also allows you to recieve funds while the wallet is locked. Bitcoin isn't a banking app, transactions aren't reversible so it requires a higher standard of security.

**Comment by NearlyMad** [comment]
Thank you.


Joseph L. Moore
Staff Engineer
Avocational Raconteur

"Be yourself; everyone else is already taken."
- Oscar Wilde




On Sat, May 16, 2015 at 5:32 PM -0700, "Aaron Voisine" <notifications@github.com> wrote:
we wanted to have the user authorize for each payment instead, and this also allows you to recieve funds while the wallet is locked. Bitcoin isn't a banking app, transactions aren't reversible so it requires a higher standard of security.



---

**Comment by voisine** [comment]
Also see #29 for discussion of btc vs bits

**Comment by NearlyMad** [comment]
Thank you.


Joseph L. Moore
Staff Engineer
Avocational Raconteur

"Be yourself; everyone else is already taken."
- Oscar Wilde




On Sat, May 16, 2015 at 5:35 PM -0700, "Aaron Voisine" <notifications@github.com> wrote:
Also see #29 for discussion of btc vs bits

---
