### ISSUE TITLE
Bitcoin dollar value/conversion

### ISSUE THREAD

**Issue by NearlyMad** [voisine/breadwallet#204]
what exchange is used to calumet the dollar value of the bitcoins? Could that be added in the 'About' text?

**Comment by NearlyMad** [comment]
Instead of 'calumet' should be 'calculate,  sorry, I'm new to Github, I couldn't figure out how to edit it.

**Comment by voisine** [comment]
It mentions that the rates are from bitpay.com/rates. Bitpay is the most popular bitcoin merchant services company, so their rates are the most likely to be what you're paying. Their method of calculating it involves multiple exchanges and is explained here: https://bitpay.com/bitcoin-exchange-rates

**Comment by NearlyMad** [comment]
Thank you very much.
