### ISSUE TITLE
Amount is showing when syncing without pin or touchid entered.

### ISSUE THREAD

**Issue by jguchte** [voisine/breadwallet#205]
I noticed that when you open breadwallet and it starts synchronizing the amount of bitcoin is shown without having entered the pin or touchid.
This only happens when it's showing the progress in %.

I attached a screenshot.
![20150520_105640000_ios_edited](https://cloud.githubusercontent.com/assets/12527787/7725109/e5ea935a-fef7-11e4-9552-9826a648735c.png)

**Comment by dabura667** [comment]
I re-synch and re-wipe my wallet a ton, and this happens all the time. locked, but also showing balance (albeit, incorrect balance... probably the balance at the time which the wallet is currently synched to.

**Comment by voisine** [comment]
@jguchte thanks for reporting, that's a genuine bug.

@dabura667 I'm curious what you're doing that you need to re-sync and re-wipe? Are you managing multiple wallets on the same device? That would be pretty inconvenient.

**Comment by dabura667** [comment]
@voisine every time a new build was up on testflight, I was uninstalling and reinstalling constantly to check the opening warning screen etc.

bright side, I memorized my phrase. Lots of syncing tho.

**Comment by voisine** [comment]
@dabura667 ah, product testing :) that's an excellent reason. Appreciate it.

**Comment by jguchte** [comment]
@voisine You're welcome! Awesome app and thanks for fixing this so quick.
