### ISSUE TITLE
localization: German "pay from clipboard" button

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#206]
v 0.5.1 (9)

Can't see the German localization for "pay address from clipboard" button.

In German it would be any of these (all quite long unfortunately, some translated a bit more freely than others, the further down the more creative..):
 
 "An Adresse aus Zwischenablage bezahlen"
 "An Adresse aus Zwischenablage schicken"
 "Adresse aus Zwischenablage verwenden"
 "Adresse aus Zwischenablage bezahlen"

**Comment by voisine** [comment]
What do you mean by "can't see"? The text is too small?

I like creative. Short is good, people are more likely to read it, but obviously not if "creative" is a euphemism for "confusing" or "wrong".

**Comment by chrismarquardt** [comment]
No, I see the original English text.

**Comment by chrismarquardt** [comment]
I'd personally use the third one.

**Comment by voisine** [comment]
You see the english text in the app store version? When I switch my phone to german it show up as "Zahlung an Adresse aus Zwischenspeicher"

**Comment by voisine** [comment]
Also, you can go to https://crowdin.com/project/breadwallet to suggest or vote for translations.

**Comment by chrismarquardt** [comment]
Did the Testflight version overwrite the appstore version? Don't really remember what the app store version said. Only started to look closely after you asked for it with the beta ;)

**Comment by voisine** [comment]
The App Store version is build (11), and the current testflight is 0.5.2 (1)

**Comment by chrismarquardt** [comment]
Interesting, the Testflight invitation mail I received (40 minutes ago) lists v 0.5.1 (9)

**Comment by voisine** [comment]
Looks like "invites" are not just email notifications like I thought, they actually give you access to the build.

**Comment by chrismarquardt** [comment]
Better now, Testflight just notified me of 0.5.2 (1). Thanks. I'll verify the other ones I submitted and close if necessary.
