### ISSUE TITLE
localization: German settings menu

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#207]
In the settings menu the German string for "local currency" is lower case wheres all others are upper case. Make it consistent, e.g. "Lokale Währung"

**Comment by chrismarquardt** [comment]
Still the case in 1.5.2 (1)

Couldn't find this label on crowdin.com

**Comment by voisine** [comment]
I like lowercasing everything, but I guess in German they capitalize every noun, not just sentences, so we can't really do that.

**Comment by voisine** [comment]
https://crowdin.com/translate/breadwallet/9/en-de

**Comment by voisine** [comment]
https://crowdin.com/translate/breadwallet/9/en-de#724

**Comment by chrismarquardt** [comment]
Thanks, had missed that. I know you are a lower-case man :) Which I can understand to a certain extent, albeit from a pure visual design point of view. I believe consistency throughout the app within a language should be the higher goal.

**Comment by voisine** [comment]
yes, it's purely for visual aesthetics, and playfully taking artistic license with correctness, but I get the felling doing things CORRECTLY is more important to the germans.

**Comment by chrismarquardt** [comment]
Ha. If you knew me, you'd understand that I'm probably one of the least
German Germans you've ever met. I don't do correct for correctness' sake.
Ever. What I do right now serves a purpose: mainstream adoption of
breadwallet. I have my own products in several markets, including the US
and the German one. Please trust me if I say that I know the Germans (and
what makes them tick) pretty well.
