### ISSUE TITLE
localization: German "import private key" has inconsistent capitalization

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#208]
Inconsistent captalization for the menu entries under the transaction list. Both should start upper case for consistency reasons, e.g. "Privaten Schlüssel importieren"

**Comment by chrismarquardt** [comment]
Added a suggestion and a comment to crowdin.com

**Comment by dabura667** [comment]
breadwallet style guide states to use all lower case unless absolutely necessary.

Maybe this is why.

**Comment by voisine** [comment]
German is a special case since nouns are capitalized. It should either be all lowercase, or using proper capitalization, but not mixed in the same context.
