### ISSUE TITLE
localization: German help bubble for QR code using wrong form

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#209]
There's a formal and informal way to address people in German. All help bubbles use the formal form, but the current German translation for the QR code uses the informal form.

Here's what I'd change it to: "Wenn Ihnen jemand Bitcoin schicken möchte, lassen Sie sie diesen QR-Code scannen, in welchem ihre Bitcoin-Adresse enthalten ist. Bitcoins werden auf diese Weise an diese Wallet geschickt."

**Comment by chrismarquardt** [comment]
Added something to crowdin.com

**Comment by voisine** [comment]
On crowdin it mentions we prefer simple and informal language to make the app more friendly and personal.
