### ISSUE TITLE
Discussion about app persona

### ISSUE THREAD

**Issue by chrismarquardt** [voisine/breadwallet#210]
Aaron, this is my answer to your question on crowdin.com: "Do other apps like twitter use the informal address to be more playful and personal?"

I am German and I've been living in Germany for most of my 45 years, I've made apps, I've been in charge of usability, I18N and L10N in one of my previous careers, and I deal with language every day, in writing and in speaking. So I believe I have something to say here.

For me it comes down to two things: consistency and app persona.

*Formal vs. Informal*

Speaking in very broad strokes, the two forms are somewhat age-related and mostly have to do with the perception of authority. Most Germans wouldn't walk up to a 40-year-old stranger and address them informally. Doing so would be perceived by some as a minor act of rebellion.

Personally, in everyday life I absolutely prefer to be addressed in the informal way, but apps that do the same thing sometimes feel a bit like they're trying too hard to be playful and personal.

But that's my personal preference, I'm by no means a typical German.

*Onliners vs. Offliners*

There are of course many shades here, but if I were again to paint in extremely broad strokes and really over-generalize, in the context of Bitcoin, I'd put Germans into two camps: onliners and offliners. The onliners are curious of the things to come and have stopped reading their news off of dead trees, while the offliners perceive the internet to be a bit of a threat and they struggle to keep up with what they perceive being fast change. Many of them also don't really understand the net, which doesn't help. In Germany I can see this going through all age groups, but my strong gut feeling tells me that it again at least partially correlates with age.

I also believe the offliners are the vast vast majority, e.g. what we call mainstream.

*Formal speech in apps*  

I think most apps try to pussyfoot around the issue by avoiding to directly address the user. Indirect speech seems to be the norm. This would be the way to go to avoid the entire discussion. Unless you want to make a point. Of course there are a few areas where it would be hard to be indirect. Example: "WRITE DOWN YOUR RECOVERY PHRASE" is more powerful than "THE RECOVERY PHRASE MUST BE WRITTEN DOWN"

*Consistency*

I think we can agree that it's either one or the other. Mixing formal and informal within the app is a horrible idea.

*Decision*

In the end, the decision is yours.

As it is right now, the German crowdin translations for breadwallet are predominantly formal. 

I don't believe that being addressed by an app in one way or the other will seriously influence someone's choice of buying or using it, but it might subconsciously influence the users' perception of its authority and that might be important when it comes to trust. After all, you expect people who have never heard of open source to trust their money to breadwallet.

My suggestion, both in terms of perception and in terms of workload would be to leave it at formal. I'd be much more concerned with some of the unwieldy long German wordings that have the potential to make breadwallet's layout look uglier than it should. And formal/informal won't make any real difference when it comes to that.

**Comment by voisine** [comment]
You know the market better than I do, and respect your opinion. My gut tells me that young people are always the ones who adopt new technology first, and older people will follow them just like with Facebook and twitter. Those platforms clearly targeted college age kids. I think bitcoin, and breadwallet in particular will be successful with that market segment first and we should tailor the experience to appeal to them. So whatever you think younger people will be more delighted, comfortable and excited about is what we should go with.

**Comment by chrismarquardt** [comment]
Sorry for the late answer, I was traveling for the last 2 weeks. I agree,
younger audience is the most likely to engage. Also, if older ones engage,
chances are they're young in their thinking ;)

**Comment by voisine** [comment]
Martin Schwaller made some updates to the german translation now in github.
