### ISSUE TITLE
default wallet in iOS

### ISSUE THREAD

**Issue by bamos01** [voisine/breadwallet#214]
I installed Circle's app to try it out but wanted to go back to breadwallet as my default on my iphone, but even after deleting and reinstalling breadwallet several times, my iphone still goes to Circle's app as the default bitcoin wallet for ios (e.g. when you click on a bitcoin url).  Is there something in the code that you can do that makes breadwallet the default app after install or re-install?  thanks

**Comment by voisine** [comment]
Unfortunately this is a limitation of iOS. According to apple, when two apps both register to handle the same url scheme, the one that is launched to handle it is "undefined". Thankfully at least it does seem to consistently choose the same app each time, whichever that one happens to be. The only solution I've found is to uninstall other bitcoin wallet apps until breadwallet launches.

**Comment by bamos01** [comment]
Thanks for reply - annoying iOS does not provide option user can select.

**Comment by willnwhite** [comment]
We can keep an eye on this here: https://developer.apple.com/library/ios/documentation/iPhone/Conceptual/iPhoneOSProgrammingGuide/Inter-AppCommunication/Inter-AppCommunication.html#//apple_ref/doc/uid/TP40007072-CH6-SW10
