### ISSUE TITLE
Breadwallet received Transfer with same Target-ID - 2nd not showing up

### ISSUE THREAD

**Issue by tjaeger** [voisine/breadwallet#215]
From a Bitcoint Account i transferred BTC to Breadwallet using the Breadwallet-Address.
Worked ok. Made a second Transfer and accidentally used the same (from before) Address.
That (2nd) Transfer doesn't show up !

Theoretically the 2nd Transfer also should go there as the Address can't become invalid really and should go to the same resource. Reload Blockchain didn't help.
Any idea ?

**Comment by dabura667** [comment]
What wallet did you send FROM? Depending on the software, it might have done something weird.

Are both transactions showing up in the sending software?

**Comment by tjaeger** [comment]
I sent it from an online Account (bitcoin.de). There i see both Transactions being sent, with same RCPT-Address.

**Comment by dabura667** [comment]
What are the transaction IDs for both of the transactions?

If you are not comfortable posting them, can you check both of them on the following sites:

https://blockchain.info/
https://btc.blockr.io/
https://insight.bitpay.com/

Tell me if you can see both transactions on all three of these sites?

If you think "what is a transaction ID?" it is a 64 character hexadecimal number. Looks like this:
`05fbf1115af5ab7b21c0bf003fdc9c4c5aea6cb23fba06002a328214d7d752fb`

This could also be a problem at bitcoin.de... they may be having internal problems that are delaying the sending of actual bitcoin transaction. (So their system might say "sent" but they actually didn't send...)

If the site bitcoin.de gives you transaction ID for both of the 2 transactions, AND you can find them on those 3 sites... THEN maybe breadwallet is the problem.

**Comment by tjaeger** [comment]
Thanks!
strangely enough that "double" Transaction took very long now (like 8hrs) - maybe a hiccup in the sending Bank bcs of the overlap Address - i don't know. It finally showed up in the wallet.
So very likely nothing to do with Breadwallet. THANKS FOR SUPPORTING THAT QUICK !!
Great work !
cheers
