### ISSUE TITLE
Recovery phrase usable on other wallets?

### ISSUE THREAD

**Issue by MrSkinny** [voisine/breadwallet#216]
Sorry if there's an obvious answer for this somewhere but I couldn't find it when searching. I was wondering if the seed phrase you use for bread wallet can be used with any desktop client that supports HD wallets, for example, Electrum or Multibit?

**Comment by dabura667** [comment]
Electrum - no. They do not support BIP39 with the exception of Trezor wallet recovery.

Multibit HD - Yes. Choose BIP32 style

![default](https://cloud.githubusercontent.com/assets/6586275/8022383/e199da12-0d08-11e5-849d-0895d783897b.PNG)

**Comment by voisine** [comment]
It can be used in any wallet that uses bip39 and the default bip32 wallet structure. Many other wallets don't, but I believe hive and recent versions of schlidbachs wallet do. We recommend strongly against sharing your recovery phrase between different types of devices and wallet software however, as they are not built to the same security standards.

**Comment by MrSkinny** [comment]
Thanks for the quick reply. General plan isn't to use the phrase between wallets but I wanted to be sure that if Breadwallet ever went away, there are options!  (Hey, Apple banned bitcoin wallets once...)
