### ISSUE TITLE
Breadwallet will not stop syncing?

### ISSUE THREAD

**Issue by nellalea** [voisine/breadwallet#217]
When opening my Breadwallet app it continuously sycs itself, but never increases from 0.0% completed. App is up to date, with no updates waiting to be downloaded. Is any one else experiencing this issue? Any suggestions?

**Comment by voisine** [comment]
Sorry you're experiencing problems. Does the issue persist after killing and restarting the app?

**Comment by nellalea** [comment]
It does indeed. I restarted my phone as well and the same thing happened as soon as I started the app. I'm running out of ideas haha.

**Comment by voisine** [comment]
You can delete and reinstall the app if you need access to funds quickly, (your wallet will not get deleted) or alternately we can give you a debug version of the app with extra logging so we can see what's going on if you're comfortable with that

**Comment by voisine** [comment]
closing this one, feel free to re-open if you're still having problems
