### ISSUE TITLE
Existential threat to Bitcoin (and thus Breadwallet)

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#218]
Gavin Andresen: "A lot of people are pushing me to be more of a dictator (like Mike) ... that may be what has to happen with the block size. I may just have to throw my weight around and say this is what it's going to be. If you don't like it, find another project."

https://www.reddit.com/r/Bitcoin/comments/393fym/gavin_andresen_a_lot_of_people_are_pushing_me_to/

What response can be made against the unbridled arrogance, disrespect, and disregard for consensus (with Jeff Garzik, Greg Maxwell, Adam Back, 'Blue Matt', Luke Jr, Peter Todd, and many other core members) that Gavin Andresen and Mike Hearn are displaying? I urge anyone with 'connections' to do something to make it known to Gavin that his approach is unacceptable, extremely dangerous, and misguided. I can't even believe that Gavin is saying what he is saying. If I didn't know better, I'd think he has become a mole in the ecosystem who is intentionally trying to subvert and fracture the community with provocative language and actions. This is wrong on so many levels.

**Comment by voisine** [comment]
Pick your existential threat I guess. The extreme bias toward the status-quo when external factors like user adoption are changing rapidly is even more dangerous. If things need to change in order for bitcoin to survive, then a capable leader who can also just as easily be "fired" is how those things will get done, but without the problems associated with dictatorship. Relying on consensus only works if nothing of more than trivial consequence ever needs to be done.

**Comment by eragmus** [comment]
I thought the history of Bitcoin's development has been, by and large, via consensus. If so, what makes this time different? What makes Gavin and Mike's view more legit than the view of Garzik and every other core member? All I am arguing is that Gavin is behaving very irresponsibly, as there is no crisis situation (we are not in the middle of a bubble in: exchange rate, user adoption, or transaction growth) to justify this kind of talk.

**Comment by dabura667** [comment]
Irrelevant to breadwallet development. This is an issue board. Not a soapbox.

To your point:

People flaming up the issue look like the social diversionary tactics outlined in the Snowden reports to me.

Consensus has failed, and we've fallen into the playing on emotions tactics of politics.

The only person actually doing research and listening to other's opinions is Gavin. And his recent comments are merely to try and push people to come to consensus.
