### ISSUE TITLE
Using a screenshot of a QR code

### ISSUE THREAD

**Issue by bslayton** [voisine/breadwallet#220]
Has anyone thought about the ability to use a screenshot of a qr code for payment? I commonly buy gift cards via Gyft and for some reason I can't copy the wallet address from the gyft/bitpay page. I think it's a bug on there end. However, this isn't the only time I've ran into needing this feature. The quick fix that I normally do is send the screenshot to my wife's phone and then "scan" it in breadwallet.

Is something you guys are interested in? I don't know any Obj-C or I'd love to help out. If you know of a way I could help, let me know.

**Comment by voisine** [comment]
excellent idea :)

36b11db

**Comment by bslayton** [comment]
Bingo! :+1:

Neat implementation there. It doesn't look like this has made its way to the app store yet. Glad to know you guys beat me to it. Forgive me for creating an issue about it. I searched through the issues and didn't find anything regarding this functionality.

**Comment by voisine** [comment]
No worries, thanks for your interest in the project. Here's the current code. I took the r= hack out and made BRPaymentRequest handle BIP73 url's directly instead: https://github.com/voisine/breadwallet/blob/master/BreadWallet/BRSendViewController.m#L779

**Comment by bslayton** [comment]
How exactly is this suppose to work? I've tried copying a qr code to my clipboard and bread shows me no address to send to. :(

**Comment by voisine** [comment]
Are you using the App Store version or building from the latest source? It's not in the current App Store build.
