### ISSUE TITLE
Authentication of payment unlocks balance showing.

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#222]
Making sure that the balance doesn't get unlocked directly after authorizing payment to be sent.

Current behavior is sporadic.

You mentioned it is most likely a race condition between when the balance updates itself and something else.

**Comment by voisine** [comment]
Greeting meeting you the other night, I did not make the connection between
you and the dabura667 github name. :)

On Friday, July 3, 2015, dabura667 <notifications@github.com> wrote:

> Making sure that the balance doesn't get unlocked directly after
> authorizing payment to be sent.
>
> Current behavior is sporadic.
>
> You mentioned it is most likely a race condition between when the balance
> updates itself and something else.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voisine/breadwallet/issues/222>.
>


-- 

Aaron Voisine
co-founder and CEO
breadwallet.com
