### ISSUE TITLE
Barcodes and BTC

### ISSUE THREAD

**Issue by mgbtcfv** [voisine/breadwallet#227]
Is there a way to use barcodes for BTC payments at retail stores?
Every store usually has a barcode reader. Can software be written to convert breadwallet balance to a barcode on a mobile device like iPhone?
For example, in Fold app (https://foldapp.com/) we add BTC to a virtual Starbucks gift card and then we just scan the bar code at the register. Can something like this be implemented in breadwallet?

**Comment by voisine** [comment]
Unfortunately there is too much information to represent even in a very large compact QR. It would take multiple scans in both directions (scanning and displaying qr codes) which I don't think is an acceptable user experience in a retail environment. I think bluetooth and adhoc wifi are the right tools to solve the problem.
