### ISSUE TITLE
Finger ID

### ISSUE THREAD

**Issue by athletedo** [voisine/breadwallet#228]
Hi so I've been accessing my bread wallet via finger ID for a while and therefore I had forgotten my passcode as I wasn't using it as frequently and suddenly my bread wallet asks for my passcode instead of my finger so now I'm stuck as I do not remember my passcode and have lost my paper with the recovery phrase. Could I get some help please I've got quite a few bitcoins in my wallet.

**Comment by dabura667** [comment]
In options under "Touch ID sendable amount" it says by default 100,000 bits.

So just send 100,000 bits at a time outside breadwallet until all your money is out of breadwallet.

Otherwise, there is no way.

**Comment by athletedo** [comment]
When I go onto that it says 
Passcode for ''bread''
2 attempts remaining 
So is there no way I can get to my bits because I've literally just sent some coins to that wallet

**Comment by voisine** [comment]
@dabura667 the default is 1,000,000 bits, but it's cumulative, not per tx. You can only send up to that amount total without entering your passcode. That way a thief who steals your phone and constructs a fake finger can only steal up to the touch id limit, not empty the wallet.

You need either the device and passcode, or the recovery phrase to access the funds.
