### ISSUE TITLE
Sending bitcoin URI to bread

### ISSUE THREAD

**Issue by bslayton** [voisine/breadwallet#229]
I know bread accept the bitcoin: uri. However, is there a way to send a bitcoin uri transaction request to bread, using breads own uri? Maybe something like... bread://x-callback-url/bitcoin-uri?uri=bitcoin%3A1448PbGuf75o7U2oLq2AfH2HHkCnBUEL5X%3Famount%3D1%26message%3Ddonation

The reason for this, is so you can submit bitcoin uri's to bread when you have other Bitcoin wallets on iOS that have been given priority of the bitcoin: uri scheme.

**Comment by voisine** [comment]
I was just discussing doing this with Chris Moss (Sarutobi) over a beer the other day for something new he's working on. Good idea.

**Comment by traidman** [comment]
You on wifi?  I'm still at Narita.  Delayed
