### ISSUE TITLE
Japanese phrase fixes

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#231]
i noticed during your presentation on Sunday:

1. Need to separate words with ideographic space
2. Need to ensure words don't split between lines.

I saw ascii spaces and one word was half on line 1 and half on line 2.

I understand it's a WIP build, but those 2 issues must be fixed.

**Comment by voisine** [comment]
I'm really surprised that a UITextView would wrap in the middle of a word. 

Also we normalize the phrase before displaying it, but I guess we can't do that for ideographic languages.

**Comment by dabura667** [comment]
1. Japanese text recognizes every character as a "breaking" character. (ie "it's ok to break after me") in ASCII only `" -;:?!"` are breakable. (I think)
2. When showing the user the phrase, normalizing ideographic to ASCII will show them words all scrunched together and it's hard to read. Should definitely show the phrase split by ideographic space / or any other way that will show the user where one word ends and another begins. (It's a quirk about Japanese, as words are very fluid and viewing A and B too closely might not be seen as AB but might be seen as C if you understand what I am saying)

For 1, I wonder if there is a way to tell the last character on a displayed line? if so, I might test the first line's last character to see if it is a space, and if not, find the last space in the line and insert a line break after it. repeat with each line.

Or counting characters could be another viable option (count how many characters fit in a line, and count each word until one word before it runs over that limit, then add in a line break etc)... but that seems like it would vary from device to device...

**Comment by dabura667** [comment]
counting characters could also work if you just count for the smallest display possible... (and hope that iDevices don't ever get a thinner screen)

**Comment by RenSylvain** [comment]
@voisine Hi there, I am interested in sharing a feature request with you. Where is the appropriate place to submit that? I've been using breadwallet for a while and I love it, but there's something that I'd love to see included.

**Comment by voisine** [comment]
@dabura667 that's really helpful, I was thinking to look if there's a no-break Unicode value I could put between characters within words, as that would be simplest, but there are also (clunky) ways to check text width and insert newlines.

@RenSylvain submitting a new issue here is the right place. Also don't forget to search past open and closed issues to see if it's already been discussed. Feel free to comment on another issue to indicate your interest if someone else already suggested it.
