### ISSUE TITLE
Method for recurring transactions. Can be coin, websocket, or protocol...but for the love of god, anything.

### ISSUE THREAD

**Issue by RenSylvain** [voisine/breadwallet#235]
Hi Voisine, 

I have absolutely loved using breadwallet and I am very thankful for your work. I've been in the bitcoin space for 3 and a half years and I've been trying to think of the best way to do recurring payments with bitcoin for a while; with the end goal being an extremely effecient crowd funding protocol/method that only bitcoin would enable.

The most recent iteration of that idea is a digitial token that one would get from another person or a website. This digitial token, once in your wallet, would tell the wallet that it should ask you to send some amount of money every month(or week, or whatever). 

Example of user experience: 
1) I go to www.SENS.org 
2) I go to their token page
3) I scan a QR code with breadwallet
4) Breadwallet asks "Are you sure you want to hold the SENS token? You will be asked to send 1$ a month to SENS until you delete it?"
5) You hit ok. and then SENS website sends a token to your wallet.
6) Your wallet now has a token in it. (which you can also share with anybody who you think would be interested).
7) At the end of every month you get a transaction message and enter your passcode/thumb print etc.

Conlusion: recurring payments accomplished, and you can share with people who you know might be interested.

You can probably think of a more technically savvy way to accomplish the same thing, but I wanted to explain the overall concept. Maybe it's a coin from Colored Coins, or Counter Party, maybe it's a protocol extension, maybe it's a websocket, but the user experience is as per above.

With that said, I would be willing to pay you for a 30 minute google hangout to discuss this furthur, or we can just keep messaging on here.

**Comment by voisine** [comment]
Thanks for your interest, @RenSylvain,

Recurring payments are definitely something that would be useful. I'm not sure why you'd want to connect them to a token, that part doesn't follow for me. What makes more sense would be an extension of the BIP70 protocol for a recurring payment request. These could potentially be stored in the wallet, and the user could be prompted to authorize payments ahead of time.

**Comment by RenSylvain** [comment]
This is why I messaged here @voisine, You know way more than I! and if that's your ideal approach to the above user experience, then I am all for it.

How many man hours do you think it would take to write the extension? and, who is capable of writing it? I imagine this is not a trivial thing if it hasn't been done before. (both tough questions I am sure.)

For me I have two choices: Find someone who can do it and pay them, or do it my self.

Just trying to figure out the answer. :)

**Comment by voisine** [comment]
@RenSylvain I think you'd want to write an extension to BIP70. You could discuss with the people at bitpay since they are heavily involved in BIP70 extensions and related BIPs. Once it's speced out and agreed on, then we would consider implementing. It would involve some non-trivial changes to the usage patterns we have today, so it wouldn't happen right away.

**Comment by RenSylvain** [comment]
Hi @voisine , just wanted to say thanks for your response. I have contacted some people at BitPay and I will follow up with them. The discussion can be found here: https://labs.bitpay.com/t/recurring-payments-made-easy-and-shareable-in-person/577
