### ISSUE TITLE
Import BIP38 Private Key is broken

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#239]
On current beta testflight scanning a BIP38 private key with the import privkey feature does nothing.

No prompt for password even.

**Comment by dabura667** [comment]
Still occurs in today's beta build that I downloaded from testflight.

1. Normal private keys
2. BIP38 private keys

both of them do not work. After scanning them, the scanning window disappears and you are placed back on the send screen with no pop ups.

However, like before, scanning an address with import private key will show you the balance of the address.

Please re-open

**Comment by voisine** [comment]
hah! I couldn't reproduce this at all... because I was using scan button on the send screen instead of the one from the tx history screen. :) The previous fix was a different bug.
