### ISSUE TITLE
Suggestion: If the phrase input contains no spaces, inform the user.

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#241]
When performing checks on the recovery phrase:

1. NFKD normalize the user's input
2. Check if the result has any ASCII spaces.

If 2 fails, show a message saying "phrases comprise of at least 12 words, and these words must be separated by a space. Please enter more than one word."

This will help prevent Japanese/Chinese people from accidentally forgetting to put in spaces.

Currently, if you enter a valid phrase minus the spaces, it says ""reallylongstring" is not a valid word" where it should first notice no spaces and tell the user 1 word is not enough.

**Comment by voisine** [comment]
so, I put in some code so when you type in a word from one of the ideographic word lists, it will automatically append an ideographic space afterward. I figure this will solve the issue and speed up phrase entry at the same time. I imagine this issue is even worse for chinese since every word is single character. They probably would not expect to need spaces at all.

**Comment by dabura667** [comment]
hmmm... I'll have to try this out with both Japanese keyboards and see if it works well... it seems like it might cause problems with the way that Japanese keyboards force you to lock in entries with enter...

Also, I am not sure how the Chinese keyboard works (I wish I did)... but this seems like it might cause bugs. (iirc, Chinese traditional has a quirky keyboard where it forces the suggestions panel to show up and you have to hit enter before locking in a symbol... and Simplified Chinese keyboard entry is much different than traditional Chinese keyboard)

I would sleep better knowing someone with experience using the Traditional Chinese and Simplified Chinese iOS keyboards actually runs through inputting some phrases and tries it out...

**Comment by dabura667** [comment]
I just checked and there are 6 keyboards for traditional chinese and 3 keyboards for simplified.

One of them shows english letters until the user hits enter, then they change to chinese. Another one has some sort of phoenetic alphabet-ish set that changes into chinese when the user hits enter.

Hiring a native chinese and a native taiwanese person to run through testing phrases might be a good idea.

**Comment by voisine** [comment]
So the way I have it, it will not append a space until after you input a word contained in the japanese or chinese word lists. (also we only support simplified chinese at the moment)

I will try it out with chinese to see if it the textview contents get updated while you're in the process of selecting a character, which would be problematic, or only after you lock in the symbol.

**Comment by dabura667** [comment]
I just tried Japanese phrase entry through both keyboards in the build u just put out and even if I hit enter to get rid of the suggestion box after each word, there were no spaces automatically inserted for me.

**Comment by voisine** [comment]
It works for me when pasting individual words. However I thought of better way to handle this that should be more robust. Just let the user enter the phrase without spaces and then scan through it afterwards to insert them then.

**Comment by voisine** [comment]
@dabura667 so the new beta build (8) now handles ideographic recovery phrases with no spaces in them. It will scan for recovery phrase words within the phrase and insert spaces after you hit enter. It should also work even with incorrect non-phrase words inserted anywhere in the phrase (start, middle, end, more than one, etc...)

**Comment by dabura667** [comment]
Can't test chinese, as I can't write down the phrases or know how to type them haha

But I checked Japanese, and it seemed to work fine.
