### ISSUE TITLE
UI: Recovery Phrase screen BG turns black

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#242]
Reproduce steps:

1. Enter into the Recovery Phrase input screen.
2. Wait for about a minute.
3. The orange background will slide to the right slowly revealing a black bar that grows bigger in width until it goes back to the left.

**Comment by voisine** [comment]
what device and iOS version? I can't seem to reproduce it, although I do see some problems on the 6+ (background doesn't move)

**Comment by dabura667** [comment]
iPhone 6 iOS 8.4 set to Japanese region, and Japanese language.

The image slides off screen to the point where 1/3 of the left side of the background is black. The it heads back to the left.

The right side of the screen never exposes black.
