### ISSUE TITLE
Today extension QR is unscannable by certain apps.

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#243]
I tested on iPhone 6 and Android Nexus 5:

Android:
Mycelium Nope
Bitcoin Wallet Nope
Copay Nope
GreenAddress Nope
Wallet32 Nope

iPhone:
CoinPocket OK
breadwallet OK
Copay Nope
Mycelium OK
GreenAddress Nope
Hive Nope
Bither Nope
Airbitz Nope
Pheeva Nope

It seems like all the iPhone Nopes are using some sort of Cordova package (I think all of them are Nodejs apps packaged with Cordova)

All Android wallets are out so far.

Maybe it's because traditionally QR has black where in the Today extension it appears as white, and what usually appears as white appears in the Today extension as a transparent dark gray (with hints of whatever color is on your home screen at the time)

Perhaps inverting the black & white of the QR code before feeding it into the Today screen will cause it to be easier to read... (by making the traditionally white parts white and the traditionally black parts be that translucent dark gray)

**Comment by voisine** [comment]
Does this one work better? Try it on an iPhone screen if you can.

![qr](https://cloud.githubusercontent.com/assets/316879/8768346/8188295e-2e31-11e5-8380-94823398f759.png)

**Comment by voisine** [comment]
:) so purdy
![qr_jp](https://cloud.githubusercontent.com/assets/316879/8768504/809020e6-2e37-11e5-823d-435a9b02e227.png)

**Comment by chrismarquardt** [comment]
bitcoin:mjPjgUdPytFJiSBmoZ5Q1zJnnkpVk5TUZX doesn't work because it's not a
valid Bitcoin address.
Aaron Voisine <notifications@github.com> schrieb am Mo., 20. Juli 2015 um
01:59:

**Comment by voisine** [comment]
yeah, it's a testnet address, but if you get that error it means the scanning worked

**Comment by dabura667** [comment]
Looks great. All the Nope wallets on both Android and iPhone scanned it fine, I displayed it on an old iPod Touch screen I had. Then I tried scanning by displaying on my iPhone 6 and all the Android apps worked. (though they gave errors for being an invalid address due to testnet)

But they read it fine.

Once this is merged this issue can be closed

**Comment by voisine** [comment]
fixed with bc451cc
