### ISSUE TITLE
Notification doesn't go away 

### ISSUE THREAD

**Issue by nshopik** [voisine/breadwallet#245]
This is latest beta from today, after I made payment it show me notification (with delay about 20sec) of confirmation but never discard it
![image](https://cloud.githubusercontent.com/assets/4439311/8765815/99d78f4e-2e28-11e5-8de8-dd53060f525d.png)

**Comment by voisine** [comment]
Ah, this is related to switching from NSURLConnection to NSURLSession... now the callback blocks don't execute on the main thread so alerts and popups behave strangely.
