### ISSUE TITLE
Add the option to choose nodes

### ISSUE THREAD

**Issue by pop9119** [voisine/breadwallet#248]
After the July 2015 forks it has been recommended that SPV wallets wait for 30 conformations before a tx is considered valid and safe. I personally have no will to wait approx 5 hours (on average) to know that a tx is safe and can/will not be orphaned/reorged. To my knowledge that has not happen on such a scale, but this is causing some lost trust in the system. (If I posses incorrect info on this, or my wording is wrong i do apologize)

I have personally created nodes that are up-to-date and i would like to be able to choose to directly connect to those and know that my confirmations are good and valid. I understand that you created this wallet to be used by non-techs as well and might not want to add a feature that they would not understand. But, I do believe that this is has become an important issue to look into. I'm interested in hearing your thoughts on this.

**Comment by voisine** [comment]
I don't think we'd ever offer an option for users to choose their own nodes, I can't imagine apple pay offering options like that, and that's what we're competing against.

But breadwallet will at some point start running full nodes to augment the volunteer p2p network. If we've got millions of users, we'll need to do so we don't overwhelm the network. In that case of course we wouldn't want to relay invalid blocks.

**Comment by Onetallnerd** [comment]
You can't sneak the setting without putting it in the gui? I'm having issues relaying some transactions and I'd love to be able to use my own node.
