### ISSUE TITLE
Re: Fee estimation based on network load

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#251]
I'm not sure what logic is being used in breadwallet's new update, but just as a point of information in case it's not known by breadwallet devs and can be learned from, here is a recently developed service that estimates fees based on load:
> http://www.cointape.com

Thanks

**Comment by voisine** [comment]
We've been talking to the blockcypher guys, but will check these guys out as well. Thanks.

**Comment by eragmus** [comment]
Cool!

Some feedback...

After the update to 0.5.2, I sent ~3,600 bits and a 42 bits fee was attached. Size was 225 bytes. This equates to 18.7 satoshis/byte, which cointape says equates to the tx being included in the next 2-18 blocks... that of course is too high a range and 'bad'.

According to cointape, a fee rate of 31-40 satoshis/byte will achieve speed of inclusion in blocks 1-2, a tight narrow range. Being included in the next 1-2 blocks sounds reasonable, right?

So, maybe adjusting breadwallet's fee automatically based on cointape's estimae for inclusion in next 1-2 blocks would be better than the current logic being used. Current logic seems faulty (since it put only a 42 bit fee which is 2-18 blocks, meaning the tx is vulnerable to the effects of the current spam attack ).

**Comment by voisine** [comment]
The current fees are the minimum fee-per-kb needed to get into elegius pool with the smallest typical tx size. I'd like to try to keep a standard fee if possible that works reasonably well during a spam attack, and is also relatively cheap during normal network loads. Obviously this will not be possible if blocks start filling up with normal non-attack transactions and fees rise above the elegius default minimums, but it's preferable until that time. At the moment many pools are attempting to filter the spam attack tx, so I don't know if cointape is doing the same when modeling what pools are doing. How does their numbers compare to blockcypher high/medium/low_fee_per_kb ? https://api.blockcypher.com/v1/btc/main?&jsonace=413

**Comment by eragmus** [comment]
Hi,

I'm not really sure how to answer your question because I don't know how to interpret blockcypher's data (they show a 5 digit number, not sure what this represents exactly).

Cointape has an api too: http://www.cointape.com/api

{ "fastestFee": 40, "halfHourFee": 20, "hourFee": 10 }

fastestFee: The lowest fee (in satoshis per byte) that will currently result in the fastest transaction confirmations (usually 0 to 1 block delay).

halfHourFee: The lowest fee (in satoshis per byte) that will confirm transactions within half an hour (with 90% probability).

hourFee: The lowest fee (in satoshis per byte) that will confirm transactions within an hour (with 90% probability).


This is how Cointape describes their policy...

What does the delay mean?

The delay shown here is the predicted number of blocks the transactions will take to confirm. If a transactions are predicted to have a delay between 1-3 blocks, there is a 90% chance that they will be confirmed within that range (around 10 to 30 minutes).

Transactions with higher fees will often have 0 delay, which means they will likely be confirmed with the next block (usually around 5-15 minutes).

How is the delay predicted?

The predictions are based on blockchain data of the last 3 hours, as well as the current pool of unconfirmed transactions (mempool).

First, a likely future mempool and miner behavior is predicted using Monte Carlo simulation. From the simulations, it can be seen how fast transactions with different fees are likely to be included in the upcoming blocks. 

The predicted delay shown here is chosen to represent a 90% confidence interval.


I don't know if breadwallet's current implementation is better or worse than Cointape's, but hopefully you can evaluate that. Your thoughts?

I understand the reasoning behind ideally wanting a standard default fee that is good in all situations to keep the wallet as independent as possible and not reliant on an outside service, but please also prioritize user satisfaction in terms of adjusting to network conditions promptly.

In this vein, can you please clarify if breadwallet currently will adjust to network conditions? i.e. if and when coinwallet again begins a spam attack that this time creates a 30-day backlog

**Comment by eragmus** [comment]
@voisine 
@dabura667

Hello, sorry to do this only 2 days later, but considering the impending supposedly severe September attack on the Bitcoin network by Coinwallet, and hence the urgency of mitigating it, I want to BUMP my prior post.

Thanks.

**Comment by voisine** [comment]
1) unknown, we'll have to see how it works in practice.

2-4) I'm not so worried about 1-2 blocks, it's a balance of short confirmation times and low/stable/predictable fees. I'm curious why 1-2 blocks seems to be so important for you? Maybe the service or vendor you want to send funds to needs to be lobbied to accept zero-conf tx that have a high confidence rating. People sending funds don't really care about confirmation times, only the person receiving them does. And with breadwallet we allow users to spend unconfirmed, so in practice transactions are instant regardless of confirmation times.

**Comment by eragmus** [comment]
I guess we'll just have to wait and see then how breadwallet handles an increased network load.


re: 1-2 blocks

Your argument makes sense, but mainly only for payments between 2 trusted parties, right? In a user-merchant relationship, the merchant may be trusted, but the user is not. Since the merchant does not have a good reason to trust the user, most merchants today want at least 1 confirmation. e.g. Gyft, which initially accepted zero-conf payments, has been vacillating between accepting zero-conf and requiring 1 confirmation. In a user-user relationship, again, it depends on trust. If it's just between two friends, then sure zero-conf is not a problem. But if it's between strangers, it seems inevitable that people will try to double-spend since zero-conf is quite insecure without relying on 3rd party services like BlockCypher.

1-2 blocks is important to me, due to the above. Double-spending is a problem with zero-conf, and various tools make it easier to accomplish. Services like Coinbase may accept zero-conf, but only because they accept the double-spending and eat that cost in order to provide customers a good experience. Peter Todd has spoken a lot about this, and how zero-conf encourages services to eventually try to make direct deals with miners, which poses a problem longterm and is unsustainable.

So while I understand wanting to keep fees low/stable/predictable as much as possible, I don't think this goal reflects the reality of the market place. Since all merchants don't accept zero conf, as the general feeling is that 1-conf is a minimum for good security (because everyone can't and shouldn't be expected to rely on a TTP (trusted third party) like BlockCypher with what is supposed to be a trustless system (Bitcoin)) , I feel the bar in breadwallet should be set to trying to achieve min 1 confirmation as quickly as possible, i.e. by paying a fee that enters within 1 block ideally or at least within 2 blocks. After the #1 priority of "1 confirmation asap" is achieved, then by all means make #2 priority be keeping the fee as low and stable as possible.

Basically, if you took a poll of bitcoin users, I'm arguing I think the majority will prefer having payments getting 1 confirmation asap and willing to occasionally (during abnormally high network load) pay 10x higher fee if required (2 cents vs. 20 cents, 100 bits vs. 1,000 bits) for that privilege, rather than feeling like they are being "left stranded" waiting say 5 blocks for their 1 confirmation and paying only a modestly higher fee (e.g. 2 cents vs. 5-10 cents, 100 bits vs. 250-500 bits).

Just my opinion though. We can see the results of the experiment if/when Coinwallet delivers their 'massive' spam attack.

**Comment by voisine** [comment]
I guess I just don't see it that way. Even if you pay enough to get into the very next block, you will never achieve near instant transactions without zero-conf. There are lots of applications for near instant transactions, but as soon as you introduce a typical wait time of 5min-20min, there are actually very few use cases where it's acceptable to wait a quarter of an hour, but not one hour. You can't for instance pay a restaurant check, or conduct really any in-person trade if you must wait for 1 block which occur and random intervals. You could very well end up waiting an hour or more if you are unlucky even if you could guarantee getting into the next block.

**Comment by trevorchill** [comment]
I don't think you understand many use cases in which people care about confirmation times. 

Just a couple of examples - for any trading, most exchanges require at least one confirmation, sometimes more. Many people transfer their coin off an exchange when not tradinggn for safekeeping, and back on when movement picks up again. For a lot of gambling sites, the same issue holds. It's a matter of transferring to one' sown account on a service that requires confirmation. And this is a big issue because there have been many successful double spend attacks on zero conf gambling sites that I am personally aware of by talking to the founders. It's absolutely not a hypothetical issue at all. There are quite concerted and successful attackers out there and they have made it exceedingly difficult for some sites to accept zero conf transactions. 

I don't think that one should consider trading on exchanges as a fringe use case either. It is probably much larger in terms of the percentage of bitcoin activity than actual merchant transactions. 

If someone wants to send their bitcoin to an exchange for trading, it's very time sensitive, as you can imagine. For the sites that accept one confirmation, one could be trading within 10-15 minutes or less if they got in the next block. To wait an hour or more is grueling in that circumstance.

**Comment by nshopik** [comment]
> If someone wants to send their bitcoin to an exchange for trading, it's very time sensitive, as you can imagine. For the sites that accept one confirmation, one could be trading within 10-15 minutes or less if they got in the next block. To wait an hour or more is grueling in that circumstance.

Blocks that generated within 30-60 mins aren't that uncommon so you still have to sit and wait until that first confirmation, so you can't really expect that 1-conf will be within 15 mins

**Comment by voisine** [comment]
@trevorchill I hear you. I think you've identified the strongest use case needing fast confirmation, trading. We have to also balance this against low transaction fees. We also have people who receive daily mining pool rewards who have hundreds of inputs when they spend $100 worth of funds. These are the extreme cases and we're going to do our damnedest to make something that "just works" (tm) for everyone without having to understand how bitcoin transactions and fees work under the hood, because requiring that knowledge excludes far more people than are excluded at the margins by a single fee schedule that tries to serve the needs of as many people as possible.

This is another great case for a separate power-user app. I can't justify devoting engineering resources to something like that right now, but I will happily code-review and support it if someone else wants to do it in the mean time.
