### ISSUE TITLE
Latest release 9 (0.5.2) crashes just after launch

### ISSUE THREAD

**Issue by adattudos** [voisine/breadwallet#253]
Hi,

I have updated to latest release and cannot start Breadwallet as it consistently crashes during startup.

bug_type: 109
os_version: iPhone OS 7.1.2 (11D257)
version: 9 (0.5.2)
Hardware Model: iPhone 3.1 (I know it is time to upgrade...)

Exception Type: EXC_BAD_ACCESS (SIGSEGV)
Exception Subtype: KERN_INVALID_ADDRESS at 0x00000000
Triggered by Thread: 0

Thread 0 Crashed:
0 breadwallet
...
39 UIKit
40 breadwallet 0x00092766 0x18000 + 501606
41 libdyld.dylib 0x3b6ecab4 0x3b6eb000 + 6836

Do you get the full crash reports from Apple?
Do you need specific additional details?

Please advise.

**Comment by pinheadmz** [comment]
Same here, iPad 2 running iOS 7.1.1

**Comment by voisine** [comment]
Thanks for reporting. We do get crash logs from apple, but for whatever reason they seem to take a long time to get reported. I tested on a iPhone4 with 7.1.2 and didn't hit any issues, but I will see if I can duplicate.

**Comment by adattudos** [comment]
Thanks for the update. I have tested it again and now it works.
I am not sure what has changed other than maybe status of the bitcoin network.

Can you symbolicate the following or do you need the full crash log to do that?

Thread 0 Crashed:
0 breadwallet  0x0008db20 0x18000 + 482080
1 breadwallet  0x00085c4a 0x18000 + 449610
2 UIKit  0x332666da 0x33241000 +153306
...

Binary Images:
0x18000 - 0xa3fff breadwallet armv7
...
0x33241000 -0x339b4fff UIKit armv7
...

**Comment by voisine** [comment]
Finally figures out what's going on here. On iOS 7, the app will crash if you have an image copied to the clipboard. It tries to scan the image for a QR using an iOS 8 only core image method.

**Comment by pinheadmz** [comment]
Wow! That's about as tweaky as bugs get - amazing you found that. ALSO! That's cool that the app scans images in the clipboard for Bitcoin QR codes. I was thinking that would be a nice feature to add, like accessing the camera roll for an existing photo with a QR code, but the clipboard makes more sense.

**Comment by adattudos** [comment]
Nice catch!
