### ISSUE TITLE
Payment Protocol integration

### ISSUE THREAD

**Issue by Joukehofman** [voisine/breadwallet#254]
Breadwallet is reporting that the signing of the payment protocol in incorrect. It does however work on all other wallets we've tried it on. You could test our payment protocol message by clicking the "donate now"- button on this page: https://www.bof.nl/do-your-bit/bitcoins-doneren/

**Comment by franamati** [comment]
This is happening too when using any BitPagos (https://www.bitpagos.com) merchant with breadwallet. Not sure if the certificate is wrong of if this bug is the reason.

**Comment by voisine** [comment]
Thanks for the report. The bits-of-freedom cert is using a x509+sha1 sig, I don't know if that has anything to do with it, but apples security framework returns an "underlying crypto error" when verifying the sig. And I haven't figured out why yet.

**Comment by dabura667** [comment]
sha1 is deprecated... Apple's crypto verifications will throw an error until they upgrade to SHA2.

Just fyi, Google's Chrome browser has stopped showing the green lock for any SSL cert using SHA1

Anyone dealing with bitcoin should upgrade to SHA2 (all SSL cert authorities will allow you to upgrade for free)

**Comment by voisine** [comment]
going to close this.. it happens for any sha1 sig, and sha1 is being phased out
