### ISSUE TITLE
coins not sending... unverified

### ISSUE THREAD

**Issue by dongordon** [voisine/breadwallet#255]
hi I've loaded bitcoins to my bread wallet and I've been trying to send them the past 4 hours and its not sending... this happens overtime, i have to wait for like 10 hours before they sent... can you please help

**Comment by voisine** [comment]
Funds are always sent instantly, but I assume you're talking about longer confirmation times. What version of the app are you using? Version 0.5.2, released just the other day has improved fees for faster confirmation during high network congestion. That said, now that blocks are filling up, long and/or uncertain confirmation times are going to happen at the margins no matter what wallets do.

**Comment by dongordon** [comment]
yeah the confirmation is still on zero, saying seen by o out of 3 peers and then it says unverified and asks me to rescan and I'm using the 0.5.2 version and also on wifi. so is there no way around thing to get fund to a different wallet with no issues? because this actually happens every time which is abit annoying

**Comment by voisine** [comment]
If it's asking you to rescan, then that sounds like a different issue. Can you give the transaction id for the one that's not confirmed? You can copy it to the clipboard from tx details.

**Comment by voisine** [comment]
Closing, feel free to reopen if you're still unable to send
