### ISSUE TITLE
breadwallet crashes after start Iphone 5S iOS 7.1.2 Jailbreaked

### ISSUE THREAD

**Issue by fullauto040** [voisine/breadwallet#257]
Since today the wallet crashes after i start it... but if i double tap the home button its there...
if i click it it disappears after 0.1 second, i reinstalled it and same shit, i dont have a phrase set (Wanted to set it today) and i got a bit of money on it.. shitty situation....

**Comment by nshopik** [comment]
Looks like #253

**Comment by fullauto040** [comment]
Finally figured out what's going on here. On iOS 7, the app will crash if you have an image copied to the clipboard. It tries to scan the image for a QR using an iOS 8 only core image method. Clear the clipboard and it will launch.

Thats the Solution, what the FUCK :dancer:

great support, where can it donate?
