### ISSUE TITLE
Allow import of private keys

### ISSUE THREAD

**Issue by akvadrako** [voisine/breadwallet#258]
It would be nice to be able to use my current bitcoin address and private key with bread wallet. Confusingly, there is an "import private key" function, but when I use it, it says it will send this money into my wallet. I don't want a transfer.

**Comment by dabura667** [comment]
This is not a good feature. I vote against implementing it.

-1

**Comment by jonasschnelli** [comment]
Private keys are very sensitive. Transferring keys from one device/wallet to another increase risks of getting compromised. You should consider requesting a "swipe" private key feature.

**Comment by dabura667** [comment]
> "swipe" private key feature.

Already implemented :-)

**Comment by voisine** [comment]
Yes, the problem with key import is that then not all your wallet funds can be recovered with the recovery phrase. That's why we only offer sweep.
