### ISSUE TITLE
Transaction still sent after reporting network timeout error

### ISSUE THREAD

**Issue by pinheadmz** [voisine/breadwallet#259]
...leading me to foolishly re-send the Bitcoin a second time (a double-spend!).

Received error message "Couldn't send, network timeout." So I tried again before realizing the first transaction DID go through.

**Comment by voisine** [comment]
Thanks for reporting. It's definitely a bug for the app to report to failure and then later succeed without re-sending. I will go through all the edge cases and make sure that will not happen.

**Comment by pinheadmz** [comment]
It occurred to me that I might have tried to send a transaction before the blockchain was synced, and perhaps the timeout error was not in reference to sending the first transaction at all? It makes me wonder, actually, if there is a way the app can sync with the network periodically in the background? I would even support a notification that reminded me to just open the app every morning and sync the blockchain so it's ready to go whenever I need it.

**Comment by voisine** [comment]
You won't get a popup timeout for syncing, it will just say "not connected" above the navbar. And it does actually do background network fetches after you launch the app the first time after rebooting. Just make sure you don't manually kill the app or turn off background fetching in settings.

**Comment by pinheadmz** [comment]
Just had this experience again, breadwallet v0.5.2 on iOS 8.1.1 (iPhone 6). Got two error messages about network timeout but this time I waited. Tx was still listed in the app and definitely hit the blockchain. Miner fee was 0.00006000 After rescanning blockchain with the app, everything was fine and balance is correct.

**Comment by voisine** [comment]
Thanks @pinheadmz, I believe this is fixed in the current github version, and fix will be included in the next app store update.
