### ISSUE TITLE
Not able to enter a pass phrase.

### ISSUE THREAD

**Issue by anyayakubu** [voisine/breadwallet#263]
Tried to help my brother set up Breadwallet on a new i phone. When I got to the part where it asked me to enter a pass phrase into it I typed a few letter and it disappeared from the screen went to wanting a four digit pin #. We don't know if it ever created a pass phrase or not. I don't feel safe with out a recovery pass phrase, not sure what I should do now. anyone know?

**Comment by voisine** [comment]
You only ever enter a passphrase when recovering an existing wallet. Is this what you were attempting to do? You can view the recovery phrase for your current wallet under settings->recovery phrase

**Comment by anyayakubu** [comment]
I realize that, but did it create a twelve word phrase for this wallet automatically, because I never got the chance to do it.  I'm not near his phone now so i can't see what if has for a pass phrase  or if it is there. If it made up one, i can copy it down next time i see him.

**Comment by voisine** [comment]
After tapping "new wallet" the next step is "generate recovery phrase". Tapping this causes a cryptographically random 12 word recovery phrase to be generated.

Your friend should not reveal the recovery phrase to you or anyone else. It is important to keep it private.

**Comment by anyayakubu** [comment]
I think you have answered my question, This isn't a friend is my brother, and the small amount of bitcoin in this wallet is what i gave him to get started. I understand how important it is to keep such a thing private, normally you don't share such information, but I will need to  show him where to go to see it and record it. We will do this next week, so if this phone is lost or damaged we can then recover it. Thanks for your help.
