### ISSUE TITLE
Now that CommonCrypto is gone; how would I add Scrypt?

### ISSUE THREAD

**Issue by losh11** [voisine/breadwallet#265]
I've got no examples on how to add scrypt now...

If someone could help me do something [like this](https://github.com/peritus/doughwallet/commit/67a8cfe4de0cab15ee274da6aa35dd736ee5204f) that would be great.

I'm sorry if I'm being a lazy dev.

**Comment by voisine** [comment]
There is an implementation of scrypt in brkey+bip38 which doesn't rely on commoncrypto. We're working on a cross platform straight-C port of the wallet and networking core, which is why we're eliminating dependencies on apple libraries.
