### ISSUE TITLE
Request: gift-spending

### ISSUE THREAD

**Issue by willnwhite** [voisine/breadwallet#266]
Please implement [gift-spending](https://github.com/willnwhite/gift-spending). Happy to help and talk more about it.

**Comment by voisine** [comment]
This isn't something we'd implement directly in the app, but we do allow exporting of used addresses via an x-callback-url, so you can make a companion app that looks up your tx history and then generates a donation payment request based on the gifts the user sets up.

**Comment by willnwhite** [comment]
Great! I'll get on it.
