### ISSUE TITLE
How to add OP_RETURN?

### ISSUE THREAD

**Issue by andreidumitru** [voisine/breadwallet#272]
Hi,

Thanks for the great open source. I'm trying to add OP_Return for the transaction, how can I achieve that?
I'm new to Bitcoin. Hope you can help me out.

Thanks

**Comment by voisine** [comment]
You'll want to use -[BRWallet transactionForAmounts:toOutputScripts:withFee:] with a custom OP_RETURN output script

This is quite advanced if you're new to bitcoin. You will probably have an easier time using some online raw transaction generation tool rather than writing your own code in breadwallet to do it, but I'm sure it would be a good learning experience.

**Comment by andreidumitru** [comment]
Hi,

Thanks for your quick answer.
So here's the thing. We want to add OP_Return for every sending transactions.
OP_Return will contain custom string.
So in Android, I achieved this, by first creating a transaction using a bitcoin address, then add Op_Return output to it.

sendRequest.tx.addOutput(Coin.ZERO, ScriptBuilder.createOpReturnScript(custom_output_bytes));

*****
    public static Script createOpReturnScript(byte[] data) {
        checkArgument(data.length <= 40);
        return new ScriptBuilder().op(OP_RETURN).data(data).build();
    }
*******
In android, they had this above script that create OP_RETURN output, and so I've added this to the outputs created with bitcoin address. So meaning all the transaction had two outputs. One with bitcoin address, and one with OP_Return.

So two outputs: generated by  
new Output(amount, ScriptBuilder.createOutputScript(address)) 
and
sendRequest.tx.addOutput(Coin.ZERO, ScriptBuilder.createOpReturnScript(custom_output_bytes));

I would like to know what code should I use to create custom Output Script, and in which place should I plant this code.

If you can provide me some code samples that will be great.

Thanks.

**Comment by voisine** [comment]
You'll want to use -[BRWallet transactionForAmounts:toOutputScripts:withFee:] and replace the current calls to transactionFor:to: and transactionForAmounts:toOutputScripts: in BRSendViewController

We don't have a script builder class, just -[NSMutableData appendUInt8:] and -[NSMutableData appendScriptPushData:], use appendUInt8: for script operations like OP_RETURN (0x6a) and use appendScriptPushData: for script data items

**Comment by bhugo** [comment]
hello andreidumitru,

If your attempt to add OP_RETURN is succesfull, I'd be glad to see how you did it and try your code! If you don't mind..
I had planned to do exactly that but you seem to be already fairly into it !

Thanks in advance.
