### ISSUE TITLE
Please help!!!

### ISSUE THREAD

**Issue by guero818** [voisine/breadwallet#273]
So I lost my phone today :( and luckily I had my paraphrase stored somewhere safe(yay) but when I recovered my wallet there's nothing in there and there is no transaction history either what can I do to contact support or to recover my funds :/???

**Comment by dabura667** [comment]
Question: *AFTER* you wrote down your phrase, did you attempt to screenshot your phrase (by pressing the Home button and the Sleep button at the same time)?

**Comment by voisine** [comment]
You can contact support@breadwallet.com

Did syncing complete? It can take several minutes.

**Comment by dabura667** [comment]
@guero818 
For reference:

I have been using breadwallet for 14 months, and have over 200 transactions in my history, and it takes me about 10-15 minutes to restore from scratch.

**Comment by guero818** [comment]
Thanks a lot for the help guys yes seems like it restored and yes it took like 5 mins but nothing shows up :/. I'll try logging out and back in to see what happens. You think support can help if I provide the info they request? Thanks again guys

**Comment by guero818** [comment]
And yes lol I did screen shot the paraphrase but I got a new one and wrote down the second one. Do you think that has something to do with it?

**Comment by dabura667** [comment]
> And yes lol I did screen shot the paraphrase but I got a new one and wrote down the second one. Do you think that has something to do with it?

I know a lot of people who did this:

1. Write down phrase
2. take screenshot
3. don't realize the phrase changed
4. continue on, thinking their wallet is the first phrase.
(Currently, breadwallet will send you back to the very first screen if you try to screenshot it, so you are very aware that the old phrase is gone (you have to tap "Create New Wallet" again))

Are you sure the one you are trying to restore isn't the FIRST phrase (the wrong one)?

**Comment by voisine** [comment]
If you still have the screenshot, you can also try that phrase. I'm closing this issue since the current version of the app has been improved so this situation doesn't happen. Please contact support@breadwallet.com if you need further assistance
