### ISSUE TITLE
passcode dialog cancel button non-functional on iOS 9

### ISSUE THREAD

**Issue by voisine** [voisine/breadwallet#275]
the alert view cancel button when entering your passcode doesn't work on iOS 9

was hoping this was an iOS 9 bug that apple would fix at least for apps built under earlier iOS versions

**Comment by koalalorenzo** [comment]
I was noticing the same yesterday! I was forced to update the passcode or quit the app.

**Comment by voisine** [comment]
nice, this fix also drops CPU usage from 100% down to 0%
