### ISSUE TITLE
iOS 9 cancel transaction

### ISSUE THREAD

**Issue by Onefox** [voisine/breadwallet#281]
With an iPhone 5 and 9.0.1 iam not able to hit the cancel button.

This one on the screenshot.
http://imgur.com/bN1I0eG

Steps to reproduce:
1. Open the App on an iPhone 5 with ios 9.0.1
2. Scan a coinbase payment code or a normal address.
3. Try to cancel it.

Also giving in the wrong code don't do anything.

**Comment by nolith** [comment]
This bug has already been reported as #275

**Comment by Onefox** [comment]
Ah thanks.
