### ISSUE TITLE
wrong amount in coinbase payment.

### ISSUE THREAD

**Issue by Onefox** [voisine/breadwallet#282]
Device iPhone 5 with ios 9.0.1.

If you try to use a coinbase qr code, and change the amount there its still the old amount although the qr code is updated with the new amount.

For example:
Go to:
http://imgur.com/r1Qx6EP
(https://www.coinbase.com/checkouts/fe543c1fbe3f17ecba299323532ac0c8)
The qr code contains:
bitcoin:1CZXZ37JWZDzvdW4y1uSSSBj9MM3sfgWyL?amount=0.10&r=https://www.coinbase.com/r/560a5b9b4d0473222b000082

Kill the Application.

Now change the amount to 0.25:
http://imgur.com/HS8LFOJ
The qr code is update to:
bitcoin:1CZXZ37JWZDzvdW4y1uSSSBj9MM3sfgWyL?amount=0.25&r=https://www.coinbase.com/r/560a5b9b4d0473222b000082

Scan the qr code again with the new opened app.

The amount will still be 0.1 bitcoin.

**Comment by voisine** [comment]
This is bug in coinbase's payment protocol server. Notice the URL following r= is the same for each request. It's not generating a new protocol request object for the second one.
