### ISSUE TITLE
Bad rendering when switching/opening the app

### ISSUE THREAD

**Issue by koalalorenzo** [voisine/breadwallet#284]
When I was in settings, or in the "menu" of the app and then I close it and re open it, 4 of 5 times, this is what I see when I  re-open the app:

![img_3217](https://cloud.githubusercontent.com/assets/33528/10214126/7ac43f9a-6815-11e5-98d3-a96d97d659cd.PNG)

I am using the iOS 9.0.2 with the latest version from the Apple Store

**Comment by voisine** [comment]
I believe this is fixed in the current app store release.
