### ISSUE TITLE
Selectable Network Fee

### ISSUE THREAD

**Issue by AutoDMC** [voisine/breadwallet#286]
Half of my transactions from breadwallet to coinbase end up listed as "medium priority" because breadwallet selects a transaction fee which is way too low.

Without fail, the transactions that bungle are the ones I'd really, really appreciate happening within a block.

I'd thought the last couple of times when it happened was because I was emptying out a wallet, so this time I made sure to leave a couple thousand bits in the wallet, so it could pick as big a transaction as it needed.  My latest transaction picked 18.5 satoshi per byte.  I had plenty of bits left in my wallet to pay 90 satoshi per byte, which this service lists (at this time) as the 0-1 block confirmation time:  http://www.cointape.com/#delay

I'd like either a slider to select a higher priority, radio buttons to select the fee, or an "advanced screen" text box I can edit.  Or even an option to select the algorithm used to select the fee.

I appreciate the simplicity of the wallet software, but I appreciate it way less when I've got a transaction that is estimated in 6+ blocks.

**Comment by voisine** [comment]
Thanks for your feedback @AutoDMC, it helps us to gauge where we need improvement.

It would help us a lot if you can explain what your use case is that you need really fast confirmation times. There are a lot of use cases for instant transactions, but anything that requires confirmation is not going to be possible to do instantly no matter what fee is paid.

"medium priority" is currently what we're targeting, a nice balance between low fees and timely confirmation. Once you're in a situation where you have to wait for a confirmation, you go from having an instant transaction, to a check-back-later model. In that case waiting 5-20min, vs 15-45min isn't all much of a difference in most cases. One exception that was brought up is the American style of paying a restaurant check, where sitting around for 10min while the waiter shuffles your bill/credit card back and forth a few times is typical. What use case are you encountering?

**Comment by AutoDMC** [comment]
@voisine The main use case is when I need to take bitcoins in my main wallet (breadwallet) and transfer them to Coinbase so I can turn them into dollars, because I need dollars.

In this case, the deposit time from Coinbase is a couple of days, so the world doesn't end if a transaction takes an hour or two in the grand scheme of things...

...but now I have to sit there and refresh blockchain.info, or spam Coinbase, to see when the bitcoin is actually confirmed so I can trigger the "make it dollars" functionality in Coinbase.

With the option to set an "Instant" fee, I can set an alarm for 15 minutes, come back, and be done with it.  As it is now, the final 6-total-confirmation-baked-into-a-block time is anywhere from 20 minutes to ???.  I'm reduced to constantly checking back every 30 minutes or so.  One pathological transaction took > 6 hours to get fully baked into a block.

The difference in transaction fee between "medium" and "high" priority is a nickel.  I recognize that for most transactions a "medium" transaction works just fine, but I'd really like a "next block or so" option.  It's worth a nickel to save the time and frustration of an open ended transaction, when I absolutely, positively, need to know when a transaction is baked in, which is what I need when I'm trying to get dollars out of my bitcoins via Coinbase.

(As a UI suggestion:  Having a button labeled "Rush" on the amount input screen, or in the popup where you punch in your pin to auth the transaction would be nice.  Alternatively, having a "rush transaction" option, even if I had to go into the hamburger menu, would be useful.)

I recognize this is a bit of an edge case, but I run into it every month or so.  And every time I do I have dark thoughts about breadwallet, dark thoughts it doesn't really deserve in the long run.  Because other than this monthly frustration, I actually really love it.

**Comment by voisine** [comment]
We're quite opposed to adding advanced options that no-one but bitcoin nerds will ever use. Having a "rush" button is the best UI suggestion I've heard for fee selection, much better than a priority slider. However from a user's perspective, transactions are already instant, so what in the world is this "rush" option? They don't know what confirmations are. (we show them for people who do know, but we expect most users to ignore it).

I think the approach we would prefer to take is to further refine and improve the fee selection to avoid any such degenerate cases and keep confirmation times within the hour except for the rare case where no blocks are found for a long stretch.

In that >6 hour case, do you remember if it was it on the latest version of the app, and if it was during the recent coinwallet.eu spam attack?

**Comment by AutoDMC** [comment]
The pathological transaction was posted 2015-07-28.

It was on a previous version of the app (I believe), and it was not during any attempted spam attack.  AFAIK, there wasn't even a peak level of activity around that time;  I researched it pretty hard before I discovered it was simply pathological transaction selection by miners due to a low-ish transaction fee.

Complaints aside, I *do* applaud keeping the wallet simple and I'm not quite sure of the best way to handle this.  Even a checkbox on the configuration page making all transactions a "rush" transaction has the negative connotation that "regular transactions" are slow, when for the most part they're fast enough for day to day work.

Would you guys be interested in/willing to use the Cointape API?  ( http://www.cointape.com/api ).  This could be an option in the wallet to use the internal fee calculator (recommended) or the Cointape API.  And if the Cointape API is selected, the user can select which "speed" they want their transactions;  Fastest, Half Hour, or Hour.

For most users, they would just use your internal calculator and never be the wiser.  For power users (or people who consider themselves power users) who are willing to configure the app, they could use the Cointape fee calculator.  With the benefit that a casual user that blunders into the "advanced" fee setting can't shoot themselves in the foot;  worst case they spend a nickel too much by jumping on the "Fastest!" button.  If the api fails, you just fall back to the internal calculator with a notice for "power users" who've set the cointape option.

**Comment by voisine** [comment]
We have an api hook so that we can bump up fees in an emergency since app updates take a week, but it's currently unused. We want the wallet to function as well as possible without reliance on any services other than the bitcoin network.

Just in general, I'd rather have a whole separate app for power users, and do everything we can to make the main app work for as many people as possible. If you have fast confirmation use cases, then others will too, and we should serve them even if they have no idea what a confirmation is (nearly everyone)

**Comment by voisine** [comment]
@AutoDMC api hook is now live, you shouldn't see this issue any longer
