### ISSUE TITLE
"runaway" is not a recovery phrase word

### ISSUE THREAD

**Issue by giacecco** [voisine/breadwallet#288]
I own an empty wallet I used Breadwallet to manage until a few months ago. 

This morning I've tried recovering it and got the message you see in the subject. Does this mean I am such an idiot that I wrote down the passphrase wrong when I generated the wallet, or there's something else going wrong?  

@voisine I am happy to share the entire passphrase if you're curious. As I said, I emptied the wallet long ago. Thanks.

**Comment by voisine** [comment]
Here's a list of all the valid english recovery phrase words in alphabetical order:

https://github.com/bitcoin/bips/blob/master/bip-0039/english.txt

I'm guessing the word you're looking for is "runway"

**Comment by dabura667** [comment]
> Does this mean I am such an idiot that I wrote down the passphrase wrong when I generated the wallet

Not an idiot, just forgot to check twice. haha

"runway" is on the list, so that's probably what you meant to write down ;-)

**Comment by giacecco** [comment]
It was "runway", and that's what I call an idiot, as I perfectly knew how important it was to get the passphrase right! :-( Thank you all.
