### ISSUE TITLE
Implement "BIP 47: Reusable Payment Codes for HD Wallets"

### ISSUE THREAD

**Issue by eragmus** [voisine/breadwallet#289]
> This BIP defines a technique for creating a payment code which can be publicly advertised and associated with a real-life identity without creating the loss of security or privacy inherent to P2PKH address reuse.

> This BIP is a particular application of BIP43 and is intended to supplement HD wallets which implement BIP44.

> Payment codes add identity information to transactions which is useful in a merchant-customer interaction while protecting the privacy of users. Payment codes provide the privacy benefits of Darkwallet-style Stealth Addresses to SPV clients without requiring the assistance of a trusted full node and while greatly reducing reliance on blockchain storage.

Thoughts on implementing this into breadwallet?

Samourai Wallet recently had this to say about it:
> We have made very big progress in implementing BIP47 payment codes (stealth addresses for SPV/mobile) and you will all be seeing them in an upcoming version of Samourai Wallet. All of the building blocks are in place and now we just have to fit them together in an easy-to-use UI and work them into our wallet app.

Prior discussion on the topic:
> https://www.reddit.com/r/Bitcoin/comments/3alzga/bip47_reusable_payment_codes/

Thanks.

**Comment by eragmus** [comment]
There is also something called "BitAlias II" -- thoughts on that?
> https://medium.com/@yanislav/bitalias-ii-9a6e11e17c0d

> https://bitalias.github.io/

**Comment by dabura667** [comment]
> we just have to fit them together in an easy-to-use UI

This is the biggest hurdle imo.

Basically, Samourai Wallet just said something akin to "Bitcoin can be a great micropayment platform without any Layer 2 protocols... we just have to scale the system in an efficient manner." (aka easier said than done)

Granted, the UI problem of BIP 47 payment codes is not as big a problem as Bitcoin scalability, it's still a pretty big hurdle.

For breadwallet's case, synchronization for restoration of BIP47 wallets will take significantly longer, as the app would need to scan the ID addresses with a bloom filter first, then once that is up to date, it would need to generate the addresses for each pairing from scratch (though this could be optimized to only start scanning from the first found ID transaction. That would still take a while)

BIP 47 would work well with servers to query, such as Electrum, Mycelium, and Copay. But the SPV node method of directly connecting to the network like breadwallet would lower UX significantly. Though not as much for newly created wallets (as we can assume no pairings have been made, and just start searching from the point of creation.)

**Comment by eragmus** [comment]
Besides transaction privacy, I think BIP47 will actually long-term enhance UX significantly -- only need 1 address to share with everyone, rather than having to generate a new receive address every single time and avoiding address reuse. It will turn Bitcoin more into a mainstream system.

Again, this was just a suggestion, but I think it's pertinent to point out -- SPV was also hard and new, but @voisine was entrepreneurial enough to develop it! :) And, as a result, he succeeded in making breadwallet one of the most respected wallets in Bitcoin (universally popular and recommended on r/bitcoin). Just saying, you reap the rewards of innovative work. If something was easy, everyone would do it... but then, it consequently has less meaning and less impact.

In terms of "newly created wallets" vs. "existing wallets": If it's a significant issue, maybe new users by default can use the new system, while old users can be prompted with an option to "migrate to new single-address system" or "postpone and remain on current system"? I'm not really understanding the issue being described though, so I might be suggesting the wrong thing.

**Comment by keo** [comment]
:+1:

**Comment by voisine** [comment]
we will be implementing BIP75 as an alternative to BIP47 that doesn't require an initial dummy transaction, doesn't store non-bitcoin-transaction data in the blockchain, doesn't require monitoring an additional address chain per trading party, etc...
