### ISSUE TITLE
choose bitcoin symbol type and units

### ISSUE THREAD

**Issue by richardsj** [voisine/breadwallet#29]
It would be good to be able to select e.g. Ƀ
and use 'bits' (microbits) or just BTC

**Comment by rgenito** [comment]
I see this was closed long ago, and for what it's worth: my company has done extensive research on this topic. What it boils down to is that the current bitcoin users are smart enough to figure out and understand "bits" in the Bitcoin context, while complete Bitcoin newbies understand "bits" intuitively. We all favor mass adoption, and the sacrifices made to get there (such as using "bits") are a great investment whether we support it or not: it's what makes sense to the common person that counts.

**Comment by lucasdantur** [comment]
It would be very much appreciated if the user has the chance to decide which unit to use.
