### ISSUE TITLE
Timeout for 4/5 transactions

### ISSUE THREAD

**Issue by AndersBNielsen** [voisine/breadwallet#291]
Over the last couple of days I've been experienced way more timeouts than I'm comfortable with and a few issues like #259 - reinstalling and killing/restarting the app doesn't seem to have any effect. 

"The transaction is annulled, timeout error" happens pretty much every time and a few times I've been at the verge of panicking because I can't export my private keys. 
Especially annoying when trying to pay for something, like lunch, which means I have to keep extra coins in my blockchain.info account for when Breadwallet just doesn't work.

Is the issue related to the current malleability attack or is Breadwallet connecting to "bad nodes"?

It's probably a coincidence but just seemed to go away after sending and extra bit, changing the transaction.

**Comment by dabura667** [comment]
> Is the issue related to the current malleability attack or is Breadwallet connecting to "bad nodes"?

Both, kind of. My theory is that you're connecting to nodes that raised their minrelaytxfee setting.

**Comment by voisine** [comment]
I haven't run into this myself yet, but we have had a few complaints. That is my guess is well. It's frustrating that people who think they're helping the bitcoin network are actually being bad citizens, by randomly changing relay rules without coordinating the change with the rest of the network.

I will do some investigation and see if there's a reliable to detect non-conforming nodes and disconnect from them.

**Comment by voisine** [comment]
to be fair, the wallet needs to assume that random p2p nodes are hostile and react in a robust manner.

**Comment by voisine** [comment]
@AndersBNielsen, did you happen to send more than one transaction in a short period of time? In that case it may have been the result to tx malleability.

**Comment by AndersBNielsen** [comment]
I wouldnt say I have enough data to generalize but I do have a feeling the issue is more common when sending the same amount several times in a row(or trying to) which might explain why the 2000000b transaction that wouldn't go through suddenly did when I changed it to 2000001b.
It could be a buggy way some nodes try to stop the tx mal issue... Doesn't make sense that a transaction with different inputs/outputs but the same amount would get caught there though 

Would a retry button that retries with different random nodes solve the issue? (assuming the majority of nodes don't behave this way.)

**Comment by voisine** [comment]
tx malleability would only potentially be the cause if you are spending unconfirmed outputs, i.e. when you have more than one unconfirmed tx in your wallet at the same time, (since the second might depend on the change from the first if both are sends)

if it's a problem with tx relay rules, then hopefully we could detect that when we connect to the node or at least when we attempt to spend, and then mark it internally as misbehaving, drop it, and select another. we definitely want to avoid the user having to take any special action or even be aware of anything other than a timely and successful transaction.

**Comment by AndersBNielsen** [comment]
I don't think it's related to spending unconfirmed outputs because that doesn't happen a lot.
I like the idea of silently retrying with different nodes. 
By the way - when this occurs it takes around 15 seconds before I get the error - hopefully detecting misbehaving nodes won't take that long.

**Comment by AndersBNielsen** [comment]
Will everyone increasing it make worse?
https://www.reddit.com/r/Bitcoin/comments/3oecqm/psa_to_address_mempool_flooding_bitcoin_core/

Den søndag den 11. oktober 2015 skrev Aaron Voisine <
notifications@github.com>:

**Comment by voisine** [comment]
I bet this is what's causing it right now... thankfully we have an api hook in place to bump fees remotely (within a hard coded range for security). It's in the app already, we just need to setup the api endpoint, which we will be doing directly.

**Comment by AndersBNielsen** [comment]
I just ran into the issue again. It doesn't make sense but it seems to appear when I'm trying to send the exact same amount as my last transaction.

Last transaction: 2,000,001
Tried transaction: 2,000,001 - failed three times and probably would've failed infinitely.
Succesfull transaction: 2,000,002
It doesn't make sense since the outputs are obviously different but it seems to be the case - is there any way this would make sense?

For POS-uses this is terrible since merchants usually expect the exact amount and not 100 satoshis less or more - luckily what I'll be paying a merchant is very unlikely to match the amount I last sent. 

Maybe the fees isn't what's causing this - they are already higher than typical spam.

**Comment by voisine** [comment]
is there any difference to the tx fee?

**Comment by AndersBNielsen** [comment]
No. Total output only differs by the 1b changed.

**Comment by voisine** [comment]
ok, I can't imagine why it would do that, very strange, but I will try to duplicate... Is it possible that some nodes have rules that attempt to try stop people making mistaken double tx ? Was the payment address the same for the first and second tx? Do you feel comfortable sharing the txids? You can send me private email with them so I can have a closer look if you're comfortable with that.

**Comment by KickedMe** [comment]
I'm experiencing timeout issues as well

**Comment by voisine** [comment]
@AndersBNielsen @KickedMe @dabura667 we setup an api endpoint for an emergency fee bump. Everything should work now.

There is still one small edge case that @NicolasDorier made me aware of, the min-relay-fee increase had a side effect of also increasing min-output-amount. So if you try to send less than about 7bits, or if a change amount happens by unlucky coincidence to fall between 5.46 and ~7bits, you may see the issue again. We will be pushing out an app update shortly to address this along with a few other more minor bugs.

**Comment by AndersBNielsen** [comment]
Awesome! I should point out that I haven't seen this bug for the last two days though.
Maybe the fee bump is premature but we'll probably find out soon enough and if so it's reversible, right?

**Comment by voisine** [comment]
I saw it earlier today. I think it depends on what nodes you connect to. In any case it's only a bump from 1/2 a penny to 3/4 penny for a typical tx
