### ISSUE TITLE
Notification Center QR code

### ISSUE THREAD

**Issue by losh11** [voisine/breadwallet#295]
The QR code in Notification Center can seem too whitey if the user background is really bright.
So this is what I'm talking about ![image](http://i.imgur.com/BMKOOsE.jpg)

That picture doesn't show what it is like if the background is white or a very light colour background, but I think you'll know what I mean.

Please think about changing QR code from opaque to white.

**Comment by voisine** [comment]
I'm sorry, I don't understand the issue you're having. On a pure white background, the QR scans just fine for me. Also if it were completely opaque (no transparency) it would just be whiter. If you mean to invert the white and transparent parts, not all QR scanners are able to handle that.

Do you have an example of a QR that doesn't scan well?

**Comment by voisine** [comment]
Feel free to reopen if you're still having an issue.

**Comment by dabura667** [comment]
I think what he means is:

> Make the "black" portions 100% opaque black and "white" portions 100% opaque white. (ie. not match the rest of the notification center, just paste the pure black and white image on there)

It would make it look tacky, but would remove any possible reading problems.

Though from the sounds of it, I think the user just doesn't like the look of it on some backgrounds.

I'd say NACK unless the user can provide a screenshot of a situation where this makes the QR unreadable.
