### ISSUE TITLE
Can't see how to initiate payment by "opening a [BIP70] payment request file directly"

### ISSUE THREAD

**Issue by willnwhite** [voisine/breadwallet#296]
https://bitcoinj.github.io/payment-protocol#protocol-overview says:
> In a payment handled by the [BIP70] payment protocol, the process is initiated in one of two ways:
1. The user clicks a Bitcoin URI that has a new “r” parameter, which contains a (http) URL that resolves to a payment request file.
2. The user opens a payment request file directly.

How can I get breadwallet to do 2.?

**Comment by voisine** [comment]
It's registered to handle the appropriate mime type and file extension, so you can for instance tap on a payment request file in an email attachment and it will launch breadwallet.
