### ISSUE TITLE
Problem with Passcode

### ISSUE THREAD

**Issue by wbret** [voisine/breadwallet#297]
We just installed BreadWallet on our iPhone and went to a bitcoin atm and added money to it but when we try to send it, it wants a passcode.  We never entered a passcode or a recovery phrase when we installed it. .  Please help, we need our money off of there.

**Comment by voisine** [comment]
Sorry you're having an issue @wbret. We handle support requests through support@breadwallet.com, please contact us there and we will do our best to take care of your issue.
