### ISSUE TITLE
Are'nt we missing an addressbook?

### ISSUE THREAD

**Issue by mortengh** [voisine/breadwallet#302]
I keep all other peoples bitcoin addresses in a text file, but I would much rather have it in an in-app address book. Could this be implemented?

**Comment by voisine** [comment]
Reusing addresses is anti-pattern we want to discourage. For now the correct way to do it is to request a payment address each time you want to pay someone (or have them send you payment request). There are some standards in the works to better automate this process.

duplicate #58
