### ISSUE TITLE
Any chance of denominating the transaction amount in a fiat currency?

### ISSUE THREAD

**Issue by NanoAkron** [voisine/breadwallet#304]
Often I want to send somebody just a small amount as a tip or something (e.g. 20p), but I have to keep typing in and erasing different BTC values until I get near the amount I want to send in fiat.

Would there be any chance of making it easier to denominate my transaction in fiat rather than by using guesswork?

**Comment by voisine** [comment]
You can do this now, but obviously the UI must not be very intuitive.

As a user wanting to enter an amount your local currency, what way would make intuitive sense for you to be able to do that? How would you want to change the UI to make it easy to do that?
