### ISSUE TITLE
unknown recovery phrase and passcode

### ISSUE THREAD

**Issue by NinerXrayBravoTwoTwo** [voisine/breadwallet#305]
Just tested the app to see the interface and then deleted it for about a year.  Just reinstalled it to try it again but the app still expects me to remember the passcode or recoverphrase ...

Never cared or read the manual when I installed it the first time and there doesn't seem to be any way to wipe it and start over.

Never did find anyone to get a bitcoin from or give a bitcoin to ... never had any bitcoins ...

How do I start over?  Is there a FAQ?

**Comment by voisine** [comment]
After 8 different passcode attempts and about 24hrs of lockout, it will reset and you can start a new one

**Comment by NinerXrayBravoTwoTwo** [comment]
(Could possibly add that as a footnote in the manual page.)
