### ISSUE TITLE
Do not add unverified transactions to balance

### ISSUE THREAD

**Issue by TCSchrodinger** [voisine/breadwallet#307]
Currently unverified transactions sent to the wallet are immediately added to the balance and are "spendable". This is bad.
Here's a case that happened to me:
While testing a bitcoin client, I sent a small amount to BreadWallet. The client messed up the transaction fee, resulting in a transaction that never verified. ( Been waiting 6 weeks now. ) No problem, it was only 25 cents. But that transaction sits forever in bread wallet, right at the top of the screen.  ( This could be used as a pseudo-DOS attack on the wallet, if I were to flood someone with a few hundred small transactions designed to never verify.) 
To get rid of the nuisance transaction,  I sent my entire balance to a different wallet with the intent of wiping the current Breadwallet and starting new. Unfortunately I did not realize Breadwallet included the 25 cent unverified transaction in my balance. So this second, high value transaction also got stuck because it was dependent on the first, never verifying, hanging there like a wet sock on a shower curtain rod. Now two unverified transaction sit staring me in the face.  After a long series of resyncs, wiping the wallet, forcing a double spend ( by timing my send to be between the sync of the first transaction and the second ), and lots of swearing, I did get my balance off of Breadwallet, and now I can start new, without the 25 cent transaction of death clogging everything up. 
So maybe allowing spending of unverified transactions is a nice when the network is slow, but it needs to have a warning or to require an explicit override, or be disallowed. Also the ability to drop unverified sends to Breadwallet should be possible. 
I'm also concerned that someone *might* be able to craft a con where they send unverifiable money to a BreadWallet user, and they think its good because BreadWallet lets them try to spend it, even though the transaction will never confirm. ( Yes they should know better, but so should BreadWallet. )

TC

**Comment by voisine** [comment]
Thank you for the report. This is really useful feedback. Do you by chance have the tx id of the large transaction that got stuck? What about the one that did eventually confirm?

breadwallet will increase the fee when spending unconfirmed non-change inputs to trigger child-pays-for-parent, which is supported by a certain percentage of miners. This is specifically to avoid the situation you describe, however the bitcoin network standard relay behavior was recently, suddenly and haphazardly modified by a lot of full node operators by raising the minimum relay fee. I'm wondering if this may have caused the low fee tx to propagate inconsistently. Another possibility is that the tx that finally did confirm was actually the first one breadwallet sent, and it just took a while to get picked up by a cpfp miner.

**Comment by TCSchrodinger** [comment]
Thanks for the quick response.

Transaction 1: 998.09 bits, to Breadwallet : ID 160a962d238397e31cc4a989e0682e82ba4eceefc44f7f3629289d27161627ae
sent about 4 weeks ago, *still* shows up unverified. I don't have data anymore on what the fee was, but it very low. 

Transaction 2: Send full balance out of bread wallet ( included unverified change above) :  de4e484d131798fd0c0d91f326b5a63b1b8176f340a4f361ffa11fb192f18001 about 3 days ago. Would not verify. Figured it was because of 1.

Tried to backfill the 998 bits by sending again to the addresses making up the 1st transaction. Confirmed very quickly, but didn't unjam anything.

I noticed that doing a resync would cause Breadwallet to show a balance for a short period if time ( between seeing Transaction 1 and 2? )  So I sent the full balance again *minus* the 998.08 bits (plus a little more for safety) during that time window. Breadwallet took the transaction, but it immediately came up invalid, and marked as a double spend.  Wiping the wallet again, and resyncing, it showed up as confirmed: (yay) 12a1c27d115dbfc12914c83df25cd933d2bce70dce4c88b64302c61263e06828  (Transaction 3)


I didn't know about "child-pays-for-parent", that sounds like it should have worked, but it didn't seem to work in this case. I'm sure transaction 3 is the one that went though and not transaction 2 as you theorize since the amount was less. Though as I think about it, since the transactions are built up from  multiple addresses there would be no reason to assume sending again with a smaller amount wouldn't still include the unverified amount?  Maybe the backfilling worked? 

Thats all I know, I am no where close to being able to do bitcoin forensics, but hopefully this is useful to you. But I can say with certainty that having a good hunk of money get stuck in nowhere land is a very bad user experience. ;-)

thanks for your attention,

TC

**Comment by voisine** [comment]
This is really useful info. Having real world examples is extremely helpful to refine the wallet behavior. I'm making some changes to better handle the possibility of the inputs not being well propagated, and I'll see what else I can figure out.

**Comment by voisine** [comment]
for reference, incase the tx drop off the network later

tx1:
{
"block_height": -1,
"block_index": -1,
"hash": "160a962d238397e31cc4a989e0682e82ba4eceefc44f7f3629289d27161627ae",
"hex": "010000000107be1191cefe10b5aba80b61bdb7b451bf6ec46ed890cb5be6994ea87816cfa0010000006a4730440220438b8c22deade3cea186436404b7a8e9c75f242008f5b3a683289732d3d2586b0220034d2b1b81f9bf983be3cf3d4f7f28a17f100d646341887d2c941c37fee2b672012103de33f58e5330851167cfb33dd10773b4f351e5c1f310c7d1ac7418902dfde956feffffff01e1850100000000001976a914513e8084ac3e019c6ea529fbb99619afca16f84d88acc7c60500",
"addresses": [
"18QacFo17auZ4hfDEBLMhnoBG2jgTxnJA9",
"1C79DHbEAsqLQxaoSpdJpZ1Z1YnruPZNSu"
],
"total": 99809,
"fees": 191,
"size": 191,
"preference": "low",
"relayed_by": "176.10.116.242:8333",
"received": "2015-11-06T00:09:34.972Z",
"ver": 1,
"lock_time": 378567,
"double_spend": false,
"vin_sz": 1,
"vout_sz": 1,
"confirmations": 0,
"receive_count": 92,
"confidence": 0.32760503033370314,
"inputs": [
{
"prev_hash": "a0cf1678a84e99e65bcb90d86ec46ebf51b4b7bd610ba8abb510fece9111be07",
"output_index": 1,
"script": "4730440220438b8c22deade3cea186436404b7a8e9c75f242008f5b3a683289732d3d2586b0220034d2b1b81f9bf983be3cf3d4f7f28a17f100d646341887d2c941c37fee2b672012103de33f58e5330851167cfb33dd10773b4f351e5c1f310c7d1ac7418902dfde956",
"output_value": 100000,
"sequence": 4294967294,
"addresses": [
"1C79DHbEAsqLQxaoSpdJpZ1Z1YnruPZNSu"
],
"script_type": "pay-to-pubkey-hash",
"age": 3920
}
],
"outputs": [
{
"value": 99809,
"script": "76a914513e8084ac3e019c6ea529fbb99619afca16f84d88ac",
"addresses": [
"18QacFo17auZ4hfDEBLMhnoBG2jgTxnJA9"
],
"script_type": "pay-to-pubkey-hash"
}
]
}

tx2:
{
"block_height": -1,
"block_index": -1,
"hash": "de4e484d131798fd0c0d91f326b5a63b1b8176f340a4f361ffa11fb192f18001",
"hex": "010000000352d287ff1db11e6b3cb798df292468a6c034d2b25fb2f621dfc31068236b2abe010000006b483045022100d772ca71dffb9780c3652577f0cf6e42644f76373ef38bedc7878fc3705c464f0220690dea9a7293843dae3e3753bdd80775296163ff79d6a560de16cb1139fe9f5c0121025154eeac830412c8b98a58944220b689c7f3d7e9863066fbfd3934624a439dd2ffffffff6f9fe933dd0c30d78f9232961fd0d1ff420e1ff46065cd1ecb5d7e02c4d4711b000000006a473044022068eb1595f1f8327c86c3bdb0da869b9ac9cc67979e8da72b78bc9e39c6602ffa022079d6575140bbcb86e4f226b1272df1540204eb9e7b699aa2ac1de2e1271b8a28012102b757b161f13400a37807f1269ba753d4c691e87e17677012f297ff482dc369bfffffffffae271616279d2829367f4fc4efce4eba822e68e089a9c41ce39783232d960a16000000006a4730440220450c43fb2f5a0bbe6f88bbd70132e8292a2076eb5f6c554f3cb5c340c8b6097d02205ada35537ec8a08bf637016dfa183fd4964c63371510028136fd4fd328b6f6f7012103ba4cf759c610d54ca0b0be1b5678cd6324435b0b986f5436ee4c6488c1123f00ffffffff01659ec602000000001976a91442b0092fd88816d7450b4264b5a92e407926faab88ac00000000",
"addresses": [
"175cUrDkDstiiL6cUCrkBekvDP7xtqNE9q",
"18QacFo17auZ4hfDEBLMhnoBG2jgTxnJA9",
"1GEvRGuxyv3bjTZna8mPEcQmqmK5cGTEAB",
"1KkQ6fn6aBvmyZP68LS8miK4GSUcdxkKQm"
],
"total": 46571109,
"fees": 18800,
"size": 486,
"preference": "medium",
"relayed_by": "54.93.40.236:14888",
"received": "2015-11-05T23:41:39.138Z",
"ver": 1,
"lock_time": 0,
"double_spend": true,
"double_spend_tx": "12a1c27d115dbfc12914c83df25cd933d2bce70dce4c88b64302c61263e06828",
"vin_sz": 3,
"vout_sz": 1,
"confirmations": 0,
"confidence": 0.01,
"inputs": [
{
"prev_hash": "be2a6b236810c3df21f6b25fb2d234c0a6682429df98b73c6b1eb11dff87d252",
"output_index": 1,
"script": "483045022100d772ca71dffb9780c3652577f0cf6e42644f76373ef38bedc7878fc3705c464f0220690dea9a7293843dae3e3753bdd80775296163ff79d6a560de16cb1139fe9f5c0121025154eeac830412c8b98a58944220b689c7f3d7e9863066fbfd3934624a439dd2",
"output_value": 6490100,
"sequence": 4294967295,
"addresses": [
"1KkQ6fn6aBvmyZP68LS8miK4GSUcdxkKQm"
],
"script_type": "pay-to-pubkey-hash",
"age": 3418
},
{
"prev_hash": "1b71d4c4027e5dcb1ecd6560f41f0e42ffd1d01f9632928fd7300cdd33e99f6f",
"output_index": 0,
"script": "473044022068eb1595f1f8327c86c3bdb0da869b9ac9cc67979e8da72b78bc9e39c6602ffa022079d6575140bbcb86e4f226b1272df1540204eb9e7b699aa2ac1de2e1271b8a28012102b757b161f13400a37807f1269ba753d4c691e87e17677012f297ff482dc369bf",
"output_value": 40000000,
"sequence": 4294967295,
"addresses": [
"1GEvRGuxyv3bjTZna8mPEcQmqmK5cGTEAB"
],
"script_type": "pay-to-pubkey-hash",
"age": 324
},
{
"prev_hash": "160a962d238397e31cc4a989e0682e82ba4eceefc44f7f3629289d27161627ae",
"output_index": 0,
"script": "4730440220450c43fb2f5a0bbe6f88bbd70132e8292a2076eb5f6c554f3cb5c340c8b6097d02205ada35537ec8a08bf637016dfa183fd4964c63371510028136fd4fd328b6f6f7012103ba4cf759c610d54ca0b0be1b5678cd6324435b0b986f5436ee4c6488c1123f00",
"output_value": 99809,
"sequence": 4294967295,
"addresses": [
"18QacFo17auZ4hfDEBLMhnoBG2jgTxnJA9"
],
"script_type": "pay-to-pubkey-hash",
"age": 0
}
],
"outputs": [
{
"value": 46571109,
"script": "76a91442b0092fd88816d7450b4264b5a92e407926faab88ac",
"addresses": [
"175cUrDkDstiiL6cUCrkBekvDP7xtqNE9q"
],
"script_type": "pay-to-pubkey-hash"
}
]
}

**Comment by voisine** [comment]
Most recent update will rebroadcast dependent inputs.

We need to make an improvement though to Bitcoin core bloomfilter/mempool requests. It needs to provide the entire chain of unconfirmed inputs for any matched tx.

**Comment by Logicwax** [comment]
I thought that was the responsibility of the client to update its bloom filter when receiving TX's? (By looking into their inputs, and throwing those hashes onto the bloom filter pile)

**Comment by voisine** [comment]
Yes the wallet adds receive addresses to the bloom filter which gives it any immediate inputs. What it doesn't give you is the inputs of your inputs, or the inputs of the inputs of your inputs. Normally you don't care about them if they're all confirmed, but if a transaction you receive is part of a chain of unconfirmed inputs, then you need to know about that to do things like CPFP calculation.

**Comment by voisine** [comment]
further improvements depend on improved mempool request behavior in core, which is being undertaken by Tom Harding
