### ISSUE TITLE
breadwallet can't find passphrase

### ISSUE THREAD

**Issue by alewijnse** [voisine/breadwallet#308]
I've created a wallet, received funds & then my phone crashed. 

Now I'm trying to enter my passphrase again but breadwallet can't find the passphrase. This means my money is stuck in my old wallet, any tips?

**Comment by voisine** [comment]
This sounds like a support issue. Please contact support@breadwallet.com and we will take care of you.

**Comment by alewijnse** [comment]
Thanks Aaron

**Comment by alewijnse** [comment]
well no, I am still to get my money back...


On Thu, 26 Nov 2015 at 23:56 Aaron Voisine <notifications@github.com> wrote:

> Closed #308 <https://github.com/voisine/breadwallet/issues/308>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/voisine/breadwallet/issues/308#event-475910768>.
>
-- 

Sent from my mobile so please excuse my brevity and typos.

Regards,
Jeroen Alewijnse
