### ISSUE TITLE
Crash on launch

### ISSUE THREAD

**Issue by rantanplan41** [voisine/breadwallet#310]
The app crashed for me today. I supposed the issue could be related to Save Battery mode in iOS. When I turned the save battery mode off, the App worked perfectly again.

**Comment by voisine** [comment]
Does it happen consistently or was it just the one time?

**Comment by rantanplan41** [comment]
Hi,

It has happened before but today I noticed the Battery mode trick. 

Maybe it has something to do with background updating of the blockchain data. 

Just wondering...

Att,
Daniel Herkenhoff
+55 27 98801-1002 (Brasil)
+1 (206) 203-5773 (USA)
http://www.appideias.com
http://www.facebook.com/appideias

Sent from my iPhone 6

0% estado. 0% impostos. 100% Liberdade.

**Comment by voisine** [comment]
@rantanplan41 does the app take a long time to start up? (longer than 10seconds?) If so, I believe this is fixed in github.

**Comment by rantanplan41** [comment]
Yeah! After an undefined number of attempts it runs ok. 

:-)

Att,
Daniel Herkenhoff
+55 27 98801-1002 (Brasil)
+1 (206) 203-5773 (USA)
http://www.appideias.com
http://www.facebook.com/appideias

Sent from my iPhone 6

0% estado. 0% impostos. 100% Liberdade.

**Comment by voisine** [comment]
If you'd like a solution right away, you can email us your iTunes account email address and we can invite you to the testflight beta. We've made a bunch of improvements for people using the app for periodic mining payouts, which was an edge case that revealed some performance problems.

**Comment by rantanplan41** [comment]
Cool. It's danielrhc@mac.com

But I can wait until a new official version is released. 

:-)

Keep up with the good work!

Att,
Daniel Herkenhoff
+55 27 98801-1002 (Brasil)
+1 (206) 203-5773 (USA)
http://www.appideias.com
http://www.facebook.com/appideias

Sent from my iPhone 6

0% estado. 0% impostos. 100% Liberdade.

**Comment by rantanplan41** [comment]
Thanks! It's working perfectly!

Att,
Daniel Herkenhoff
+55 27 98801-1002 (Brasil)
+1 (206) 203-5773 (USA)
http://www.appideias.com
http://www.facebook.com/appideias

Sent from my iPhone 6

0% estado. 0% impostos. 100% Liberdade.
