### ISSUE TITLE
No receive notification when requesting specific amount

### ISSUE THREAD

**Issue by ejhong** [voisine/breadwallet#311]
When you specify an amount to receive in breadwallet, you get a little dialog QR code for showing the payer.  Payer pays and breadwallet in that dialog shows no indication that anything was received.  This is different when you are not on the specific amount dialog - you get a little notification that an amount was received.  A notification should at least pop up until the dialog is closed in this case.  Also need to consider what to do if too little or too much is received.

**Comment by ejhong** [comment]
On test flight version when specifying a receive amount the displayed amount is always zero.

**Comment by voisine** [comment]
Fixed the display amount. Will do a new testflight build after I get a few more fixes in.
