### ISSUE TITLE
Multiple mempool requests?

### ISSUE THREAD

**Issue by gmaxwell** [voisine/breadwallet#313]
Assuming this is actually bread wallet, is there a particular reason that it's making multiple mempool requests after connecting?

2015-11-24 23:25:43 receive version message: /breadwallet:3.0/: version 70002, blocks=0, us=x.x.x.x:8333, peer=121
2015-11-24 23:25:43 sending: ping (8 bytes) peer=121
2015-11-24 23:25:43 received: filterload (634 bytes) peer=121
2015-11-24 23:25:43 received: mempool (0 bytes) peer=121
2015-11-24 23:25:43 received: ping (8 bytes) peer=121
2015-11-24 23:25:43 sending: pong (8 bytes) peer=121
2015-11-24 23:25:43 received: verack (0 bytes) peer=121
2015-11-24 23:25:43 received: pong (8 bytes) peer=121
2015-11-24 23:25:43 received: filterload (634 bytes) peer=121
2015-11-24 23:25:43 received: mempool (0 bytes) peer=121

**Comment by voisine** [comment]
It calls mempool after filterload to see if any new transactions match the filter. I can double check that it's not loading the filter multiple times on each connect, but it can happen on occasion of several bip32 addresses are consumed and a new filter needs to be generated with additional addresses. That should be pretty rare though. Did you just it this one time or is something you're observing more frequently?

**Comment by gmaxwell** [comment]
Just started watching for it, I'm exploring changing how the mempool command works in Bitcoin core in order to suppress some privacy problems and denial of service attacks.  this is the only case I've seen so far.

What I'm looking to do is putting the mempool on a slight quantized time delay to avoid it being used to bypass trickling to track transactions, and making subsequent calls only return things added since the prior call.  Based on your usage it looks like I'll need to reset the prior call time on filterload... Though refiltering the whole mempool is quite computationally expensive, so I hope your design doesn't depend on doing it too often.

**Comment by voisine** [comment]
We generate 100 addresses ahead on the bip32 chain to try to minimize filter updates, and only request the mempool if the filter is reloaded after the chain is fully synced. Also we plan to start running our own nodes to support our users and reduce load on the volunteer p2p network.

**Comment by gmaxwell** [comment]
@voisine Thats fine, I just wanted to make sure you weren't updating it one per address.
