### ISSUE TITLE
Failed transaction broadcast before SPV sync complete

### ISSUE THREAD

**Issue by adamcol** [voisine/breadwallet#314]
When attempting to send a transaction as soon as breadwallet opens, the app appears to send successfully, deduct the balance, and shows the transaction in history. But no transaction is broadcast. The issue appears to be related the SPV sync still in progress when you open the app, especially if days have past since you last opened it.

I understand the SPV sync should be completed before attempting to form a transaction, but breadwallet allows the user to form one and leads the user to believe they have made a successful transaction, when that is not the case. 

I'd recommend either requiring the SPV sync to complete first, or allow the user to build and approve the transaction, then show a loading bar which represents the same remaining SPV sync progress before showing "Sent!".

I'm not capable of creating a pull request to solve this issue, so I apologize for not being more helpful.

**Comment by voisine** [comment]
How were you able to determine that the transaction wasn't broadcast? Was it that you received a "transaction failed" error afterward?

The current code has improved behavior in this area vs the current app store build. If you're interested, email me your iTunes account email address and we can invite you the test flight beta.

**Comment by adamcol** [comment]
The recipient's wallet never detects the transaction. Block explorers don't see it either. Don't receive a "transaction failed" error. 
 
Rescan Blockchain corrects my transaction history immediately and let's me make the transaction correctly.

No worries, love the app, glad it's on your radar and I will just wait for the next public build.
