### ISSUE TITLE
Dealing with a large number of bulky transactions

### ISSUE THREAD

**Issue by jmacwhyte** [voisine/breadwallet#316]
Hey everyone,

Using your breadwallet as a payout address for mining generally means you get a large number of bulky transactions, which can fill up memory quite quickly. A bunch of people reported the app crashing on startup, which was caused by the app blocking while it was loading coredata and eventually getting killed by iOS. Recent updates have fixed that so the app can now startup, but that might not be enough to avoid all problems!

As a "worst case scenario" test, I grabbed a monster mining address: 1CK6KHY6MHgYvmRQ4PAafKYDrg1ejbH1cE

At the time of writing this address has over 5000 transactions, and many are at least 5kb in size. Trying to load up breadwallet with this address causes the app to crash during sync when run on an iPhone. It syncs successfully when run in the simulator, but memory usage tops out around 1.45GB, which is obviously problematic.

I think the simplest solution is to prune all non-essential data from transactions before storing the blob. We can start by eliminating all input and output scripts that aren't related to our wallet, keeping just a couple addresses to display to the user in the transaction list. We can still download the entire list of send and receive addresses when the user selects to view the full details of a particular transaction.

Thoughts?

**Comment by voisine** [comment]
so, 5000 transactions, even if every single one is 5k in size, that still only comes out to 25Mb... Of course the transaction objects in memory are a bit larger than the serialized wire data, since it has things like the addresses instead of only scripts, and some extra object/pointer overhead, so generously it could take up as much as 50Mb... 1.45Gb means something has badly gone wrong somewhere I think.

**Comment by voisine** [comment]
appears to be a case of core data gone wild... but there are some workarounds

**Comment by jmacwhyte** [comment]
It also looks like updateBalance is soaking up a lot of memory, particularly the "spent" object in the line right after "check the entire UTXO set against the entire spent output set". Would it help to limit how often updateBalance is called? (no more than once per second, for example)

**Comment by jmacwhyte** [comment]
I had a feeling the spent object wasn't being cleared up properly, so I tried added an autoreleasepool block. So far memory usage appears to be a lot better! I will let you know how the tests go...

**Comment by voisine** [comment]
with the autoreleasepool additions and using core data context reset after save, I'm calling this fixed. In our worst case mining wallet, the peak memory usage is a few hundred megs.
