### ISSUE TITLE
crashes, coin loss, currency change to default...

### ISSUE THREAD

**Issue by weirdotaz** [voisine/breadwallet#319]
i have breadwallet for a few months now and recently i was getting dificulty accessing it. it was crashing on start after a 20secs timeout on load screen. i saved my recovery passphrase, reinstalled the app and recovered my wallet. crash issue was resolved but only retrieved data for the last few days
also, currency keeps changing to GBP (default) after i select EUR as my currency (not that important, just thought i should mention it)
i'm re-scanning my blockchain again now but still only have the data for the last 4 days instead of 3 months...

EDIT: using iOS 9.1 on iPhone 5S

**Comment by voisine** [comment]
Are you by chance using breadwallet for mining payouts? I've recently made a lot of improvements to handle this use case better both for app launch speed and sync performance. Would you be interested in joining the TestFlight beta? Is so, email me your iTunes account email address and we'll invite you.

**Comment by weirdotaz** [comment]
im using breadwallet for daily cloud-mining payments and it was working perfectly. then i got the load crashes and now i'm worried i lost it's content. i can see in the service i hired that the payouts are being made and the address of the wallet. so im not sure what's missing. yes i would be interested in the testflight beta, where do i sign in?
