### ISSUE TITLE
TouchID UX

### ISSUE THREAD

**Issue by Logicwax** [voisine/breadwallet#321]
Tapping on the top lock button, scanning my TouchID (to see my balance), and then again having to scan my touchID again to send a transaction can get annoying.

I honestly don't care if someone can read my wallet ballance, because my phone is locked with my TouchID anyway.   Many banking apps take this approach.....they will only stay logged in between app reboots if and only if the phone is auto-locked with TouchID.   Why can't Breadwallet?

Most people I see using Breadwallet who are new to Bitcoin, I see them have a problem remembering to scan their finger just to see their balance (when they just scanned it to unlock the phone).   I'd like to recommend that Breadwallet shows the balance by default (if the phone is globally locked by TouchID).   Many other banking apps take this approach.   As an alternative, how about making it only scan the TouchID during initial boot of the app, and only then (allowing transactions to go without).

I'm fine with keeping TouchID for each transaction send, but a separate scan just to see the balance seems a little too much.

**Comment by voisine** [comment]
@Logicwax the app used to show your balance once you unlocked the app, but people complained that they wanted to keep it private when they were presenting their QR code to receive funds. With a banking app you don't need to show your screen to anyone to receive money, so showing the balance be default is less problematic.

**Comment by Logicwax** [comment]
well, how about swiping over to the QR-code screen, would simply hide the balance?

**Comment by voisine** [comment]
That's possible, but right now you can loan your phone to someone and they can't just launch the app to see your balance. This is the same for every banking app that I've used, you need touch id or login to see balances.
