### ISSUE TITLE
Opening Bread Wallet

### ISSUE THREAD

**Issue by ekuehne** [voisine/breadwallet#327]
I have had bread wallet for a year or so. Today I tried to open bread wallet and it is asking for a 4 digit passcode.  I tried the passcodes for my iphone and the screen locks.  In the past, I have been able to open with a thumb print.  It says that I have 5 more attempts and I am sure nothing good happens after I use all of my attempts.  Not sure what the fix is....  Any help would be appreciated.  Thanks

**Comment by dabura667** [comment]
> I have been able to open with a thumb print

When you first started the wallet, it asked you to set a 4 digit PIN.

After this PIN was set, you then could set touchID (thumb print) from the settings menu.

However, the PIN was still there the whole time, it was just hidden from you because you used thumb print.

For some reason, your app forgot you're using thumb print and asked for your PIN, which I am guessing you forgot... You can not re-enable touchID without entering your PIN...

**Comment by ekuehne** [comment]
I have the original pin.  However, when I put the pin, the app locks up and the only way to get past is to close the app.  Every time I have tried it takes away one of my attempts and I only have a couple left.  Not sure what to do…

**Comment by voisine** [comment]
@ekuehne if you have your recovery phrase, you can always recover your funds. If you didn't write it down, please make an iTunes backup of your phone before any more passcode attempts.

After you ensure you have the phrase or an iTunes backup of your phone, then try deleting and reinstalling the app. Your wallet will not be deleted, however I haven't been able to observe the passcode freeze bug so I'm not completely certain this will fix it, and it could just end up losing another attempt.

The app now asks you to reenter your passcode one time (and again if the app is deleted/reinstalled) to ensure you have it. We had problems where people installed the app, selected a passcode, deleted the app, waited a year, reinstalled, and had no idea what their passcode or recovery phrase was.

**Comment by ekuehne** [comment]
I ended up having to delete and reinstall the app.  I did have my recovery phrase, so that was not a problem.  The “synching” took a long time for the first couple of days – 15 minutes minimum.  However, everything appears to working fine now and synching is down to a few seconds.

Eric

**Comment by calvinl** [comment]
I just had this exact same issue. I remember not having used breadwallet for awhile, and then updating the app not too long ago when it was in the app store. Tried getting into my wallet this morning and the app kept freezing up on me after putting in my PIN.

**Comment by voisine** [comment]
The app freezing issue is fixed with https://github.com/voisine/breadwallet/commit/7e1e866768bf72f161e752a23965a2c2ba633d00

If you're not able to open the app, contact support@breadwallet.com with your iTunes email and we can get you a testflight build with the fix.
