### ISSUE TITLE
Your point about tapping the receive address to copy it being too cryptic is well taken.

### ISSUE THREAD

**Issue by Transisto** [voisine/breadwallet#331]
I'm just so totally fed up to be receiving screenshots of QR codes instead of addresses. It make my job of selling bitcoin so much harder.  I'd say about 15% of our customer can't figure that one out and half of those I can't even manage to explain them.  

Hitting onto a plain piece of text to expect something to happen is just NOT intuitive !

In reference to one of the annoyance listed in this issue : https://github.com/voisine/breadwallet/issues/299

**Comment by voisine** [comment]
We color it blue to make it look clickable, but I guess that's not obvious enough. Also tapping the QR gives you a tip bubble explaining you can tap it, except nobody reads it. :(

**Comment by Transisto** [comment]
The whole receive page is so empty it could fit on an iwatch I Don't
understand why this sub menu is not there already without an extra action.

**Comment by dabura667** [comment]
@voisine to be honest, I think @Transisto is right on this point.

"Blue text = clickable link" is a trope that only computer users would get. If the target audience is supposed to be grandma and the tech illiterate, the UI cues need to not rely on "computer literate" tropes.

Perhaps turning the address text into a flushed button with "tap" written on the right side. (The button template for the send screen can be used I think.)

However, I do think @Transisto will have trouble no matter how you make the UI.
I guarantee you there are some people who will just always not understand anything.

In general, I think that complex UIs with lots of buttons are easier to explain and easier to understand when someone is holding your hand, but are also easy to forget how to use after leaving the person that explained it to you.

On the other hand, simple intuitive UIs are easier to understand intuitively, so when grandma picks it up 6 months later, when she's undoubtedly forgotten any explanations given to her, we should strive for an app that is just as easy to use 6 months later as it is the day they install it.

**Comment by samuraisam** [comment]
Our next UX refresh addresses this issue

**Comment by Transisto** [comment]
I've seen a few update passing by, ETA ?
