### ISSUE TITLE
App sometimes gets stuck during sync

### ISSUE THREAD

**Issue by chris41188** [voisine/breadwallet#332]
I have the latest version of breadwallet installed and the app fails to sync, the percentage is 0.0% and seems to flick around the same block.

force closing the app and pressing the resync button doest help the issue, however deleting and reinstalling the app fixed the issue

**Comment by voisine** [comment]
This is fixed with https://github.com/voisine/breadwallet/commit/10c17deb69841ecbe101efe16fc5d5cc6033b003
