### ISSUE TITLE
Touch ID

### ISSUE THREAD

**Issue by Stoney310** [voisine/breadwallet#333]
Every time I try to use the bread wallet app to pay it asks for touch ID or cancel. I do not have a touch ID. I try putting my finger on it and it does absolutely nothing.

**Comment by voisine** [comment]
Do you mean you disabled touch ID for the phone?

When you hit cancel, is there an option labeled "passcode" ?

**Comment by Stoney310** [comment]
I have touch ID for my iPhone but I never use it. No, there is no option for the passcode

**Comment by Stoney310** [comment]
No, it doesn't say for my phone it just comes up as touch id in the app.
And I don't get an option for passcode when I hit cancel.

**Comment by Stoney310** [comment]
I am getting really frustrated...I'm trying to use the app to make a
payment and I can't figure out anyway to make it work.

**Comment by Stoney310** [comment]
I paid $100 into my acct that I have no access to

**Comment by voisine** [comment]
If you need immediate support, please contact support@breadwallet.com.

Once in a while I've encountered iOS touch id bugs that were fixed by powering off the phone and back on again.

**Comment by Stoney310** [comment]
I disabled the touch id on my phone and it worked finally. How long does it
take to pay?

**Comment by voisine** [comment]
Bitcoin payments take only a few seconds. They are then confirmed by the bitcoin network and become irreversible usually within several minutes.

**Comment by Stoney310** [comment]
It must still be confirming it says 0 confirmations right now.
