### ISSUE TITLE
Breadwallet Transaction says I have sent Negative value of Bitcoin (V/Urgent)

### ISSUE THREAD

**Issue by joeybz** [voisine/breadwallet#334]
Hi there, this is the first time I have put breadwallet into practice by purchasing my first amounts of bitcoin today. The process on receiving the bitcoins to the breadwallet app on my phone was okay, however I have been having problems transferring the bitcoin over to Bitcoin Core on my laptop. I found out that my full transactions havent yet showed up on Bitcoin core due to the synchronization of the network, and i understand this takes some time so I am happy to wait, but... when i checked the transaction on breadwallet it has said that I have transferred an amount of  b-380,000...

The amount I wanted to transfer was positive (of course) b380,000. It has said that the transaction has sent but says it in a red text. I am a bit worried now because I am unsure if whether or not I have lost this money. Very urgent, please help.

Ps I have included this picture of the problem:
![img_3395](https://cloud.githubusercontent.com/assets/16612418/12202673/ef67abf6-b622-11e5-9883-03b97ffedd7e.PNG)

**Comment by joeybz** [comment]
oh and also I have rescanned the chain... multiple times. Still no progression or reassurance of the matter.

**Comment by voisine** [comment]
Looks correct to me. You received b381,000, then sent it out again. +b381,000, -b381,000, final balance in the wallet 0.

**Comment by joeybz** [comment]
Fantastic. Thanks a lot! Wasn't too sure, but thanks for the reassurance.
