### ISSUE TITLE
Compatible HD Import / Export

### ISSUE THREAD

**Issue by akvadrako** [voisine/breadwallet#335]
Hello - I like bread wallet but it would be nice if there was a way to import my pass phrase in aother system and have it see all my accounts. It's hard to understand the whole picture, but I think supporting PIP44 would allow this compatibility.

In any case, this would be a nice feature for bread wallet to have.

Thanks!

**Comment by voisine** [comment]
breadwallet uses industry standard BIP32 with the "default" wallet structure it describes, along with the BIP39 mnemonic standard which I co-authored. A breadwallet recovery phrase will work with any wallet that supports these standards. (however we strongly recommend against ever typing your recovery phrase into other devices or wallets, as they are not built to the same security standards)

dup of #131
