### ISSUE TITLE
Wondering how Fee per KB is determined?

### ISSUE THREAD

**Issue by losh11** [voisine/breadwallet#336]
All I see is that fee per KB is gotten from https://api.breadwallet.com/fee-per-kb - but how do you do this?
Also doesn't that mean that this is a point of failure if the web server calculating that is broken?

**Comment by samuraisam** [comment]
We determine manually at this time, but may at some point make this responsive. Manually updating the fee has been "good enough" for us.

The app will continue to function without _any_ server required. All server integrations that exist now or in the future will remain completely optional to the core wallet functionality.

**Comment by voisine** [comment]
to add to @samuraisam's point, the fee-per-kb api endpoint is only intended for temporary use in a emergency if the fee needs to be bumped in the face of rapidly changing network conditions, while an update is navigating the app store review process.

**Comment by losh11** [comment]
Got it. But how is it determined on the server?

**Comment by samuraisam** [comment]
It is manually set by a knowledgable human.

**Comment by voisine** [comment]
At the moment it's set to the same value that the wallet uses in the absence of the api. It's the new bitcoin-core default minimum relay fee of 5000 satoshis per kb, rounded up to the nearest whole kb, applied to the smallest one input, one output tx (191bytes), rounded up. So (5000*1000 + 190)/191, or 26179 satoshis per kb. This way any breadwallet transaction will beat the fee-per-kb rate of the smallest possible tx using the default minimum relay fee. This currently is getting confirmations consistently within about 2 or 3 blocks on average.

**Comment by losh11** [comment]
*knowledgable*

right...

**Comment by losh11** [comment]
That's @voisine that's all I wanted to know. :+1:

**Comment by voisine** [comment]
Also the wallet will take the fee-per-kb rate, then round up the result to the nearest 1000 satoshis (10 bits), or if the resulting change output is less than the minimum dust output, it will just add it to the fee instead.

**Comment by Logicwax** [comment]
is there a way Breadwallet could examine a few random transactions in the most recent blocks and determine an average of what fee's are needed to get into the block?  That way it won't need to rely on a 3rd party server in order to function.

**Comment by dabura667** [comment]
> is there a way Breadwallet could examine a few random transactions in the most recent blocks and determine an average of what fee's are needed to get into the block? That way it won't need to rely on a 3rd party server in order to function.

This is highly unreliable without downloading megabytes worth of transactions from the last 20-30 blocks.

Face it. Bitcoin fees are broken.
