### ISSUE TITLE
Transaction still unverified after almost 20 hours

### ISSUE THREAD

**Issue by grumpyoledoinshead** [voisine/breadwallet#337]
I tried to send a payment of 0.5 BTC from my Breadwallet last night and it's still unverified. I have made transfers using Breadwallet before without any problem and am a bit concerned about this especially as it's not a small transaction.  I did have trouble as the transfer failed the first couple of attempts.  Please help!

**Comment by voisine** [comment]
When you say the transfer failed, how was that apparent? Did you get an error message? If so, what was the exact message?

If you contact support@breadwallet.com with the transaction id, we can also investigate further if you prefer not to post it publicly.

**Comment by grumpyoledoinshead** [comment]
Thank you, I've just emailed as suggested
