### ISSUE TITLE
Many users get stuck at swiping left/right to receive their bitcoin.

### ISSUE THREAD

**Issue by Transisto** [voisine/breadwallet#338]
I don't care if the tiny dot make it obvious to you. I see it almost everyday. I'm giving them time to see if they can figure it out the left/right thing. But no, if they haven't read the instructions at first it seems like they'll never figure it out.

There are so many better options than this cryptic dot, I don't even feel like suggesting one.

**Comment by voisine** [comment]
We've done a fair bit of observing new users, and so far between the dots that every iOS user is familiar with, and the tip bubble tutorial on first launch, haven't yet come across someone who was confused.

I will have the app swipe to the right automatically to show the action when you launch the app but have zero balance.

**Comment by Transisto** [comment]
Thanks, every bit helps.

Our average customer is really not tech saavy.

**Comment by voisine** [comment]
Right, it does complete the new wallet tip tutorial on the receive screen for that reason, and at some point in the past it also would autoswipe over to receive if the wallet was empty. Not sure when that got taken out, might have been inadvertent.

**Comment by samuraisam** [comment]
Future versions will improve upon this design, giving users easier discoverability while retaining the ease of use and speed of Aaron's original vision.
