### ISSUE TITLE
how to export wallet.dat (private key)?

### ISSUE THREAD

**Issue by fyears** [voisine/breadwallet#340]
Hi,

I am new to Bitcoin, and I am using breadwallet to create a completely new wallet. (So my question may seem to be silly...)

Now I have a auto-generated 12-words "recovery phrase" and 4-digits "passcode", and of course the bitcoin public address for receiving money.

So, how should I export the `wallet.dat` / private key (it seems that it's the most important information for the wallet), so that I could manage / use my wallet **on other applications, websites**, like https://blockchain.info/wallet/import-wallet , etc?

Thank you.

**Comment by voisine** [comment]
Your 12 word recovery phrase is the equivalent of the wallet.dat file in bitcoin-core. Never type your recovery phrase into other devices or wallets. It must remain secret and they are not built to the same security standards. Anyone who knows it can spend your funds. Web based wallets in particular are notoriously insecure.

**Comment by fyears** [comment]
What protocol does it follow? [BIP-39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki)?

**Comment by voisine** [comment]
Yes, it is BIP39, and uses the default BIP32 wallet layout.

**Comment by TheQL** [comment]
Is there a simple way of generating a Bitcoin-Core compatible wallet.dat via the recovery phrase?

**Comment by dabura667** [comment]
> Is there a simple way/tool of generating a Bitcoin-Core compatible wallet.dat via the recovery phrase?

No. These are not compatible. You could extract a limited number of keys from the unlimited pool of the recovery phrase (bitcoin-core is limited) and save it in a wallet.dat format...

But no one sees the use in such a tool, and therefore it has not been made.

**Comment by TheQL** [comment]
Ok, I see that this might not be useful, but I assume I can export all my private keys before for instance dropping the app and switching to another?

**Comment by voisine** [comment]
There are several other wallet apps that support bip39 recovery phrase with the default bip32 wallet layout, same as breadwallet uses.

**Comment by woeisme** [comment]
What is the easiest way to transfer my breadwallet balance to another wallet (say bitcoin core) without sending. As in a offline key export > new wallet import.

**Comment by vx28643** [comment]
Personally I don't know of another wallet that easily accepts the bip39 breadwallet recovery phrase and would appreciate knowing which apps @vosine was referring to. I am a regular user of breadwallet but occasionally I need more functions available on my breadwallet addresses.

---

Just my personal recent experience of transferring my breadwallet balance to another wallet.. I used https://github.com/iancoleman/bip39/blob/master/bip39-standalone.html *running offline* to generate the private keys which I could then import manually into another wallet. I could have been saved the work if breadwallet allowed exporting of individual private keys (I needed them to sign/prove ownership of an address).

**Comment by bigdisk** [comment]
Breadwallet doesn't support custom fees. It asks for **4.99 USD** fee right now, making it unusable to move small amount of coins.

I would love a custom fee feature, so that I could set lower fees (and wait longer), and set trx as replaceable. In the meantime, my coins are stucked on Breadwallet, as Breadwallet doesn't **either** have an export key functions.

Tried to use the recovery phrase in electrum as a BIP39 12 word seed and all I see is an empty wallet. @voisine What other wallet that allows custom fees could I use my seed with?

**Comment by cornedor** [comment]
@vx28643 can you share what you used for BIP32 Derivation Path? m/0h/0 isn't a valid.

**Comment by Saturnix** [comment]
@cornedor 3 months ago, derivation path was m/0'/0 and "m/0'/1 for change addresses. Don't know if that changed.

**Comment by vx28643** [comment]
Imported directly into Electrum today using path ```m/0'```, following instructions given in #463
