### ISSUE TITLE
What is the path scheme?

### ISSUE THREAD

**Issue by rvanegas** [voisine/breadwallet#341]
I am able to derive what appear to be used key pairs from the 12 word mnemonic using bip32/39 code I've found elsewhere. Specifically, I found a used address at "m/0'/0/0" and also "m/0'/1/0" and "m/0'/1/1". But I know there are many more used addresses, and wasn't able to find them at "m/0'/0/1", "m/0'/0/2", etc. Where are they exactly? What is the scheme by which Breadwallet selects key pairs to use? I tried to understand what's going on in "BRBIP32Sequence.m" but admit it's over my head.

I am trying to write a little Javascript to sweep a set of addresses Breadwallet uses for a specific bip39 mnemonic. Why not just use Breadwallet to empty the wallet directly? Because it is failing. I am getting transaction rejection errors and seeing incorrectly doubled balances and positive balances for addresses that should be empty. I tried rescanning and also re-installing app, but the problems persist.

**Comment by dabura667** [comment]
breadwallet only shows new addresses when it actually detects a new transaction.

so keep checkig addresses m/0'/0/x incrementing x by 1 until you find any address with no history. Then stop.

Then do the same with m/0'/1/x

That is your entire breadwallet balance.

Other wallets use different address deriving rules they follow, but if you've only used breadwallet, what I said should show you your entire balance.

**Comment by dabura667** [comment]
Please note I said history, not balance

**Comment by rvanegas** [comment]
That worked, thank you. So now that I've recovered the funds, I am wondering what ever happened to Breadwallet!
