### ISSUE TITLE
I sent my money to wrong address on breadwallt!

### ISSUE THREAD

**Issue by ktetetet** [voisine/breadwallet#343]
Hi 
I was so stupid.. so I sent b0.09301629 to 1HHq1Y7ViZb1G4HhhyUedj58HsDaVraMmq
but It wasn't the address please cancel the transaction and give my money back :/

transaction id : 191411e4e7e75a47eba9ab9e33a692a8f21115c70fbeff8062c87975ba31e513

my money is in wrong wallet please help!!!

oh my wallet address in breadwallet is "16pDw3atvbxZCyRidV9wQ3mAXoCv6Tq5gT".

**Comment by dabura667** [comment]
So I just want to be sure... your address is 16pDw3atvbxZCyRidV9wQ3mAXoCv6Tq5gT... correct?

**Comment by ktetetet** [comment]
exactly!

2016-01-24 21:23 GMT+09:00 Dabura667 <notifications@github.com>:

**Comment by voisine** [comment]
This looks like a support issue. Contact support@bredwallet.com and we will take care of you!
