### ISSUE TITLE
Ability to recover a wallet using private key (not importing)

### ISSUE THREAD

**Issue by aviadoffer** [voisine/breadwallet#344]
I have an old wallet which I don't wish to replace with the generated wallet on the breadwallet.
I wish to recover that wallet using private key and not via recovery phrase

**Comment by aviadoffer** [comment]
Sorry this is an enhancement request

**Comment by voisine** [comment]
Breadwallet is a deterministic wallet. Single address wallets are not recommended for privacy reasons. 

Also importing a key not derived from your wallet seed without sweeping the balance would mean that you can no longer recover your wallet from just the seed

**Comment by aviadoffer** [comment]
I understand but how would one have access to the same wallet through breadwallet and Bitcoin core and/or Electrum on a pc?
When I'm home I want to use the PC wallet. When I'm on the road I want to use breadwallet. 
Kindly advise how to achieve it ?

**Comment by voisine** [comment]
Desktop wallets are not recommended for people who aren't security experts. They are not hardened agaisnt malware by default. People typically even use the same machine for general web browsing and email.

You should only hold Bitcoin private key material on secure devices like dedicated hardware wallets or iOS devices.

**Comment by aviadoffer** [comment]
OK, please suggest a way to pay via a PC and via BreadWallet.
If my phone dies and I need to transfer money now I need an option.
Please suggest a way.

**Comment by voisine** [comment]
You can charge your phone, get a second iOS device, or get a dedicated hardware wallet. A PC is not a suitable device for storing sensitive private key material as it is vulnerable to malware.

**Comment by aviadoffer** [comment]
Thanks. I will digest it overtime I guess.
