### ISSUE TITLE
Request for BTC settings vs Satoshi

### ISSUE THREAD

**Issue by aviadoffer** [voisine/breadwallet#345]
I think people with enough coins would rather specify and view amounts in BTC and not Satoshi.
I would be nice if one can configure it via settings.
This is enhancement request

**Comment by voisine** [comment]
Breadwallet uses micro-btc (bits), not satoshis. 1,000,000bits = 1btc, so you can just look at the number preceding the second comma to see how many whole btc you have.

Dupe of #299
