### ISSUE TITLE
How do one changes to BTC display?

### ISSUE THREAD

**Issue by loachjohn** [voisine/breadwallet#346]
I can't find the option, maybe issue with my phone (it's older)

**Comment by jprichardson** [comment]
@loachjohn see: https://github.com/voisine/breadwallet/issues/299 for discussion.

**Comment by loachjohn** [comment]
Thanks for the rapid answer. Does that mean there is no option and never will be ? bummer
Back to my old app I guess.

**Comment by voisine** [comment]
@loachjohn what was is your old app? breadwallet connects directly to the bitcoin network rather than relying on and trusting a wallet provider's server like most others.

**Comment by loachjohn** [comment]
It's coinbase app for iphone 5. I know it's security is bad but it shows in a format I need. thank you.

**Comment by voisine** [comment]
We have a good relationship with coinbase and hope to get them to use bits/uBTC as the default soon!
