### ISSUE TITLE
Transaction fee too high

### ISSUE THREAD

**Issue by BTCAustralia** [voisine/breadwallet#348]
Today I sent bitcoins using Breadwallet and the bitcoin network fee was approximately 0.02 btc. I have not given the exact transaction ID or amount here to keep my wallet address anonymous. The transaction did not have a particularly large (under 1000 bytes). There was a large number of unconfirmed transactions on the network however I had sent another transaction a few minutes earlier which did not have a large fee attached and was confirmed in the same block.

I only realised the fee was this large after I accepted. In future I will check this more thoroughly.

Perhaps a limit could be placed on the fee. For example 0.001 btc would be more than enough for any transaction that Breadwallet would handle and would just serve as an upper limit.

**Comment by voisine** [comment]
You can contact support@breadwallet.com if you'd like to share the txid privately so we can investigate further. With a fee like that, the most likely explanation is that you were spending an unconfirmed receive which itself was large. Was that the case? When spending unconfirmed receives, breadwallet pays extra fees to make sure your tx doesn't get stuck if the receive didn't pay enough fees.
