### ISSUE TITLE
Sending payments issue

### ISSUE THREAD

**Issue by lave21** [voisine/breadwallet#350]
Yesterday I sent several payments to a website via my bread wallet, the money left my wallet but was never received by the website.

I used the mycelium wallet app on my cell phone to send the money when I realized bread wallet wasn't working - and it was received with no issue. How do I, at least, get the money back in my wallet?

What is my recourse?

**Comment by voisine** [comment]
Contact support@breadwallet.com and we will take care of you!

Funds are secure on the Bitcoin network so no worries about loss.
