### ISSUE TITLE
breadwallet does not respect BIP111 NODE_BLOOM service bit

### ISSUE THREAD

**Issue by jameshilliard** [voisine/breadwallet#352]
I'm seeing connection attempts in my bitcoind logs from breadwallet peers even though I have NODE_BLOOM set to disabled, starting in bitcoin core version 0.12 bloom filters can be disabled as they are a potential DoS vector and waste resources for high availability nodes such as pool nodes. The option peerbloomfilters=0 in bitcoin.conf for bitcoind sets the NODE_BLOOM service bit to disabled and enforcenodebloom=1 will force disconnect any nodes that attempt to use bloom filters. [BIP111](https://github.com/bitcoin/bips/blob/master/bip-0111.mediawiki) has more details on how support for the service bit should be implemented. Nodes with protocol version 70011 or higher and with the service bit set to disabled should be assumed to not allow bloom filters and breadwallet should not make requests to them.

**Comment by voisine** [comment]
breadwallet advertises protocol version 70002, and sets the relay byte to 0 (indicating SPV) in the version message it sends during handshake, so nodes can safely disconnect immediately, but we will add BIP111 support for the next release.

**Comment by voisine** [comment]
implemented by ea49c4e
