### ISSUE TITLE
Breadwallet for faircoin

### ISSUE THREAD

**Issue by XaviP** [voisine/breadwallet#356]
We're trying to adapt breadwallet for faircoin. Can you guide us about how can we fork it with new parameters and requirements? This is list of faircoin parameters:
https://fair.coop/docs/faircoin-development-notes
Any comment or help would be appreciated.
Thanks.

Edit: ok, we've found the reddcoin fork that show us how to change the parameters.
https://github.com/reddcoin-project/breadwallet/commit/f0c8e54dc59cb691a2ce7128df592b3625e8d9b9
and some more...

**Comment by jmacwhyte** [comment]
@voisine Let's close this one.

**Comment by XaviP** [comment]
Closing. We're working in that, if any issue we'll reopen it.
