### ISSUE TITLE
Transaction can succeed even though it says fail

### ISSUE THREAD

**Issue by FuzzyHobbit** [voisine/breadwallet#358]
I believe it's related to Touch ID, but it doesn't happen every time.

**Comment by voisine** [comment]
Can you explain in more detail what happened? Did you get a dialog box saying the transaction failed and then it went through?

**Comment by FuzzyHobbit** [comment]
I scan a QR code, followed by using Touch ID, then receive a failure message, but viewing the transaction history would sometimes show that it actually did go through. Before realizing what was happening, I would send the bitcoin a second time, meaning I paid twice.

A post on Reddit: [PSA: Mycelium iOS sends even when it appears failed, cost me $1k](https://www.reddit.com/r/Bitcoin/comments/4cfw6t/psa_mycelium_ios_sends_even_when_it_appears/) is why I thought it was Touch ID related. I have not run into the issue when sending with a password.

**Comment by voisine** [comment]
I don't think Touch ID has anything to do with it, other than maybe because of timing. Do you see the failure message immediately or after several seconds? I wonder if there is an edge case when you authorize the transaction before it has a chance to connect to any nodes on the network.

**Comment by FuzzyHobbit** [comment]
I agree that it is related to timing, as it will sometimes display an error message about the network too. It seems if the wallet is given more time to connect to the network, before scanning the QR code, the problem goes away.
