### ISSUE TITLE
Transaction Rejected - Randomly for no reason while transaction actually is valid

### ISSUE THREAD

**Issue by karek314** [voisine/breadwallet#359]
Im experiencing weird issue with Breadwallet, im running breadwallet 0.5.4 from AppStore. I have made over 150 transactions with this particular wallet. And very often transactions get rejected, but actually those transactions are valid on the network, even when transactions get confirmed wallet still sees them as invalid. I have tried multiple rescanning (it fixes but it's annoying to do that 3/4 per wallet usage), i have also tried to recreate wallet from passphrase but it gives the same effect as rescanning. Sometimes it happens just after transaction has been made, sometimes it happens after minute or more

**Comment by voisine** [comment]
We've had a handful of reports similar to this, but haven't yet been able to observe it ourselves. If we can get you on the testflight beta we have a version of the app with some extra logging that will help us reproduce the issue on our end.

Can you send me your itunes account email address so we can get you on the testflight beta? My email is in the LICENSE file, or you can send it to support@breadwallet.com

**Comment by karek314** [comment]
Sent :)

**Comment by kode54** [comment]
Also sent. I need to file a separate request as well.

**Comment by karek314** [comment]
I have made quick workaround for myself by pointing wallet to my private full node server.

**Comment by ffxsam** [comment]
I'm having this issue too. Transferred some BTC to another wallet, and now BreadWallet says "unverified".. if I tap on it, I get the error about transaction rejected, and then it disappears.

**Comment by voisine** [comment]
This is resolved by f37d19c

**Comment by ffxsam** [comment]
@voisine Nice - when approximately will this fix go live?

**Comment by ffxsam** [comment]
Ah, never mind! :)

![from skitch](https://cloud.githubusercontent.com/assets/12532733/15310275/2c6f4410-1ba3-11e6-90de-d1afb253e6ac.png)
