### ISSUE TITLE
having trouble generating the addresses using seed and bip39 protocol

### ISSUE THREAD

**Issue by bitcoinsSG** [voisine/breadwallet#360]
Tried to generate the pubkey hashes using the 12 word mnemonic and this tool https://github.com/dcpos/bip39. Please provide clarification in implementation and variables/values needed to replicate wallet pubkeyhash/privatekey generation. thanks.

**Comment by voisine** [comment]
breadwallet uses the default wallet layout described in BIP32, and referenced in BIP43 as purpose 0'

the path is m/0h/0/* for receive addresses and m/0h/1/* for change addresses

If you use a web or desktop tool with your recovery phrase, be aware that desktop systems are not hardened against malware like dedicated hardware wallets and iOS devices. Also if you generate an xpub, treat it as secret. Your wallet security and privacy is reduced to the same as a single address wallet for anyone who knows your xpub. (i.e. a single private key leak along with your xpub exposes your entire wallet balance)
