### ISSUE TITLE
Opsec enhancement 

### ISSUE THREAD

**Issue by matt411** [voisine/breadwallet#365]
Although the app discourages taking screenshots I was in a bind at the Apple Store and had no choice but to take one... I believe that it would be safer if the name of the of the app was hidden when the pass phrase is displayed, so that if the screenshot does 
become visible to someone other than the wallets owner,  the person that sees it won't know exactly where to go with it.

**Comment by voisine** [comment]
Yikes, screenshots are visible to other apps and are probably synced to iCloud... I'm picturing it scrolling scrolling across your Apple TV in screensaver mode. Apple Store employees are helpful, I'm shure one of them would have lent you a pen.

**Comment by dabura667** [comment]
> the person that sees it won't know exactly where to go with it.

They won't need to. breadwallet uses BIP39 which is a standard way of turning words into bitcoin wallets. No one needs to know it's from breadwallet.
