### ISSUE TITLE
iOS TouchID no longer working

### ISSUE THREAD

**Issue by hubba9** [voisine/breadwallet#366]
I've managed to lose my pin and recovery phrase for my wallet which contains coins I can't get access to. I had it set up to use my TouchID which has been working fine until I thought I really should access the recovery phrase and write it down again. This action prompted me for the pin which I wasn't expecting. I'm now on 9/10 of failed pin attempts and in a bit of a bind. TouchID appears to disable itself when you try to access something that requires your pin. 

These is no warning of this and I'm sure I'm not the only person that relies on TouchID. Is there any way to enable the TouchID again without knowing the recovery phrase or pin ?

**Comment by dabura667** [comment]
Nope.

Touch ID is not a replacement for your PIN. The same exact thing goes for iPhone. Sometimes the phone says "nope, put your password / PIN in"

contact breadwallet support and they will help you 1 on 1

**Comment by voisine** [comment]
This looks like a support issue. Don't make any more passcode attempts until you make an iTunes backup of your phone, and contact support@breadwallet.com

**Comment by voisine** [comment]
Since touchid can be defeated with the fake finger attack, we have a touchid spending limit. Once you reach the limit (cumulative) you have to reenter the passcode, or if you do anything like try to change your passcode or view your recovery phrase.
