### ISSUE TITLE
Transaction with status "unverified" for more than 24 hours

### ISSUE THREAD

**Issue by viciousvex** [voisine/breadwallet#367]
Hello everyone,

yesterday I wanted to send some bitcoins with breadwallet v0.5.4 on a non-jailbroken IOS 9.3.1 iPhone 5s. I did not change the transaction fee and just picked the default of 177 bits for a 3.282.992 bits transaction (ID d4419e3be294e6267383a52e0a6b972a3109035973d0c745f5c99bb72530a67b). Whenever I open the transaction details dialog, the "status" of the transaction keeps changing.

I have seen stuff like "1 of 2", "2 of 2", "0 of 3", "2 of 3" there. I've also tried to rescan the blockchain several times, but the transaction is still stuck.

I really don't know if that is a client issue or a Bitcoin confirmation/fee issue. Maybe there is a way to cancel the transaction and resend with a higher fee or some other ideas on how to solve this.

Thanks in advance!

**Comment by voisine** [comment]
Sorry for the late response. If you're still having an issue, please contact support@breadwallet.com. This issue is fixed by commit f37d19c, which will be pushed the app store soon.
