### ISSUE TITLE
Export Private Key

### ISSUE THREAD

**Issue by m4x555** [voisine/breadwallet#376]
Hello!

I used bitcoin adress from breadwallet for funding project-decorum Crowdsale (ICO) 
http://www.project-decorum.com/crowdsale/

I received PDC coins to this bitcoin address, but I do not see them  in breadwallet of course
OmniProtocol Properties (coins) work with any Bitcoin address where you control the private key.
To use PDC coins I need to export private key to Omniwallet  https://www.omniwallet.org/
It possible in several formats (hex, base64, Wallet Import Format, Wallet Import Format Compressed)

I am trying to convert 12 words phrase from breadwallet  in bip 39 mnemonic using Mnemonic Code Converter into Private Key (WIF)
http://anaoum.github.io/trezor-recovery/

I use this Derivation path 
m/0'/0/0

But that's not works for me. I tried different options, but I received addreses with zero balances

What is going wrong?

**Comment by dabura667** [comment]
What is your language? Is the phrase in English?

Some problems that might happen:

1. the address was not your first. try m/0'/0/1 m/0'/0/2 m/0'/0/3 etc. until you find the right address.
2. your phrase is not English. (it looks like the tool in the site does not handle non-English phrases well, try using my tool @ https://bip32jp.github.io/english/ (The site is similar, but it actually handles non-English phrases properly.)

**Comment by m4x555** [comment]
Thank you dabura667!  First solution worked for me.

**Comment by voisine** [comment]
Yes @dabura667 has it right. Please don't use your wallet to store more than pocket change now that your recovery phrase has been exposed to a non-malware hardened device.
