### ISSUE TITLE
ETH

### ISSUE THREAD

**Issue by nontimeomori** [voisine/breadwallet#390]
I know breadwallet has the purpose of furthering the adoption and use of bitcoin. Many people, myself included, now trade in both BTC and ETH. Has any consideration been made to include ETH support. Although I love breadwallet, I have switched to Jaxx because of this. 

Thanks.

**Comment by voisine** [comment]
We don't have any plans for that, but I'd be happy to see someone do an ETH fork. There are already forks for several other alt-coins.

Personally I don't have confidence that any alts will have long term staying power. Money is the strongest network effect there is, so a winner-take-all type outcome is inevitable. Everyone wants to hold what everyone else wants to hold. Why else would people want green paper with numbers on it for instance?

**Comment by askari01** [comment]
I was here to ask for ETH support, but I guess I should invest in solving other bugs and enhancements at hand. ETH is good but dont know if it would survive or not.
