### ISSUE TITLE
Enable HSTS Preload in breadwallet.com domain to avoid MITM attacks

### ISSUE THREAD

**Issue by i-rme** [voisine/breadwallet#393]
Enable HSTS Preload in bitcoin.org domain to avoid MITM attacks

At present, the Bitcoin.org domain sends this header
`Strict-Transport-Security: max-age=0`

This header is also known as HSTS, it tells the browser to only connect using HTTPS for the next 0 days.

The problem appears when the client is visiting breadwallet.com for the first time (or in incognito mode, or has deleted cache, etc.) The browser does not know that has to use HTTPS to browse to breadwallet.com so when the user types the domain in his browser he will be connecting to http://breadwallet.com instead of https://breadwallet.com. If the network is being attacked he will be downloading malware instead of Bitcoin software.

**How to fix it:**
Add the includeSubDomains and preload directive to the header sent.
`Strict-Transport-Security: max-age=31536000; includeSubDomains; preload`

Then just submit bitcoin.org domain to the HSTS Preload list in Chrome, Firefox and IE. This can be done easily just by clicking this link:
https://hstspreload.appspot.com/?domain=breadwallet.com

**Once submitted the next releases of the browsers will include breadwallet.com in the HSTS Preload list and no one could load breadwallet.com via HTTP again.**

As an example, bitcoin-related websites already using HSTS preloading include Coinbase, Coinapult, Bitgo, Localbitcoins, bitcoin.de, blockchain.info, GDAX and Multibit.

**Comment by samuraisam** [comment]
Yep, this is already on our list, thanks!
