### ISSUE TITLE
[Question] Is there a way to sweep private key from wallet ?

### ISSUE THREAD

**Issue by IpsmLorem** [voisine/breadwallet#398]
Just wondering, is there a way to see the private keys to be able to sweep them to another wallet.

A use case: breadwallet to get some small tips. Sweep them all to a desktop wallet for long term offline storage.

**Comment by voisine** [comment]
We recommend you just send the funds from breadwallet to your offline storage.

Your private keys can all be generated from your recovery phrase. It uses an open standard. (BIP39 with the default BIP32 m/0h/0 and m/0h/1 key derivation paths)

**Comment by IpsmLorem** [comment]
But what about the case where breadwallet is down ? 
People would want to sweep their money from breadwallet to another one. 
How to escape the jail without beeing able to access the private keys (seeds is more difficult since every wallet have their own seed / derivation algorithm)

**Comment by voisine** [comment]
breadwallet can't really go "down". It's an open source app that connects to the bitcoin network.

Also, as I mentioned, we use industry standard BIP39 with the default BIP32 derivation path. There are many open source and online tools you can use.
