### ISSUE TITLE
simple copy ux enhancement

### ISSUE THREAD

**Issue by abgit** [voisine/breadwallet#399]
Hi,

When we select a transaction and click on **transaction id** we get that info copied to clipboard.
That's expected but.. transaction id is copied with a space/nline in the middle (like is displayed on app).

What do you think to change this behavior so that when we copy transaction id full transaction string is stored in clipboard (without middle space) ?

best,
FA

**Comment by dabura667** [comment]
+1

**Comment by voisine** [comment]
fixed by 5a98437

this will be in the next app store update
