### ISSUE TITLE
App crashes when scanning non-bitcoin QR codes

### ISSUE THREAD

**Issue by federicobond** [voisine/breadwallet#401]
I can provide crash logs if necessary.

App version: 0.6.4 - 46

**Comment by andrewla** [comment]
I get a "not a valid bitcoin address" when I try to view a simple url (followed by "couldn't make payment: unexpected response from www.google.com"; I used the qr code below, which goes to "https://www.google.com?q=this+is+a+test").  Could you attach an image of the actual qr code that caused the crash?

![selection_20161116-13 30 40-001](https://cloud.githubusercontent.com/assets/795760/20360246/fe187a8e-ac00-11e6-8223-a8e8a99d28c9.png)

**Comment by voisine** [comment]
Actually both of those are bugs... it shouldn't close the camera, it should just show a red camera guide. 

@federicobond, yes if you can show the the qr, or the text it contains, that will help us reproduce the issue.

**Comment by federicobond** [comment]
Some of the examples that crash, from a quick Google search:

http://cdnqrcgde.s3-eu-west-1.amazonaws.com/wp-content/uploads/2013/11/jpeg.jpg
http://www.appcoda.com/wp-content/uploads/2013/12/qrcode.jpg
http://www.penadelarosa.com/wp-content/uploads/2013/10/qrCodeEncurtido.jpg
