### ISSUE TITLE
Can't build and run master branch

### ISSUE THREAD

**Issue by vinayTree** [voisine/breadwallet#406]
![screen shot 2017-01-12 at 1 08 55 pm](https://cloud.githubusercontent.com/assets/25073192/21881105/7234d36a-d8c8-11e6-9a42-5e5dbd6e12b7.png)
i have attached my issues with screen shot for your reference i am unable to run this buid please suggest me what i can do to resolve it 

Thanks
vinay

**Comment by samuraisam** [comment]
You have to alter the group IDs and app IDs everywhere, not just in the app build, but in all the dependent builds and associated files.

**Comment by vinayTree** [comment]
Thanks for the replay

**Comment by vinayTree** [comment]
Thanks for the feedback Mr. Samuel i tried it still its not running its
giving error as Shell Script Invocation Error (Command /bin/sh failed with
exit code 128. Im really thankful to your suggestion and its really helped
me but i have now stuck with the above error please help me to solve this
issue.

Thanking You,
Vinay
