### ISSUE TITLE
Not able to bulid 

### ISSUE THREAD

**Issue by vinayTree** [voisine/breadwallet#410]
not running its giving error as Shell Script Invocation Error (Command /bin/sh failed with exit code 128. Im really thankful to your suggestion and its really helped me but i have now stuck with the above error please help me to solve this issue.

**Comment by samuraisam** [comment]
Please provide more information about the error so we can help you. Xcode can provide the output of the shell command.

**Comment by vinayTree** [comment]
thanks for the replay, i found an error as 
fatal: Not a git repository (or any of the parent directories): .git
Command /bin/sh failed with exit code 128
i'm very thankful to u for your quick response
![screen shot 2017-01-18 at 4 48 30 pm](https://cloud.githubusercontent.com/assets/25073192/22062146/52579444-dd9e-11e6-862d-e6754bb7d584.png)

**Comment by samuraisam** [comment]
I'm guessing this is because you downloaded a zip distribution. You need to have git installed and have cloned the repository for building to work.

**Comment by vinayTree** [comment]
Thanks for the replay and i'm very happy that its worked on simulator but i'm still facing problem with iphone device where the build is giving certain errors which i have attached below please have a look 
![screen shot 2017-01-20 at 7 04 53 pm](https://cloud.githubusercontent.com/assets/25073192/22151338/b229c454-df43-11e6-8f4c-1e72a8ebc52b.png)
