### ISSUE TITLE
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang failed with exit code 1

### ISSUE THREAD

**Issue by gautamsareriyamt** [voisine/breadwallet#411]
I am unable to build the code.
![screen shot 2017-02-02 at 11 37 14 am](https://cloud.githubusercontent.com/assets/25502352/22544348/5e5fb574-e95a-11e6-82fd-bf72073d3c5e.png)

Is anybody any suggestion or answer please give your valuable reply.

**Comment by voisine** [comment]
you have to use git clone instead of downloading the zip, we're using git submodules for dependencies
