### ISSUE TITLE
Can't create new wallet when forgot PIN

### ISSUE THREAD

**Issue by keo** [voisine/breadwallet#414]
I have a friend who needs to re-create his wallet. He doesn't have funds locked in.

He doesn't have the passphrase written down, and breadwallet started asking for his PIN code after the freshest update.

He'd like to simply start over, but can't get to the hamburger menu to reset his wallet, as the PIN code entry dialog always pops up.

If he taps on reset, he has to enter the passphrase, which he doesn't have.

Uninstalling / reinstalling doesn't help, he gets back the same wallet.

Any ideas how to solve this?

**Comment by voisine** [comment]
It's not very intuitive, but in this situation you have to make incorrect pin attempts (which will disable the wallet for about 24hrs). After the 8th attempt it will reset. If you do have money in it, and someone else uses your phone, this also prevents them from being able to wipe it by making multiple wrong pin attempts unless they have the device for 24hrs.

**Comment by keo** [comment]
Thank you @voisine, will try this.
