### ISSUE TITLE
PIN will not unlock wallet after upgrading to ios10.3.2

### ISSUE THREAD

**Issue by gaijininjapan** [voisine/breadwallet#422]
Since upgrading from iOS 10.3.1 to 10.3.2, I have been unable to access my wallet with the PIN code.  

Unfortunately, I did not write down the recovery phrase when setting up the wallet 2 weeks ago.  I had set up the wallet original just to check it out.  I had moved some BTC on to it until I could get a hardware wallet.  I did not expect to run in to issues in the week I used it.  Stupid, I agree, but it is what it is now.  And while it was a mistake not to write down the recovery phrase before putting BTC on it, this is not a case of a forgotten PIN.

I took an iTunes backup as I was getting to the 8 try limit on retrying PINs.  I have gone through any PIN I would use twice and still cannot get the wallet unlocked.  I tried going back to iOS 10.3.1, still no luck.  Deleting and re-installing the app also no good.  

I saw in Issue 134 that another user was able to recover the PIN and recovery phrase from the keychain.  Unfortunately this required a jailbreak and one does not yet exist for for 10.3.1.

I'm a bit puzzled at how an iOS update could do something like this, but unless I managed to somehow fumble entering in the initial PIN during setup twice, I am not seeing how this can happen.  Any ideas on a solution?

**Comment by gaijininjapan** [comment]
As I have an encrypted backup, I tried a trial version of Elcomsoft's phone breaker.  I cannot find any references to Bread Wallet in the keychain via the keychain explorer.  It seems the structure has changed?  I do not see a generic passwords table as was highlighted in Issue 134.   I only see entries for email, internet, wifi and DSIDs/tokens in the keychain.  Where else can I look?

**Comment by voisine** [comment]
this is a support issue, please contact support@breadwallet.com

(we can re-open the GitHub issue if it turns out to be a problem with the app)
