### ISSUE TITLE
Very high fee

### ISSUE THREAD

**Issue by DesWurstes** [voisine/breadwallet#423]
<a href="https://ibb.co/hsDAav"><img src="https://preview.ibb.co/cbsgha/IMG_0229.png" alt="IMG_0229" border="0"></a><br /><a target='_blank' </a><br />

**Comment by macdasi** [comment]
Can the wallet implement a scroll to set the fee per kb ?

**Comment by DesWurstes** [comment]
@voisine I need help sending money. If you can show me where the code for fee calculation is, I can do the rest.

**Comment by thesoftwarejedi** [comment]
@deswurtes he seems uninterested in helping. I'm up against the same issue. I can find the code if you can make the change. I'm a C# MS dev. This is pretty out of my ballpark.

**Comment by samuraisam** [comment]
No one is "not interested" in helping. We absolutely want to ease the pain of high transaction fees as much as possible. A new more-dynamic fee calculation will be released very soon which will keep the fees as low as possible, and is currently in the testing phase. Our target release is by the end of this week.
