### ISSUE TITLE
Old but actual question: bits vs satoshi in current amount (ios)

### ISSUE THREAD

**Issue by neeilya** [voisine/breadwallet#424]
Hi, first let me thank you for your project.
It is great and the easiest way to store/spend bitcoins on iOS platform.
Thank you very much!

The only thing which I'd like to see in other way is current representing of money on the wallet.

Right now you use bits concept which you and many other people think is convenient.
And I respect that. However, I also see many other people struggling with this and they would like
to have an option to change it.

Your wallet is being used by thousands of people, and your product has made their lives easier.
I hope you could reconsider your position and offer what people want, especially when you
say yourself that enabling it is like 2 lines of code.

Thank you very much and keep up great work!

**Comment by dabura667** [comment]
Swipe the currency mark left on the local currency select screen.

**Comment by neeilya** [comment]
lol that worked, thanks
