### ISSUE TITLE
Forgot pass phrase - can i recover through itunes restore?

### ISSUE THREAD

**Issue by sexypirate604** [voisine/breadwallet#434]
Hi guys,

Is there anyway to recover my bread wallet without a pass phrase?

I had a really bad week last week and broke two iphones but what's worse is I didn't write down my bread wallet pass phrase..

I have been able to restore my iphone using itunes, and it installed bread wallet again, but it's asking me for my pass phrase which I don't have.

Posting here is my last resort, I'm really really really hoping someone here can help me out.

Thanks,

Michael

**Comment by dabura667** [comment]
Nope. Sorry.

**Comment by samuraisam** [comment]
That is not an official statement by @dabura667. Please contact support@breadwallet.com and we'll see what we can do to help.

**Comment by sexypirate604** [comment]
Will do thank you.
