### ISSUE TITLE
Option to change 'Bits' unit to 'BTC'

### ISSUE THREAD

**Issue by Conqu3rer** [voisine/breadwallet#445]
Hey guys, I love this wallet, I have recommended it to all my friends who have recently started investing in Crypto. The only thing that is driving the new comers away from Breadwallet is the 'bits' unit. It is extremely confusing for new users. **Please add the option to display our Bitcoin in the standard 'BTC' unit instead of 'bits'.**

Since the standard BTC unit is used on every exchange site, it gets very confusing to everyone. Please consider this. 

Thanks.

**Comment by dabura667** [comment]
There is already an option to change from bits to mBTC or BTC.

The default is bits.

**Comment by jdbassa** [comment]
Go into "settings" > "local currency".

In the navigation bar you'll see something equivalent to:
> $1.00 = ƀ247.46  

Swipe left on top of that and it'll change the unit between ƀ, mɃ, and Ƀ.

**Comment by jdbassa** [comment]
Go into settings > local currency.

In the navigation bar you'll see something equivalent to:
> $1.00 = ƀ247.46  

Swipe left on top of that and it'll change the unit between ƀ, mɃ, and Ƀ.

**Comment by dabura667** [comment]
@Conqu3rer 

1. Google search "breadwallet change unit to BTC"
2. First link goes here: https://github.com/voisine/breadwallet/issues/299#issuecomment-259862939
3. Profit!

@jdbassa Thanks!

**Comment by Conqu3rer** [comment]
Oh wow, that actually helped a lot. I never knew they implemented this feature! Thanks guys.
