### ISSUE TITLE
Breadwallet showing invalid receiving address (but looks valid at first glance)

### ISSUE THREAD

**Issue by teran-mckinney** [voisine/breadwallet#448]
Hi,

Breadwallet is showing a receiving address of `1CACEGxsJpXwFQRMdYCC3BV6RnvikQ2grY` which is not a valid address at all. This is using the latest Breadwallet from the Apple Store on the latest IOS, on a 5S.

Do you have any idea of what's going on? I'm extremely confused.

Thanks,

Teran

**Comment by voisine** [comment]
It appears to be valid: https://blockchain.info/address/1CACEGxsJpXwFQRMdYCC3BV6RnvikQ2grY

**Comment by teran-mckinney** [comment]
I'm sorry about this. I tested multiple times with multiple block chains and it showed up as invalid in them. It's fine for me now as well. I wonder if there was some kind of copy/paste bug on my end.
