### ISSUE TITLE
Feature Request: Export Transaction List

### ISSUE THREAD

**Issue by bhuddleston42** [voisine/breadwallet#45]
It would be cool if you could email/export your list of transactions.  Even something as simple as:
DateTime,Address,Bits Amount,Comments (if you add comments later)

In the deterministic world there is really no way to get this list unless your wallet software cooperates.  Maybe something like Armory's Export Transactions?

(I was half way through writing a web app called bitLedger to let me track things for self-accounting and tax purposes when I fell in love with the deterministic wallet idea which kind of breaks my idea of showing an address history from the blockchain and letting you add metadata to it).

**Comment by keo** [comment]
Exporting a CSV/QIF file by email would be really cool. Probably doesn't require too much development.

**Comment by voisine** [comment]
Thinking of adding this as an app callback url. Where another app (or a user could do it manually) calls a bread://txexport url that launches breadwallet and asks the user if they want to authorize the export.

**Comment by jakerich** [comment]
I would like a way to export my transactions and a way to sign messages. A separate tool would be Ok, but the ability to do this within the App would be better.

**Comment by voisine** [comment]
You can now export a list of addresses with bread://addresslist which you can use to get a list of transactions.

Signing would be a nice feature. it could be added as another bread: url without any extra UI clutter. You do expose your pubkey, but there's no known weaknesses until we get quantum computing. I'd personally rather not expose pubkeys for addresses with a balance.

**Comment by jakerich** [comment]
I like the bread://addresslist url, thank you for pointing that out. Would it be possible to keep message signing inside the app as a third item on the menu screen to keep the pubkey contained? Or is the pubkey exposed regardless of how you sign a message? I know that most Bitcoin users have no need to sign messages, but adding it would make this app complete and help the 10% of us out who do need to sign from time to time.

**Comment by dabura667** [comment]
> pubkey exposed regardless of how you sign a message?

Yes. Your pubkey is exposed via the r and s value of the signature. Most "Sign Message" features in other wallets actually don't include the pubkey in the sig and actually use the sig to calculate the pubkey and they verify with it.

Your public key will be leaked by signing anything and making it public.

**Comment by jakerich** [comment]
Is the public key leaked due to the wallet being deterministic? Is there any way to not leak it? As stated above, the Core Wallet does not appear to leak my pubkey.

**Comment by dabura667** [comment]
> the Core Wallet does not appear to leak my pubkey.

It does.

In order to verify ANY signature, the pubkey is NECESSARY.

The method in which you can recover the pubkey from the r and s value of the signature in ECDSA is written at the following: http://www.secg.org/sec1-v2.pdf  (Chapter 4.1.6)

A python implementation in Electrum:
https://github.com/spesmilo/electrum/blob/0b874b2bb03250584ef1bfc35f9151868595ffb7/lib/bitcoin.py#L471

This is the same method Bitcoin Core uses to recover the pubkey and verify that 1. the pubkey hash turns into the address you entered, and 2. that the signature matches the pubkey.

**Comment by jakerich** [comment]
Thank you for the links. Does that essentially mean that **any** signing of messages has the potential to leak the pubkey, even if indirectly? So adding it to breadwallet would not necessarily be any more risky than how it works in the Qt Wallet?

**Comment by dabura667** [comment]
> has the potential

No. It IS the pubkey. Someone just needs to calculate it. You are merely obfuscating it.

Like I could encode my message in pig latin and people could decode it if they wanted to take the time:

Ooday ouyay eakspay igpay atinlay?

**Comment by dabura667** [comment]
However, in breadwallet, the only danger of pubkey leakage is leaking of the MASTER pubkey... so as long as the signing key is always a derived key and is always using RFC6979 (which breadwallet does) then there is 0 risk. (virtually)

**Comment by jonasschnelli** [comment]
Message signing should be done with a different hd chain path then the path used for creating "coin keys". Public keys are public and if they don't collide with your coin keys I don't see how this could harm your privacy.

**Comment by jakerich** [comment]
Thank you for the detailed explanation. I see what you mean, security by obscurity is not security. So, having this feature in breadwallet would be nice: **bread://signmessage**

**Comment by voisine** [comment]
@jonasschnelli, having a separate chain is definitely what we'd do for website authentication or the like, but what I believe is being requested here is to prove you are the owner of a bitcoin address.

@jakerich I think what you're missing is that you *need* to know the pubkey in order to verify a signature. With bitcoin however you can keep it hidden until you spend funds. Spending reveals it in the tx signature.

**Comment by jakerich** [comment]
@voisine if you did implement signing would signing via breadwallet be any more risky than signing via Bitcoin Core wallet? Does breadwallet require that the pubkey be sent and the Core client does not?

**Comment by voisine** [comment]
No, it would be the same as core, however one presumes that core users are already security nerds and understand the risks, since you would need to be in order to harden a desktop system against malware. There are plenty of stories of non-security experts holding bitcoin in the core bitcoin wallet and getting robbed from malware or otherwise getting hacked.

**Comment by jakerich** [comment]
@voisine Ok, I get it now. The Core does, or did warn, about the risks at one time. Saying BEWARE the risks of signing. If you do decide to add the feature I think it should definitely be hidden using the breadwallet://address method to protect users from themselves. You have made a really great piece of software.

**Comment by BM5k** [comment]
As far as exporting transaction history (csv, json, w/e) you could export them to the iTunes document share. VLC lets you manage media this way, and several other apps use it as a way to get sensitive data too and from iOS devices (like ssh keys).

**Comment by voisine** [comment]
That's an interesting technique I hadn't considered. It doesn't look like it works for sharing between iOS apps though, correct?

**Comment by BM5k** [comment]
I don't think it will work for sharing, but if you're already generating a file to be copied to the clipboard you could export it to iTunes or even the share sheet to be imported into another app? Share sheets seem to be gaining traction: workingcopy, transmit, and evernote are a few off the top of my head examples.

**Comment by keo** [comment]
I like the ideo of exporting the transaction list through sharing :)
