### ISSUE TITLE
Add other government issued currencies as well.

### ISSUE THREAD

**Issue by keo** [voisine/breadwallet#57]
It would be great to have all currencies from BitcoinAverage.com.
I miss HUF myself.
Thank you.
(Too bad I don't know Obj-C)

**Comment by voisine** [comment]
Hungarian Forint, Norwegian Krone, Gold troy ounce, and Silver troy ounce now supported along with 150+ other currencies via bitpay.com/rates

(next up is multiple exchange rate sources)

**Comment by keo** [comment]
Thanks. When will this version be out in the App Store?

**Comment by voisine** [comment]
This will coming out probably in the next two weeks along with internationalization.
