### ISSUE TITLE
Application Reset

### ISSUE THREAD

**Issue by jasadams** [voisine/breadwallet#59]
The user has lost their backup phrase and forgotten their PIN. They have accepted that their bitcoin balance is lost and want to start again. I don't believe you can do this currently in the application as you need to type in the backup phrase to reset and without the PIN you cannot view the backup phrase

**Comment by voisine** [comment]
The app now will auto-reset after the 8th failed pin attempt (which includes over 24hrs of lockout period so someone can't borrow your phone and wipe it)
