### ISSUE TITLE
Localization for breadwallet

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#66]
Just a recommendation:

https://crowdin.com/page/open-source-project-setup-request

Crowd source your localization for free. (They give out free accounts to Open Source Projects)

tbh, not much text... but talking about the seed warnings in the other thread made me want to translate them.

**Comment by peritus** [comment]
I'd be happy to contribute a german translation.

**Comment by pryds** [comment]
Oh, I guess I forgot to mention in my previous message: I'd like to contribute a Danish translation if the project is set up at Transifex or Crowdin.

**Comment by dabura667** [comment]
https://developer.apple.com/library/ios/documentation/MacOSX/Conceptual/BPInternational/LocalizingYourApp/LocalizingYourApp.html

This makes exporting strings sound super easy...

It's probably not that easy, right?

**Comment by dabura667** [comment]
Bump

I have many many friends here in Japan that are starting to ask about bitcoin and I have to show them inferior apps because they can not understand your app's warning messages etc.

Any work that I can do to help you prepare for localization I will do, so please let me know what needs to happen before we can get started.

Thank you.

**Comment by voisine** [comment]
I agree this is a top priority. I'll probably set it up on transifex and/or crowdin this week.

**Comment by dabura667** [comment]
I appreciate it. Once a link pops up I'll get Japanese done asap.

**Comment by dabura667** [comment]
Also, support for the Japanese wordlist would also be appreciated.

Word wrapping might be a problem though... (we ran into that with Electrum)

**Comment by dabura667** [comment]
checking the screen you display the phrase on, and counting 2 english letters as 1 Japanese character, it looks like 18 characters is the limit for one line. (36 english letters)

If there is some way to make word wrapping keep each word intact and wrapping at the ideographic space, that would be ideal, but looking at the largest word (たりきほんがん) only 2 of them can fit on one line.

One other way I was thinking was splitting the words with a line break, so instead of

(Numbers added for illustration)
1たりきほんがん　2たりきほんがん
3たりきほんがん　4たりきほんがん
5たりきほんがん　6たりきほんがん...

Maybe it would be easier to do:
1たりきほんがん
2たりきほんがん
3たりきほんがん...

**Comment by dabura667** [comment]
By the way Electrum dealt with the problem in the phrase hashing procedure. (since Electrum is no longer BIP39 compliant anyways, it removes all spaces (both ideographic and not) before hashing. This solves the problem of a user accidentally viewing one word as multiple words because of a line break.)

**Comment by pryds** [comment]
> If there is some way to make word wrapping keep each word intact and wrapping at the ideographic space, that would be ideal,

I can't help but wonder whather this wouldn't be a problem in many, if not most, localization projects involving Japanese. Isn't there some sort of Unicode control character which doesn't show up in the text but marks a place in the text where it is ok to insert a line break if needed? Sort of a reversed non-breaking-space that doesn't print out anything but allows line breaks.

Perhaps the [BPH character](http://en.wikipedia.org/wiki/C0_and_C1_control_codes) ("Break Permitted Here") can be of some use for this? I am not aware whether that would be incorrect use, but maybe it's worth investigating?

**Comment by voisine** [comment]
finally got setup for translation, initially on crowdin.

https://crowdin.com/project/breadwallet

If anyone greatly prefers transifex for a language they'd like to translate to, we can set it up there as well.

**Comment by pryds** [comment]
Personally, I prefer Transifex, but I can do Crowdin. It probably would be a mess for you to use two platforms?

Anyway, I can't seem to request the addition of a language on Crowdin. Can you add Danish (da or da_DK)?

**Comment by keo** [comment]
Awesome :)

Can you add Hungarian? (hu-hu)

**Comment by traidman** [comment]
Hungarian and Danish have been added to the crowdin project

Thanks for your help in the translations!

**Comment by keo** [comment]
@voisine how can I export from Crowdin and check a build with new translations? Do I need any special role on the project or can I do it myself?
(Hungarian phrases are a bit longer, and the UI needs to be checked)

Thanks for helping.

**Comment by voisine** [comment]
@keo thanks for checking that, I was actually going to do that myself starting this afternoon. Once I check it in then it should be easy to update with new translations. I'll let you know.

**Comment by voisine** [comment]
Just committed the initial translations. For hungarian, looks like we're still waiting on the rest of localizable.strings. Do you want me to add it in as-is? I'm not sure if it defaults to english or machine translation for the not-yet-translated portions.

**Comment by keo** [comment]
almost done with Hungarian.

there's so many little details that it would be good to properly test all phrases on the UI.

Is there a way to easily show all views in XCode without having to manually click through all different edge cases in the simulator?

**Comment by voisine** [comment]
Thanks so much for the translation help. I'm not sure if there's a way to do what you suggest in Xcode or the simulator, but I will see what I can figure out. You are right that there are some areas of the UI that are not so easy to quickly try out.

**Comment by jonasschnelli** [comment]
You could use UI Automation (https://developer.apple.com/library/ios/documentation/DeveloperTools/Conceptual/InstrumentsUserGuide/UsingtheAutomationInstrument/UsingtheAutomationInstrument.html). There you could run scripts which do create some screenshots. But it is time consuming and there is no easy way to integrate this into a CI system. I once created a semi-automatic way (not with Apples UI Automation) of creating i18n UI screens within a other wallet app development (https://github.com/MacWallet/MacWallet/wiki/_pages). Code: https://github.com/MacWallet/MacWallet/tree/master/MacWalletApp/MacWalletTests

**Comment by keo** [comment]
Hungarian phrases are 100% translated now, so a preliminary version can be committed for testing.

I still need to vet all phrases and also check them on the UI to see if everything looks fine.

Should be good to go soon.

**Comment by voisine** [comment]
@keo I committed the hungarian translation to git, thank you.

@jonasschnelli I will look into this, sounds like a pain, but would be worth it if it improves the quality of translations... I'm a little scared that I have no way to personally verify the quality, but I suppose that's true for every software developer that's not a hyperpolyglot

**Comment by keo** [comment]
@voisine thank you. I am updating translations now.

How can I invoke showBackupDialogIfNeeded() so it shows the popup? There's a string there that I'd need to see while running.

**Comment by keo** [comment]
Tested most of it (excluding the backup notification dialog). Here's the PR: https://github.com/voisine/breadwallet/pull/192

**Comment by voisine** [comment]
@keo after testing 10+ languages I've made some general improvements throughout the UI to make it more flexible for translation. All the buttons now have auto-layout width ranges instead of fixed widths, and buttons and labels have adjustsFontSizeToFitWidth and adjustsLetterSpacingToFitWidth set.

**Comment by voisine** [comment]
This will always be ongoing, but I think we can say this one is addresses. Yay!
