### ISSUE TITLE
Testflight / Hockeyapp project for beta testers

### ISSUE THREAD

**Issue by dabura667** [voisine/breadwallet#69]
Just creating a thread here for people to post their UDIDs.

Remember: Most apps give you a fake UDID that starts with FFFFFF

Here's my UDID
UDID: 854F71BA0C925661672AEA8856CB484428568C5E

**Comment by dabura667** [comment]
Bumping this issue for everyone watching.

@voisine Do you have any ballpark of when testflight will be up?

**Comment by voisine** [comment]
I was going to do this but apple requires that test distributions go through the week long review process, amazingly. Crazy.

**Comment by dabura667** [comment]
HockeyKit is also an option, and it's open source.

http://hockeykit.net/

**Comment by nshopik** [comment]
@voisine I've receive apps in testflight in next day after dev posted it for review.

**Comment by voisine** [comment]
I will try it again for the next update and see how long it takes.

**Comment by voisine** [comment]
Looks like they've got the approval process more streamlined. Anyone who wants to test the beta release send me your iTunes account email address.

**Comment by nshopik** [comment]
@voisine is beta release will be running on testnet?

**Comment by voisine** [comment]
No, it's on mainnet, but I could do a separate release of another app called testbread or something.
