### ISSUE TITLE
The app crashes when restoring a wallet from backup phrase

### ISSUE THREAD

**Issue by les-sosna** [voisine/breadwallet#95]
iPad mini, iOS 8.0.2
breadwallet 0.4.2

I wanted to check how backup works so I wiped an empty wallet and tried to recreate it from the backup phrase. When I entered the phrase my screen turned black and the app was not responding for a minute. I restarted the app and it started syncing. At approximately 65 percent the progress indicator stopped for a long time and then the app crashed.

**Comment by voisine** [comment]
@truongvinht we were able to narrow this down to a core data corruption issue. Leaving the issue open until I'm able to get a fix in that can detect and correct it short of reinstalling the app.
